import type { EquipmentKind,Tank } from "./types";

export interface EquipmentCareGuide{
  kind:EquipmentKind;
  aliases:string[];
  titleAr:string;
  titleEn:string;
  intervalAr:string;
  intervalEn:string;
  stepsAr:string[];
  stepsEn:string[];
  cautionsAr:string[];
  cautionsEn:string[];
}

export const EQUIPMENT_CARE_GUIDES:EquipmentCareGuide[]=[
 {kind:"skimmer",aliases:["سكيمر","skimmer","protein skimmer"],titleAr:"صيانة السكيمر",titleEn:"Skimmer maintenance",intervalAr:"نظف الكوب والرقبة كل عدة أيام حسب التراكم، وافحص المضخة والـventuri عادةً كل 1–3 أشهر.",intervalEn:"Clean the cup/neck every few days as buildup requires; inspect the pump and venturi roughly every 1–3 months.",stepsAr:["افصل الكهرباء عن السكيمر قبل الفك.","افرغ كوب التجميع ونظف الكوب والرقبة بماء دافئ وفرشاة ناعمة.","افحص خرطوم الهواء والـventuri وأزل أي ترسب ملحي أو انسداد.","إذا حان تنظيف المضخة: فكها حسب دليلها، نظف الـimpeller والحجرة من الكلس والترسبات ثم اشطف جيداً.","أعد التركيب، شغّل السكيمر، وتأكد من تدفق الهواء والماء وعدم وجود اهتزاز أو تسريب.","بعد التنظيف راقب مستوى الرغوة؛ قد يحتاج السكيمر وقتاً قصيراً ليستقر من جديد."],stepsEn:["Disconnect power before disassembly.","Empty and clean the collection cup and neck with warm water and a soft brush.","Inspect the air hose and venturi; remove salt creep or blockage.","When pump service is due, disassemble per its manual, clean the impeller/chamber of deposits, then rinse thoroughly.","Reassemble, power on, and verify air/water flow with no abnormal vibration or leaks.","After cleaning, watch foam height; the skimmer may need a short break-in period again."],cautionsAr:["لا تستخدم صابون أو منظفات منزلية داخل أجزاء تلامس ماء الحوض.","لترسبات الكلس استخدم نقعاً مناسباً مثل حمض الستريك المخفف ثم اشطف جيداً.","إذا كان الموديل له تعليمات خاصة، دليل الشركة يتقدم على الخطوات العامة."],cautionsEn:["Do not use soap or household cleaners on water-contact parts.","For mineral deposits, use an appropriate mild citric-acid soak and rinse thoroughly.","If the model has specific instructions, the manufacturer manual takes priority over this general guide."]},
 {kind:"returnPump",aliases:["مضخة الراجع","مضخه الراجع","return pump","main pump"],titleAr:"صيانة مضخة الراجع",titleEn:"Return-pump maintenance",intervalAr:"فحص بصري أسبوعي وتنظيف داخلي عادةً كل 1–3 أشهر حسب الترسبات.",intervalEn:"Visual check weekly; internal cleaning typically every 1–3 months depending on deposits.",stepsAr:["افصل الكهرباء وأغلق الصمامات إن وجدت.","فك المضخة وسجل اتجاه القطع قبل التفكيك.","نظف الـimpeller والحجرة والمداخل من الرواسب والطحالب.","افحص الـO-rings والتشققات والكابل.","اشطف وأعد التركيب وافتح الصمامات قبل التشغيل.","تأكد من رجوع التدفق الطبيعي وعدم وجود ضجيج أو تسريب."],stepsEn:["Disconnect power and close valves if fitted.","Remove the pump and note part orientation before disassembly.","Clean the impeller, chamber, and inlets of deposits/algae.","Inspect O-rings, cracks, and cable condition.","Rinse, reassemble, and reopen valves before powering on.","Verify normal return flow with no abnormal noise or leaks."],cautionsAr:["لا تشغل المضخة جافة.","لا تفك جزءاً محكماً أو مختوماً لا يطلب الدليل فكه."],cautionsEn:["Do not run the pump dry.","Do not open sealed parts unless the manual specifically allows it."]},
 {kind:"waveMaker",aliases:["ويف ميكر","مضخة موج","مضخه موج","wavemaker","wave maker","powerhead"],titleAr:"صيانة مضخة الموج",titleEn:"Wave-maker maintenance",intervalAr:"تنظيف كل 1–2 شهر عادةً أو أسرع إذا انخفض التدفق.",intervalEn:"Typically clean every 1–2 months, sooner if flow drops.",stepsAr:["افصل الكهرباء.","فك الغطاء والـpropeller حسب التصميم.","نظف الكلس والطحالب بفرشاة ناعمة ونقع مناسب عند الحاجة.","افحص المحور أو البوشات وأي اهتزاز غير طبيعي.","اشطف وأعد التركيب ثم تأكد من اتجاه التدفق الصحيح."],stepsEn:["Disconnect power.","Remove the guard and propeller as designed.","Clean mineral scale/algae with a soft brush and suitable soak if needed.","Inspect shaft/bushings and any abnormal vibration.","Rinse, reassemble, and confirm correct flow direction."],cautionsAr:["لا تشغلها خارج الماء إذا كان الموديل غير مصمم لذلك."],cautionsEn:["Do not run it out of water unless the model is designed for it."]},
 {kind:"heater",aliases:["سخان","heater"],titleAr:"فحص وصيانة السخان",titleEn:"Heater check & maintenance",intervalAr:"فحص بصري شهري ومقارنة الحرارة بمرجع مستقل دورياً.",intervalEn:"Visual check monthly; periodically compare temperature with an independent reference.",stepsAr:["افصل الكهرباء واترك السخان يبرد قبل إخراجه.","افحص الزجاج/الغلاف والكابل وأي صدأ أو تكاثف غير طبيعي.","نظف الترسبات بلطف.","قارن قراءة الحرارة بترمومتر مستقل.","تأكد من تثبيته بمكان تدفق ماء مناسب."],stepsEn:["Disconnect power and let the heater cool before removal.","Inspect glass/housing, cable, rust, or abnormal condensation.","Gently clean deposits.","Compare temperature against an independent thermometer.","Ensure placement has adequate water flow."],cautionsAr:["أي تشقق أو تسرب داخل السخان = استبدال، لا إصلاح منزلي."],cautionsEn:["Any crack or internal leak means replacement, not a DIY repair."]},
 {kind:"filterSock",aliases:["جراب","جوارب","فلتر سوك","filter sock","sock"],titleAr:"تنظيف جراب الفلترة",titleEn:"Filter-sock cleaning",intervalAr:"عادةً كل 2–4 أيام أو عند ارتفاع مستوى الماء/انخفاض التدفق.",intervalEn:"Usually every 2–4 days, or when water level rises/flow drops.",stepsAr:["أخرج الجراب المتسخ بدون نشر الرواسب بالحوض.","اشطفه بقوة بماء مناسب حتى يزول معظم الوسخ.","استخدم جراباً احتياطياً نظيفاً مباشرةً.","اترك الجراب المنظف يجف تماماً قبل التخزين أو الاستخدام التالي."],stepsEn:["Remove the dirty sock without dumping debris back into the tank.","Rinse thoroughly until most debris is removed.","Install a clean spare immediately.","Let the cleaned sock dry fully before storage or reuse."],cautionsAr:["إذا استُخدم أي مطهر بطريقة مخصصة للغسيل، يجب إزالة بقاياه بالكامل وتجفيف الجراب تماماً قبل إعادته؛ الأسلم تجنب المنظفات المعطرة."],cautionsEn:["If a dedicated sanitizing method is used, all residue must be removed and the sock fully dried; avoid scented cleaners."]},
 {kind:"rollerFilter",aliases:["رولر","roller filter","roller"],titleAr:"صيانة رولر الفلترة",titleEn:"Roller-filter maintenance",intervalAr:"فحص أسبوعي وتنظيف الحساس/مسار الرول حسب تراكم الأوساخ.",intervalEn:"Inspect weekly; clean the sensor/roller path as buildup requires.",stepsAr:["افصل الكهرباء قبل العمل على المحرك.","افحص الرول وحرية حركته وعدم انحرافه.","نظف حساس مستوى الماء من الرواسب.","نظف بكرات التوجيه ومسار القماش.","تأكد من عمل المحرك والتغذية اليدوية قبل الإغلاق."],stepsEn:["Disconnect power before working on the motor.","Check the roll for free movement and alignment.","Clean the water-level sensor.","Clean guide rollers and fleece path.","Verify motor/manual feed operation before closing."],cautionsAr:["لا تشد الرول بقوة على المحرك أو التروس."],cautionsEn:["Do not force the roll against the motor or gears."]},
 {kind:"doser",aliases:["دوزر","مضخة جرعات","مضخه جرعات","doser","dosing pump"],titleAr:"صيانة الدوزر",titleEn:"Doser maintenance",intervalAr:"فحص الخطوط أسبوعياً ومعايرة دورية حسب الدقة والمادة المستخدمة.",intervalEn:"Inspect lines weekly and recalibrate periodically based on accuracy and fluid used.",stepsAr:["افحص الأنابيب والوصلات من التسريب أو الهواء.","اعمل اختبار جرعة في مخبار مدرج وقارن الحجم الفعلي بالمبرمج.","نظف أو استبدل الأنابيب المستهلكة حسب نوع المضخة.","تأكد من عدم وجود ترسب عند نهايات الجرعات.","حدّث المعايرة في البرنامج بعد القياس."],stepsEn:["Inspect tubing/connections for leaks or air.","Run a test dose into a graduated cylinder and compare actual vs programmed volume.","Clean or replace worn tubing according to pump type.","Check dosing outlets for precipitate buildup.","Update calibration after measurement."],cautionsAr:["لا تعمل جرعة تصحيحية كبيرة قبل التأكد من المعايرة والقراءة الكيميائية."],cautionsEn:["Do not make a large corrective dose before confirming calibration and chemistry readings."]},
 {kind:"uv",aliases:["uv","يو في","معقم","معقم uv","sterilizer"],titleAr:"صيانة UV",titleEn:"UV maintenance",intervalAr:"تنظيف الـquartz sleeve دورياً واستبدال اللمبة حسب ساعات الشركة.",intervalEn:"Clean the quartz sleeve periodically and replace the lamp according to manufacturer rated hours.",stepsAr:["افصل الكهرباء وأوقف تدفق الماء.","اترك الوحدة تبرد ثم فكها حسب الدليل.","نظف الـquartz sleeve بلطف من الكلس.","افحص الـO-rings ونظفها.","أعد التجميع، شغّل الماء أولاً وتأكد من عدم وجود تسريب، ثم الكهرباء."],stepsEn:["Disconnect power and stop water flow.","Let the unit cool, then disassemble per the manual.","Gently clean mineral scale from the quartz sleeve.","Inspect and clean O-rings.","Reassemble, restore water first and check for leaks, then power."],cautionsAr:["لا تنظر مباشرةً إلى لمبة UV وهي تعمل.","لا تشغل اللمبة خارج جسمها المغلق."],cautionsEn:["Never look directly at an operating UV lamp.","Do not run the lamp outside its closed housing."]},
 {kind:"ato",aliases:["ato","تعويض تبخر","اوتو توب اوف","auto top off"],titleAr:"صيانة ATO",titleEn:"ATO maintenance",intervalAr:"فحص الحساس أسبوعياً وتنظيفه عند أي ترسب.",intervalEn:"Inspect the sensor weekly and clean whenever buildup appears.",stepsAr:["اختبر الحساس يدوياً وتأكد أن المضخة تتوقف عند المستوى المطلوب.","نظف الحساس أو العوامة من الكلس والطحالب.","افحص خرطوم التعويض لمنع السيفون العكسي.","اختبر إنذار/حماية التشغيل الجاف إن وجدت."],stepsEn:["Manually test the sensor and verify the pump stops at the intended level.","Clean the sensor/float of scale and algae.","Inspect tubing to prevent back-siphon.","Test dry-run/alarm protection if available."],cautionsAr:["أي خلل بالـATO ممكن يغير الملوحة بسرعة؛ اختبره بعد كل تنظيف."],cautionsEn:["ATO faults can change salinity quickly; test it after every cleaning."]},
 {kind:"probe",aliases:["بروب","مجس","حساس","probe","sensor"],titleAr:"صيانة ومعايرة المجس",titleEn:"Probe maintenance & calibration",intervalAr:"تنظيف خفيف ومعايرة حسب نوع المجس ودليل الشركة.",intervalEn:"Gentle cleaning and calibration according to probe type and manufacturer guidance.",stepsAr:["اشطف رأس المجس بماء مناسب بدون فرك قوي.","نظف حسب تعليمات نوع المجس.","عاير باستخدام محاليل معايرة صالحة وغير ملوثة.","قارن القراءة بمرجع مستقل إذا أمكن.","سجل تاريخ المعايرة."],stepsEn:["Rinse the probe tip without aggressive scrubbing.","Clean according to probe-specific instructions.","Calibrate with valid, uncontaminated standards.","Compare against an independent reference when possible.","Log the calibration date."],cautionsAr:["لا تترك بعض المجسات تجف؛ اتبع تعليمات التخزين الخاصة بها."],cautionsEn:["Some probes must not dry out; follow their storage instructions."]},
 {kind:"overflow",aliases:["اوفر فلو","overflow","weir"],titleAr:"فحص الأوفر فلو",titleEn:"Overflow inspection",intervalAr:"فحص أسبوعي وتنظيف عند تراكم الطحالب أو الرواسب.",intervalEn:"Inspect weekly and clean when algae/debris accumulate.",stepsAr:["افحص الأسنان/الشبك من الانسداد.","تأكد من عدم وجود حلزون أو جسم يعيق المواسير.","راقب مستوى الماء والأصوات غير الطبيعية.","نظف المنطقة مع الحفاظ على إعدادات الصمامات الحالية.","اختبر رجوع الماء بعد إعادة التشغيل."],stepsEn:["Check teeth/screens for blockage.","Ensure no snail/object restricts plumbing.","Observe water level and abnormal noise.","Clean while preserving valve settings.","Test restart and return flow afterward."],cautionsAr:["لا تغيّر صمام drain الحرج عشوائياً قبل معرفة ضبط النظام."],cautionsEn:["Do not randomly change a critical drain valve before understanding system tuning."]},
 {kind:"other",aliases:["جهاز","equipment"],titleAr:"صيانة جهاز الحوض",titleEn:"Aquarium equipment maintenance",intervalAr:"حسب دليل الجهاز وحالته الفعلية.",intervalEn:"According to the device manual and actual condition.",stepsAr:["افصل الكهرباء إذا كان العمل يتطلب فك الجهاز.","افحص الاتساخ والتسريب والكابل والوصلات.","نظف الأجزاء المسموح تنظيفها حسب الدليل.","أعد التركيب واختبر التشغيل قبل اعتماد الصيانة مكتملة."],stepsEn:["Disconnect power if service requires disassembly.","Inspect buildup, leaks, cable, and connections.","Clean serviceable parts according to the manual.","Reassemble and test before marking service complete."],cautionsAr:["لا تستخدم منظفات منزلية على أجزاء تلامس ماء الحوض."],cautionsEn:["Do not use household cleaners on parts that contact aquarium water."]}
];

function norm(s:string){
 return (s||"").toLowerCase().normalize("NFKD").replace(/[\u064B-\u065F\u0670]/g,"").replace(/[أإآ]/g,"ا").replace(/ى/g,"ي").replace(/ة/g,"ه").replace(/ؤ/g,"و").replace(/ئ/g,"ي").replace(/[^a-z0-9\u0600-\u06ff]+/g," ").replace(/\s+/g," ").trim();
}

export function matchEquipmentCareGuide(question:string,tank?:Tank){
 const q=norm(question);
 const exact=tank?.equipment
  .map(item=>({item,match:[item.name,item.brand,item.model].filter(Boolean).some(x=>q.includes(norm(String(x))))}))
  .find(x=>x.match)?.item;
 if(exact){
  return {equipment:exact,guide:EQUIPMENT_CARE_GUIDES.find(g=>g.kind===exact.kind)||EQUIPMENT_CARE_GUIDES.find(g=>g.kind==="other")!};
 }
 const scored=EQUIPMENT_CARE_GUIDES.map(guide=>({
  guide,
  score:Math.max(0,...guide.aliases.map(a=>q.includes(norm(a))?norm(a).length:0))
 })).sort((a,b)=>b.score-a.score);
 if(scored[0]?.score>1)return {equipment:undefined,guide:scored[0].guide};
 return undefined;
}
