import type { EquipmentKind,Tank } from "./types";
import { equipmentReliability } from "./equipmentLifecycle";

export type EquipmentAdequacyLevel="good"|"info"|"warn"|"danger";
export type EquipmentSystemProfile="marine-fish"|"marine-reef"|"freshwater"|"freshwater-planted";

export interface EquipmentAdequacyIssue{
  id:string;
  level:EquipmentAdequacyLevel;
  kind?:EquipmentKind;
  ar:string;
  en:string;
  recommendationAr?:string;
  recommendationEn?:string;
}

export interface EquipmentHeadroom {key:string;valuePct:number;level:EquipmentAdequacyLevel;ar:string;en:string;}
export interface EquipmentAdequacyResult{score:number;level:EquipmentAdequacyLevel;issues:EquipmentAdequacyIssue[];suggestions:EquipmentAdequacyIssue[];sizingCoverage:number;checked:number;presenceScore:number;capacityScore:number;statusScore:number;dataConfidence:number;reliabilityScore:number;lifecycleScore:number;redundancyScore:number;consumablesScore:number;profile:EquipmentSystemProfile;basisAr:string;basisEn:string;headroom:EquipmentHeadroom[];}
function clamp(n:number){return Math.max(0,Math.min(100,Math.round(n)));}
function levelFromScore(score:number):EquipmentAdequacyLevel{return score<50?"danger":score<75?"warn":score<90?"info":"good";}
function active(tank:Tank,kind:EquipmentKind){return tank.equipment.filter(x=>x.kind===kind&&x.status!=="off");}
function has(tank:Tank,kind:EquipmentKind){return active(tank,kind).length>0;}
function loadRatio(tank:Tank){const load=tank.livestock.reduce((s,x)=>s+(x.load??1)*x.quantity,0);const capacity=Math.max(1,tank.systemVolumeLiters/35);return load/capacity;}
function allKnownLivestock(tank:Tank){const current=tank.livestock;const acclimation=(tank.acclimationSessions??[]).flatMap(s=>s.items).filter(x=>x.status!=="deferred");return [...current,...acclimation];}
export function inferEquipmentProfile(tank:Tank):EquipmentSystemProfile{if(tank.ecosystemProfile==="reef")return "marine-reef";if(tank.ecosystemProfile==="planted")return "freshwater-planted";if(tank.ecosystemProfile==="fishOnly")return tank.type==="marine"?"marine-fish":"freshwater";if(tank.ecosystemProfile==="mixed")return tank.type==="marine"?"marine-reef":"freshwater-planted";const livestock=allKnownLivestock(tank);const name=(tank.name||"").toLowerCase();const coral=livestock.some(x=>x.category==="coral")||/reef|مرجان|ريف/.test(name);const plant=livestock.some(x=>x.category==="plant")||/planted|مزروع|نبات/.test(name);if(tank.type==="marine")return coral?"marine-reef":"marine-fish";return plant?"freshwater-planted":"freshwater";}

export function equipmentAdequacy(tank:Tank):EquipmentAdequacyResult{
 const issues:EquipmentAdequacyIssue[]=[];const suggestions:EquipmentAdequacyIssue[]=[];const headroom:EquipmentHeadroom[]=[];const profile=inferEquipmentProfile(tank);const volume=Math.max(1,tank.systemVolumeLiters);const bio=loadRatio(tank);const sump=Boolean(tank.sump?.enabled);let presenceScore=100,statusScore=100;const capacityScores:number[]=[];let expectedSizing=0,knownSizing=0,checked=0;
 const issue=(x:EquipmentAdequacyIssue,penalty=0)=>{if(!issues.some(i=>i.id===x.id)){issues.push(x);presenceScore-=penalty;}};const suggest=(x:EquipmentAdequacyIssue)=>{if(!suggestions.some(i=>i.id===x.id))suggestions.push(x);};const capacity=(score:number,known:boolean)=>{capacityScores.push(clamp(score));expectedSizing++;if(known)knownSizing++;checked++;};
 if(sump&&!has(tank,"returnPump"))issue({id:"missing-return",kind:"returnPump",level:"danger",ar:"السامب مفعّل لكن ما في مضخة رجوع فعّالة مسجلة.",en:"The sump is enabled but no active return pump is registered.",recommendationAr:"أضف مضخة رجوع وسجّل Flow L/h حتى ينحسب التدفق الفعلي مقابل حجم النظام.",recommendationEn:"Add a return pump and record Flow L/h so real turnover can be compared with system volume."},28);
 if(sump&&!has(tank,"overflow"))issue({id:"missing-overflow",kind:"overflow",level:"danger",ar:"السامب مفعّل لكن ما في Overflow/مسار نزول مسجل.",en:"The sump is enabled but no overflow/drain path is registered.",recommendationAr:"سجل/أضف مسار Overflow مناسب لأن استمرارية الصرف جزء من سلامة النظام.",recommendationEn:"Register/add an appropriate overflow because safe drainage is part of system reliability."},22);
 if(profile==="marine-reef"&&!has(tank,"lighting"))issue({id:"missing-light",kind:"lighting",level:"danger",ar:"هذا الحوض مصنف Reef لكن ما في إضاءة فعّالة مسجلة.",en:"This tank is classified as Reef but no active aquarium lighting is registered.",recommendationAr:"أضف إضاءة Reef مناسبة وسجّل PAR أو مساحة التغطية.",recommendationEn:"Add reef-capable lighting and record PAR or coverage."},30);
 if(profile==="freshwater-planted"&&!has(tank,"lighting"))issue({id:"missing-light",kind:"lighting",level:"danger",ar:"هذا الحوض مصنف Planted لكن ما في إضاءة فعّالة مسجلة.",en:"This tank is classified as Planted but no active aquarium lighting is registered.",recommendationAr:"أضف إضاءة مناسبة للنباتات وسجّل PAR أو مساحة التغطية.",recommendationEn:"Add plant-suitable lighting and record PAR or coverage."},30);
 if(tank.type==="freshwater"&&!has(tank,"canisterFilter")&&!has(tank,"spongeFilter")&&!has(tank,"filterSock")&&!has(tank,"rollerFilter"))issue({id:"missing-freshwater-filtration",level:"danger",ar:"لا توجد وسيلة فلترة فعّالة مسجلة للحوض العذب.",en:"No active filtration device is registered for this freshwater tank.",recommendationAr:"سجل Canister Filter أو Sponge Filter أو وسيلة الفلترة الفعلية قبل اعتبار التجهيزات الأساسية مكتملة.",recommendationEn:"Register the actual Canister Filter, Sponge Filter, or other active filtration before considering essentials complete."},35);
 if(profile==="freshwater-planted"){const co2=active(tank,"co2");if(!co2.length)suggest({id:"co2-mode",kind:"co2",level:"info",ar:"ما في منظومة CO₂ مسجلة. هذا طبيعي إذا الحوض Low-tech؛ لا يعتبر CO₂ إلزامياً لكل حوض مزروع.",en:"No CO₂ system is registered. That is normal for a low-tech planted tank; injected CO₂ is not mandatory for every planted aquarium."});for(const e of co2){if(e.co2CylinderRemainingPercent!==undefined&&e.co2CylinderRemainingPercent<=15)suggest({id:`co2-low-${e.id}`,kind:"co2",level:e.co2CylinderRemainingPercent<=5?"warn":"info",ar:`${e.name}: الأسطوانة المتبقية تقريباً ${e.co2CylinderRemainingPercent}%.`,en:`${e.name}: cylinder remaining is about ${e.co2CylinderRemainingPercent}%.`});if(e.co2DropChecker==="yellow")issue({id:`co2-yellow-${e.id}`,kind:"co2",level:"danger",ar:`${e.name}: Drop checker مسجل أصفر؛ هذا قد يشير إلى CO₂ مرتفع ويحتاج تحقق فوري.`,en:`${e.name}: drop checker is recorded yellow; this can indicate excessive CO₂ and needs immediate verification.`});}}
 if(profile==="marine-reef"&&!has(tank,"waveMaker"))issue({id:"missing-wave",kind:"waveMaker",level:"danger",ar:"حوض Reef بدون Wave Maker فعّال.",en:"A Reef tank has no active wave maker."},24);
 if(profile==="marine-fish"&&!has(tank,"waveMaker")&&!has(tank,"returnPump"))issue({id:"missing-flow",kind:"waveMaker",level:"danger",ar:"ما في مصدر حركة ماء فعّال مسجل للحوض البحري.",en:"No active water-movement source is registered for this marine tank."},24);
 if(!has(tank,"heater")){const p=tank.type==="marine"?12:8;issue({id:"missing-heater",kind:"heater",level:"warn",ar:"ما في سخان فعّال مسجل؛ ما بقدر اعتبر منظومة الحرارة مكتملة.",en:"No active heater is registered, so temperature control cannot be considered complete."},p);}
 if(tank.type==="marine"&&!has(tank,"ato"))suggest({id:"missing-ato",kind:"ato",level:"info",ar:"ما في ATO مسجل؛ ثبات الملوحة يعتمد على التعويض اليدوي.",en:"No ATO is registered; salinity stability depends on manual top-off."});
 if(tank.type==="marine"&&(bio>.45||volume>=150)&&!has(tank,"skimmer"))issue({id:"missing-skimmer",kind:"skimmer",level:"warn",ar:"حجم/حمل الحوض يستفيد من Skimmer لكن ما في واحد فعّال مسجل.",en:"This tank size/bioload would benefit from a skimmer, but none is active."},10);
 for(const e of tank.equipment){if(e.status==="warning"||e.status==="service"){const critical=["returnPump","heater","overflow"].includes(e.kind);statusScore-=critical?24:10;issue({id:`status-${e.id}`,kind:e.kind,level:critical?"danger":"warn",ar:`${e.name}: الحالة ${e.status==="warning"?"تحذير":"صيانة"}.`,en:`${e.name}: status is ${e.status}.`});}if(e.status==="off"&&["returnPump","heater","overflow","lighting","waveMaker"].includes(e.kind)){statusScore-=20;issue({id:`off-${e.id}`,kind:e.kind,level:"danger",ar:`${e.name} مسجل Off وتأثيره يدخل مباشرة بكفاية النظام.`,en:`${e.name} is marked Off and directly reduces system adequacy.`});}}
 if(sump){const list=active(tank,"returnPump"),flow=list.reduce((s,x)=>s+Number(x.flowLph||0),0);if(!list.length)capacity(0,false);else if(flow<=0){capacity(55,false);suggest({id:"return-flow-missing",kind:"returnPump",level:"warn",ar:"مضخة الرجوع موجودة لكن Flow L/h غير مسجل.",en:"A return pump exists but Flow L/h is missing."});}else{const target=volume*5;capacity(Math.min(100,flow/target*100),true);}}
 if(tank.type==="freshwater"){const filters=[...active(tank,"canisterFilter"),...active(tank,"spongeFilter")];if(filters.length){const flow=filters.reduce((s,x)=>s+Number(x.flowLph||0),0);if(flow>0){const target=volume*4;capacity(Math.min(100,flow/target*100),true);}else{capacity(55,false);suggest({id:"freshwater-filter-flow-missing",level:"warn",ar:"الفلتر موجود لكن Flow L/h غير مسجل.",en:"Freshwater filtration exists but Flow L/h is missing."});}}}
 if(profile==="marine-reef"){const waves=active(tank,"waveMaker");if(waves.length){const flow=waves.reduce((s,x)=>s+Number(x.flowLph||0),0);if(flow>0){const target=volume*20;capacity(Math.min(100,flow/target*100),true);}else capacity(55,false);}}
 if(profile==="marine-reef"||profile==="freshwater-planted"){const lights=active(tank,"lighting");if(lights.length){const par=Math.max(...lights.map(x=>Number(x.parAtTargetDepth||0)));const covL=Math.max(...lights.map(x=>Number(x.coverageLengthCm||0)));const covW=Math.max(...lights.map(x=>Number(x.coverageWidthCm||0)));const hasData=par>0||(covL>0&&covW>0);if(!hasData){capacity(50,false);suggest({id:"light-sizing-missing",kind:"lighting",level:"warn",ar:"الإنارة موجودة لكن ما في PAR أو Coverage.",en:"Lighting exists but PAR or coverage is missing."});}else{knownSizing++;expectedSizing++;checked++;let s=100;if(par>0){const min=profile==="marine-reef"?60:30;const hp=Math.round((par/min-1)*100);headroom.push({key:"lighting-par",valuePct:hp,level:hp<0?"warn":"good",ar:`هامش PAR المسجل ${hp>=0?"+":""}${hp}% مقارنة بالحد المرجعي الأولي ${min}.`,en:`Recorded PAR headroom is ${hp>=0?"+":""}${hp}% versus the initial reference of ${min}.`});if(par<min*.6)s=Math.min(s,35);else if(par<min)s=Math.min(s,70);}if(covL>0&&covW>0){const lr=covL/Math.max(1,tank.display.length),wr=covW/Math.max(1,tank.display.width),r=Math.min(lr,wr);if(r<.6)s=Math.min(s,40);else if(r<.85)s=Math.min(s,70);}capacityScores.push(s);}}
 }
 const reliability=equipmentReliability(tank);
 // Reliability exposes scores and source equipment lists. Adequacy owns user-facing issues/suggestions.
 for(const e of reliability.replaceSoon)issue({id:`lifecycle-replace-${e.id}`,kind:e.kind,level:"danger",ar:`${e.name}: العمر/الأعطال تشير إلى ضرورة مراجعة الاستبدال.`,en:`${e.name}: lifecycle/failure history indicates replacement should be reviewed.`,recommendationAr:"راجع سجل الأعطال والعمر وخطة الاستبدال قبل الاعتماد على الجهاز كنقطة حرجة.",recommendationEn:"Review failure history, age and replacement plan before relying on this device for a critical function."});
 for(const e of reliability.review)issue({id:`lifecycle-review-${e.id}`,kind:e.kind,level:"warn",ar:`${e.name}: الجهاز دخل مرحلة تحتاج مراجعة عمره واعتماديته.`,en:`${e.name}: the device has entered a lifecycle/reliability review stage.`});
 for(const e of reliability.withoutBackup)suggest({id:`backup-${e.id}`,kind:e.kind,level:"warn",ar:`${e.name}: جهاز حرج بدون بديل/احتياط مسجل.`,en:`${e.name}: critical equipment has no registered spare/backup.`,recommendationAr:"سجل Spare أو خطة Backup عملية؛ هذا يؤثر على الاعتمادية لكنه لا يمنع تسجيل الكائنات الموجودة فعلياً.",recommendationEn:"Register a practical spare or backup plan; this affects reliability but should not block recording livestock that already exists."});
 const capacityScore=capacityScores.length?clamp(capacityScores.reduce((a,b)=>a+b,0)/capacityScores.length):70;const dataConfidence=expectedSizing?clamp(knownSizing/expectedSizing*100):0;const sizingCoverage=dataConfidence;presenceScore=clamp(presenceScore);statusScore=clamp(statusScore);let score=clamp(presenceScore*.30+capacityScore*.30+statusScore*.15+reliability.score*.25);if(dataConfidence<50)score=Math.min(score,86);if(dataConfidence===0&&capacityScores.length)score=Math.min(score,82);const level=levelFromScore(score);const basisAr=`${Math.round(score)}% = وجود الأساسيات ${presenceScore}% ×30% + القدرة/الحجم ${capacityScore}% ×30% + حالة الأجهزة ${statusScore}% ×15% + الاعتمادية/العمر/الاحتياط ${reliability.score}% ×25%. ثقة بيانات السعة ${dataConfidence}%.`;const basisEn=`${Math.round(score)}% = core presence ${presenceScore}% ×30% + sizing/capacity ${capacityScore}% ×30% + device condition ${statusScore}% ×15% + lifecycle/redundancy readiness ${reliability.score}% ×25%. Capacity-data confidence ${dataConfidence}%.`;
 return {score,level,issues,suggestions,sizingCoverage,checked,presenceScore,capacityScore,statusScore,dataConfidence,reliabilityScore:reliability.score,lifecycleScore:reliability.lifecycleScore,redundancyScore:reliability.redundancyScore,consumablesScore:reliability.consumablesScore,profile,basisAr,basisEn,headroom};
}