import type { Equipment,EquipmentConsumable,EquipmentKind,MaintenanceTask,Tank } from "./types";
import { addLocalCalendarDays,localDateKey } from "./timeSafety";

const DAY=86400000;
const nowDate=()=>localDateKey();
const addDays=(date:string,days:number)=>addLocalCalendarDays(date,days);
const ageDays=(date?:string)=>date?Math.max(0,Math.floor((Date.now()-new Date(date).getTime())/DAY)):0;
type Cadence=MaintenanceTask["cadence"];
interface MaintenanceBlueprint{key:string;ar:string;en:string;days:number;cadence:Cadence;checklist:string[];}
interface LifeDefaults{min:number;max:number;criticality:"critical"|"important"|"normal";tasks:MaintenanceBlueprint[];consumables:Array<Omit<EquipmentConsumable,"id">>;}
const Y=365;
const T=(key:string,ar:string,en:string,days:number,cadence:Cadence,checklist:string[]):MaintenanceBlueprint=>({key,ar,en,days,cadence,checklist});
const C=(name:string,nameEn:string,lifeDays:number,minimumOnHand=1,unit:NonNullable<EquipmentConsumable["unit"]>="pc"):Omit<EquipmentConsumable,"id">=>({name,nameEn,lifeDays,minimumOnHand,quantityOnHand:0,unit});

export const EQUIPMENT_LIFECYCLE:Record<EquipmentKind,LifeDefaults>={
 lighting:{min:5*Y,max:10*Y,criticality:"important",tasks:[T("clean","تنظيف العدسات والغطاء","Clean lenses and cover",30,"monthly",["افصل الكهرباء","نظف الملح والغبار بدون منظفات منزلية","افحص المراوح والحرارة","تأكد من ثبات الجدول"]),T("output","مراجعة شدة وتغطية الإضاءة","Review light output and coverage",182,"semiannual",["راجع PAR إن توفر","راجع مناطق الظل","قارن الشدة مع آخر قياس","سجل أي قناة ضعفت"])],consumables:[]},
 waveMaker:{min:3*Y,max:7*Y,criticality:"important",tasks:[T("clean","تنظيف Wave Maker","Clean wave maker",30,"monthly",["افصل الكهرباء","نظف الـimpeller والمغناطيس","أزل الكلس والطحالب","اختبر الاهتزاز والصوت","أكد اتجاه التدفق"])],consumables:[]},
 skimmer:{min:8*Y,max:15*Y,criticality:"important",tasks:[T("cup","تنظيف كوب ورقبة السكيمر","Clean skimmer cup and neck",7,"weekly",["افرغ الكوب","نظف الرقبة","اشطف جيداً","راجع مستوى الرغوة"]),T("air","فحص Venturi ومدخل الهواء","Inspect skimmer venturi and air path",30,"monthly",["افحص خرطوم الهواء","أزل الملح من venturi","تأكد من سحب الهواء"]),T("pump","تنظيف مضخة السكيمر","Service skimmer pump",90,"quarterly",["افصل الكهرباء","فك المضخة حسب الدليل","نظف impeller والحجرة","افحص البوش/المحور","اختبر التشغيل بعد التركيب"])],consumables:[]},
 returnPump:{min:4*Y,max:10*Y,criticality:"critical",tasks:[T("flow","فحص تدفق مضخة الرجوع","Check return-pump flow",30,"monthly",["راجع التدفق الفعلي","افحص الصوت والاهتزاز","افحص التسريب","تأكد من عدم سحب هواء"]),T("deep","تنظيف مضخة الرجوع والـImpeller","Deep-clean return pump and impeller",90,"quarterly",["افصل الكهرباء وأغلق الصمامات","نظف impeller والحجرة","افحص O-rings","أعد فتح الصمامات","اختبر التدفق والتسريب"])],consumables:[]},
 filterSock:{min:180,max:540,criticality:"normal",tasks:[T("wash","تبديل/غسيل Filter Sock","Change / wash filter sock",3,"weekly",["أخرج الجراب بدون نشر الرواسب","ركب جراب نظيف","اغسل المتسخ","جففه بالكامل"])],consumables:[C("Filter Sock احتياطي","Spare filter sock",365,2)]},
 rollerFilter:{min:3*Y,max:7*Y,criticality:"important",tasks:[T("sensor","فحص حساس ومسار الرول","Inspect roller sensor and path",7,"weekly",["نظف حساس المستوى","افحص حركة الرول","افحص المحرك","تأكد من عدم انحراف القماش"])],consumables:[C("Roller fleece","Roller fleece",30,1)]},
 canisterFilter:{min:4*Y,max:10*Y,criticality:"critical",tasks:[T("flow","فحص تدفق فلتر الكانستر والتسريب","Inspect canister flow and leaks",30,"monthly",["راجع التدفق","افحص الخراطيم والوصلات","افحص O-ring والتسريب","تأكد من عدم وجود هواء محبوس"]),T("media","صيانة ميديا فلتر الكانستر","Service canister filter media",30,"monthly",["افصل الكهرباء وأغلق الصمامات","نظف الميديا الميكانيكية","حافظ على الميديا البيولوجية رطبة","لا تستبدل كل الميديا البيولوجية دفعة واحدة","أعد التشغيل وافحص التسريب"])],consumables:[C("Canister mechanical media","Canister mechanical media",90,1)]},
 spongeFilter:{min:2*Y,max:6*Y,criticality:"important",tasks:[T("clean","تنظيف الفلتر الإسفنجي","Clean sponge filter",14,"weekly",["استخدم ماء مأخوذ من الحوض","اعصر الإسفنجة بلطف","لا تستخدم ماء ساخناً أو منظفات","افحص تدفق الهواء أو المضخة","أعد التركيب وتأكد من التدفق"])],consumables:[C("Sponge filter foam","Sponge filter foam",730,1)]},
 reactor:{min:8*Y,max:15*Y,criticality:"normal",tasks:[T("flow","فحص تدفق وميديا الرياكتر","Check reactor flow and media",30,"monthly",["راجع التدفق","افحص تكتل الميديا","افحص O-ring والتسريب","بدل الميديا عند الحاجة"])],consumables:[C("Media refill","Media refill",45,250,"g")]},
 heater:{min:2*Y,max:5*Y,criticality:"critical",tasks:[T("verify","فحص السخان ومقارنة الحرارة","Inspect heater and verify temperature",30,"monthly",["قارن الحرارة بمرجع مستقل","افحص الغلاف والكابل","تأكد من عدم وجود تكاثف/صدأ","راجع عمل الكنترولر"]),T("safety","مراجعة أمان السخان","Heater safety review",90,"quarterly",["اختبر فصل الكنترولر","افحص تثبيت السخان","راجع سجل الحرارة","قرر إن كان يلزم استبدال وقائي"])],consumables:[]},
 doser:{min:4*Y,max:8*Y,criticality:"important",tasks:[T("calibrate","معايرة الدوزر","Calibrate dosing pump",90,"quarterly",["اختبر جرعة في مخبار","قارن الفعلي بالمبرمج","افحص الأنابيب","نظف مخارج الجرعات","حدث المعايرة"])],consumables:[C("Dosing tubing","Dosing tubing",365,1)]},
 uv:{min:5*Y,max:10*Y,criticality:"normal",tasks:[T("sleeve","تنظيف Quartz Sleeve للـUV","Clean UV quartz sleeve",90,"quarterly",["افصل الكهرباء والماء","دع الوحدة تبرد","نظف quartz sleeve","افحص O-rings","اختبر التسريب قبل تشغيل UV"])],consumables:[C("UV-C lamp","UV-C lamp",300,1),C("UV O-ring","UV O-ring",730,1)]},
 ozone:{min:3*Y,max:7*Y,criticality:"normal",tasks:[T("check","فحص مولد الأوزون ومسار الهواء","Inspect ozone generator and air path",30,"monthly",["افحص الرائحة والتسريب","راجع مجفف الهواء","افحص الكربون على المخارج","راجع ORP والتحكم"])],consumables:[C("Air dryer media","Air dryer media",60,250,"g"),C("Activated carbon","Activated carbon",30,250,"g")]},
 ato:{min:4*Y,max:8*Y,criticality:"important",tasks:[T("test","اختبار حساس ومضخة ATO","Test ATO sensor and pump",7,"weekly",["اختبر توقف المضخة","نظف الحساس/العوامة","افحص السيفون العكسي","اختبر حماية التشغيل الطويل"])],consumables:[]},
 refugiumLight:{min:4*Y,max:8*Y,criticality:"normal",tasks:[T("clean","تنظيف وفحص إضاءة الرفيوجيوم","Clean and inspect refugium light",30,"monthly",["نظف العدسة","راجع الحرارة","راقب نمو الماكرو ألجي","راجع الجدول"])],consumables:[]},
 turfScrubber:{min:8*Y,max:15*Y,criticality:"normal",tasks:[T("harvest","حصاد وتنظيف Turf Scrubber","Harvest and inspect turf scrubber",14,"weekly",["احصد تدريجياً","نظف مسار الماء","افحص المضخة","راجع توزيع الإضاءة"])],consumables:[]},
 probe:{min:Y,max:3*Y,criticality:"important",tasks:[T("calibrate","تنظيف ومعايرة المجس","Clean and calibrate probe",30,"monthly",["اشطف المجس","نظفه حسب نوعه","عاير بمحاليل صالحة","قارن بمرجع مستقل","سجل النتيجة"])],consumables:[C("Calibration solution","Calibration solution",180,100,"mL")]},
 co2:{min:5*Y,max:12*Y,criticality:"important",tasks:[T("leak","فحص تسريب وضغط منظومة CO₂","Inspect CO₂ pressure and leaks",30,"monthly",["افحص ضغط الأسطوانة","اختبر الوصلات للتسريب","افحص المنظم والـsolenoid","راجع الـbubble counter والـdiffuser","أكد توقيت CO₂ مع الإضاءة"]),T("diffuser","تنظيف وفحص CO₂ diffuser","Clean and inspect CO₂ diffuser",30,"monthly",["أوقف CO₂ بأمان","نظف الـdiffuser حسب تعليمات الشركة","افحص انسداد المسام","أعد التشغيل وراقب الانتشار"])],consumables:[C("CO₂ cylinder/refill","CO₂ cylinder/refill",180,1),C("CO₂ tubing","CO₂ tubing",730,1,"m")]},
 overflow:{min:10*Y,max:20*Y,criticality:"critical",tasks:[T("inspect","فحص Overflow ومسار الصرف","Inspect overflow and drain path",30,"monthly",["افحص الأسنان/الشبك","تأكد من عدم وجود انسداد","راجع الصوت ومستوى الماء","افحص التسريب"]),T("poweroff","اختبار انقطاع الكهرباء والرجوع","Power-off and backflow test",182,"semiannual",["افصل مضخة الرجوع","راقب مستوى السامب","تأكد من توقف السيفون بأمان","أعد التشغيل وتأكد من استقرار الصرف"])],consumables:[]},
 other:{min:3*Y,max:8*Y,criticality:"normal",tasks:[T("inspect","فحص وصيانة الجهاز","Inspect and service equipment",90,"quarterly",["افصل الكهرباء إن لزم","افحص الاتساخ والتسريب","نظف حسب دليل الشركة","اختبر التشغيل"])],consumables:[]}
};

export function equipmentDefaults(kind:EquipmentKind){return EQUIPMENT_LIFECYCLE[kind]??EQUIPMENT_LIFECYCLE.other;}
export function createDefaultConsumables(kind:EquipmentKind):EquipmentConsumable[]{return equipmentDefaults(kind).consumables.map((x,i)=>({...x,id:`cons-${kind}-${i}`,installedAt:nowDate()}));}
export function hydrateEquipment(e:Equipment):Equipment{const d=equipmentDefaults(e.kind);return {...e,expectedLifeMinDays:e.expectedLifeMinDays??d.min,expectedLifeMaxDays:e.expectedLifeMaxDays??d.max,criticality:e.criticality??d.criticality,spareAvailable:e.spareAvailable??false,failures:e.failures??[],consumables:e.consumables??createDefaultConsumables(e.kind)};}
export function equipmentLife(e:Equipment){const h=hydrateEquipment(e),age=ageDays(h.installedAt),min=h.expectedLifeMinDays||1,max=Math.max(min,h.expectedLifeMaxDays||min);const midpoint=(min+max)/2;const used=Math.max(0,age/midpoint*100);const failures=(h.failures??[]).length;const status=age>=max||failures>=4?"replace":age>=min||failures>=2?"review":used>=75?"watch":"good";return {ageDays:age,minDays:min,maxDays:max,usedPercent:Math.round(used),status,failures};}
export function autoMaintenanceTasks(equipment:Equipment[]):MaintenanceTask[]{return equipment.flatMap(raw=>{const e=hydrateEquipment(raw),d=equipmentDefaults(e.kind),base=e.lastServiceAt||e.installedAt||nowDate();return d.tasks.map(bp=>({id:`eqm:${e.id}:${bp.key}`,title:bp.ar,titleEn:bp.en,cadence:bp.cadence,done:false,nextDue:addDays(base,bp.days),lastDone:e.lastServiceAt,sourceEquipmentId:e.id,sourceEquipmentName:e.name,autoGenerated:true,intervalDays:bp.days,checklist:bp.checklist,checklistDone:[]}));});}
export function syncEquipmentSystem(tank:Tank):Pick<Tank,"equipment"|"maintenance">{const equipment=tank.equipment.map(hydrateEquipment);const auto=autoMaintenanceTasks(equipment);const manual=tank.maintenance.filter(x=>!x.autoGenerated);const existing=new Map(tank.maintenance.filter(x=>x.autoGenerated).map(x=>[x.id,x]));const merged=auto.map(x=>{const old=existing.get(x.id);return old?{...x,done:old.done,lastDone:old.lastDone,nextDue:old.nextDue,checklistDone:old.checklistDone??[]}:x;});return {equipment,maintenance:[...manual,...merged]};}
export function equipmentReliability(tank:Tank){const hydrated=tank.equipment.map(hydrateEquipment);const critical=hydrated.filter(x=>x.criticality==="critical");const withoutBackup=critical.filter(x=>!x.spareAvailable);const replaceSoon=hydrated.filter(x=>equipmentLife(x).status==="replace");const review=hydrated.filter(x=>equipmentLife(x).status==="review");const score=Math.max(0,100-withoutBackup.length*12-replaceSoon.length*20-review.length*8);return {score,criticalCount:critical.length,withoutBackup,replaceSoon,review};}