import type { Equipment, EquipmentKind, Tank } from "./types";

export interface EquipmentProfile {
  titleAr:string;
  titleEn:string;
  howAr:string;
  howEn:string;
  lifespanAr:string;
  lifespanEn:string;
  tipsAr:string[];
  tipsEn:string[];
  issuesAr:string[];
  issuesEn:string[];
}

const P=(x:EquipmentProfile)=>x;

export const EQUIPMENT_PROFILES:Record<EquipmentKind,EquipmentProfile>={
  lighting:P({titleAr:"الإضاءة",titleEn:"Lighting",howAr:"توفر الطاقة الضوئية اللازمة للتمثيل الضوئي وتحدد شدة وطيف الإضاءة وفترة النهار داخل الحوض.",howEn:"Provides the light energy used for photosynthesis and sets intensity, spectrum and photoperiod.",lifespanAr:"الوحدة عادة 5–10 سنوات؛ شدة LED قد تتراجع تدريجياً قبل تعطل الوحدة.",lifespanEn:"Fixture typically 5–10 years; LED output may slowly decline before total failure.",tipsAr:["ثبت جدول الإضاءة ولا تغيّر الشدة بسرعة.","نظف الغطاء والعدسات من الملح والرطوبة.","استخدم PAR فعلي عند تربية كائنات حساسة إذا توفر."],tipsEn:["Keep a stable photoperiod and avoid sudden intensity changes.","Clean lenses and covers from salt and moisture.","Use a real PAR meter for sensitive livestock when available."],issuesAr:["تراكم الملح على العدسات.","تراجع شدة LED أو تعطل قناة لونية.","ارتفاع حرارة الوحدة أو المروحة."],issuesEn:["Salt buildup on lenses.","LED output decline or failed color channel.","Fixture or fan overheating."]}),
  waveMaker:P({titleAr:"صانع الأمواج",titleEn:"Wave Maker",howAr:"يحرك الماء داخل الحوض ويمنع المناطق الراكدة ويوصل الأكسجين والغذاء للكائنات.",howEn:"Moves water through the display, reducing dead zones and transporting oxygen and food.",lifespanAr:"تقريباً 3–7 سنوات حسب التنظيف ونوعية المحرك.",lifespanEn:"Roughly 3–7 years depending on maintenance and motor quality.",tipsAr:["نظف المروحة والمغناطيس دورياً من الكلس والطحالب.","راقب الاهتزاز والصوت لأنها علامة مبكرة على تآكل البوش أو المحور.","وجه التدفق لتجنب ضرب المرجان مباشرة."],tipsEn:["Clean impeller and magnet from calcium and algae.","Watch vibration/noise as early signs of wear.","Avoid blasting corals with direct flow."],issuesAr:["تراكم كلسي يضعف التدفق.","اهتزاز أو صوت مرتفع.","توقف المروحة بسبب رمل أو جسم غريب."],issuesEn:["Calcium buildup reducing flow.","Noise or vibration.","Impeller jams from sand or debris."]}),
  skimmer:P({titleAr:"السكيمر",titleEn:"Protein Skimmer",howAr:"يمزج الهواء بالماء لتكوين رغوة تلتقط المركبات العضوية قبل تحللها إلى مغذيات.",howEn:"Mixes air and water to create foam that removes dissolved organics before they break down.",lifespanAr:"الجسم 8–15 سنة؛ المضخة عادة 3–7 سنوات.",lifespanEn:"Body 8–15 years; pump commonly 3–7 years.",tipsAr:["حافظ على مستوى ماء ثابت.","نظف رقبة الكوب ومدخل الهواء.","لا تعدل الإعدادات باستمرار بعد كل تغذية."],tipsEn:["Keep water level stable.","Clean neck and air intake.","Avoid constant tuning after every feeding."],issuesAr:["انسداد venturi بالملح.","توقف الرغوة بسبب مواد زيتية أو إضافات.","فيضان الكوب بسبب تغير مستوى الماء."],issuesEn:["Salt-clogged venturi.","Foam collapse after oily additives.","Cup overflow from water-level changes."]}),
  returnPump:P({titleAr:"مضخة الرجوع",titleEn:"Return Pump",howAr:"تعيد الماء من السامب إلى الحوض وتحدد معدل تدوير الماء بين أجزاء النظام.",howEn:"Returns water from the sump to the display and sets system turnover.",lifespanAr:"تقريباً 4–10 سنوات مع تنظيف دوري.",lifespanEn:"About 4–10 years with regular maintenance.",tipsAr:["نظف الروتور والحجرة الداخلية.","لا تشغل المضخة جافة.","راقب انخفاض التدفق لأنه قد يعني انسداداً أو ترسبات."],tipsEn:["Clean rotor and pump chamber.","Never run dry.","Watch for flow loss indicating clogging or buildup."],issuesAr:["ترسبات كلسية.","تآكل الروتور أو البوش.","Cavitation أو سحب هواء."],issuesEn:["Calcium deposits.","Rotor/bushing wear.","Cavitation or air intake."]}),
  filterSock:P({titleAr:"فلتر سوك",titleEn:"Filter Sock",howAr:"فلترة ميكانيكية تلتقط الجزيئات قبل دخولها لبقية السامب.",howEn:"Mechanical filtration that captures particles before they enter the rest of the sump.",lifespanAr:"القطعة القماشية تقريباً 6–18 شهراً حسب الغسيل؛ التنظيف عادة كل عدة أيام.",lifespanEn:"Fabric typically 6–18 months depending on washing; cleaning is usually every few days.",tipsAr:["بدله أو اغسله قبل انسداده.","لا تترك المواد العضوية محبوسة لفترات طويلة."],tipsEn:["Replace or wash before clogging.","Do not leave trapped organics for long periods."],issuesAr:["انسداد وارتفاع منسوب الماء.","تحول الفلتر نفسه لمصدر نترات إذا تأخر تنظيفه."],issuesEn:["Clogging and rising water level.","Can become a nutrient source if left dirty."]}),
  rollerFilter:P({titleAr:"رولر فلتر",titleEn:"Roller Filter",howAr:"يسحب رول الفلترة تلقائياً عندما يتسخ الجزء المستخدم ويستبدله بجزء نظيف.",howEn:"Automatically advances filter fleece as the used section clogs.",lifespanAr:"المحرك 3–7 سنوات؛ الرول مادة استهلاكية من أسابيع إلى أشهر.",lifespanEn:"Motor 3–7 years; fleece roll is consumable over weeks to months.",tipsAr:["راقب حساس المستوى ونظفه.","لا تشد الرول أكثر من اللازم."],tipsEn:["Keep level sensor clean.","Avoid overtightening the roll."],issuesAr:["انحشار الرول.","اتساخ حساس المستوى.","تعطل محرك السحب."],issuesEn:["Fleece jam.","Dirty level sensor.","Drive motor failure."]}),
  reactor:P({titleAr:"الرياكتر",titleEn:"Media Reactor",howAr:"يمرر الماء بمعدل مضبوط عبر ميديا كيميائية أو بيولوجية مثل GFO أو الكربون.",howEn:"Pushes controlled flow through chemical or biological media such as GFO or carbon.",lifespanAr:"الجسم 8–15 سنة؛ المضخة 3–7 سنوات.",lifespanEn:"Body 8–15 years; pump 3–7 years.",tipsAr:["اضبط التدفق حسب نوع الميديا.","راقب channeling أو تكتل الميديا.","بدل الميديا حسب الأداء لا الوقت وحده."],tipsEn:["Set flow for the media type.","Watch for channeling or clumping.","Replace media based on performance, not time alone."],issuesAr:["تكتل الميديا.","تسرب عند O-ring.","تدفق زائد يطحن GFO."],issuesEn:["Media clumping.","O-ring leaks.","Excessive flow grinding GFO."]}),
  heater:P({titleAr:"السخان",titleEn:"Heater",howAr:"يرفع حرارة الماء ويعمل عادة عبر ترموستات داخلي أو كنترولر خارجي.",howEn:"Heats aquarium water using an internal thermostat or external controller.",lifespanAr:"تقريباً 2–5 سنوات؛ يفضل اعتباره قطعة حرجة وفحصه باستمرار.",lifespanEn:"Roughly 2–5 years; treat it as a critical component and monitor closely.",tipsAr:["استخدم كنترولر مستقل إن أمكن.","لا تخرجه ساخناً من الماء.","قسّم القدرة على سخانين في الأنظمة الكبيرة لتقليل نقطة الفشل الواحدة."],tipsEn:["Use an independent controller when possible.","Do not remove while hot.","Split heating across two units in larger systems to reduce single-point failure."],issuesAr:["تعليق على وضع التشغيل ورفع الحرارة.","فشل وعدم التسخين.","تشقق الزجاج أو تسرب كهربائي."],issuesEn:["Stuck ON causing overheating.","Failure to heat.","Glass damage or electrical leakage."]}),
  doser:P({titleAr:"الدوزر",titleEn:"Dosing Pump",howAr:"يضخ كميات صغيرة ومحددة من السوائل وفق جدول زمني للحفاظ على ثبات العناصر.",howEn:"Delivers measured liquid doses on a schedule to maintain stable chemistry.",lifespanAr:"الوحدة 4–8 سنوات؛ الأنابيب والرؤوس أجزاء استهلاكية وقد تحتاج تغييراً خلال 6–24 شهراً.",lifespanEn:"Unit 4–8 years; tubing and heads are consumables often replaced within 6–24 months.",tipsAr:["عاير كل قناة دورياً.","ثبت نهاية الخرطوم فوق مستوى الماء لمنع السيفون.","راقب تصلب الأنابيب وانزلاقها."],tipsEn:["Calibrate each channel regularly.","Keep outlet above water level to prevent siphon.","Inspect tubing for hardening or slipping."],issuesAr:["فقدان المعايرة.","سيفون غير مقصود.","انسداد خرطوم أو تآكل رأس المضخة."],issuesEn:["Calibration drift.","Accidental siphon.","Blocked tubing or worn pump head."]}),
  uv:P({titleAr:"UV Sterilizer",titleEn:"UV Sterilizer",howAr:"يمرر الماء قرب مصباح UV-C لتقليل الكائنات العالقة عند جرعة تماس مناسبة.",howEn:"Passes water near a UV-C lamp to reduce suspended organisms when contact dose is adequate.",lifespanAr:"الجهاز 5–10 سنوات؛ لمبة UV غالباً 9–12 شهراً من التشغيل الفعال.",lifespanEn:"Unit 5–10 years; UV lamp commonly around 9–12 months of effective output.",tipsAr:["نظف quartz sleeve من الترسبات.","بدل اللمبة حسب ساعات التشغيل حتى لو ما زالت تضيء.","اضبط التدفق حسب الهدف."],tipsEn:["Clean quartz sleeve.","Replace lamp by operating hours even if it still glows.","Match flow rate to the treatment goal."],issuesAr:["ضعف UV بسبب ترسبات على الكم الزجاجي.","لمبة مضيئة لكن خرج UV-C منخفض.","تسرب من O-ring."],issuesEn:["Reduced UV from dirty quartz.","Lamp still glowing but UV-C output depleted.","O-ring leakage."]}),
  ozone:P({titleAr:"مولد الأوزون",titleEn:"Ozone Generator",howAr:"ينتج O3 لتحسين أكسدة المركبات العضوية وصفاء الماء ويجب استخدامه بتحكم ومراقبة ORP مناسبين.",howEn:"Generates O3 to oxidize organics and improve water clarity; should be controlled and monitored carefully.",lifespanAr:"تقريباً 3–7 سنوات؛ بعض الخلايا أو مواد التجفيف تحتاج صيانة دورية.",lifespanEn:"Roughly 3–7 years; cells and air-drying media may require periodic service.",tipsAr:["استخدم كربون على مخارج الهواء والماء عند الحاجة.","لا تعتمد على الأوزون بدون تحكم ومراقبة مناسبة.","حافظ على هواء جاف إذا كان الجهاز يتطلب ذلك."],tipsEn:["Use carbon on air/water outlets where appropriate.","Do not run uncontrolled ozone.","Keep feed air dry when required by the unit."],issuesAr:["انخفاض الإنتاج بسبب الرطوبة.","رائحة أوزون حول الجهاز.","تدهور خلية التوليد."],issuesEn:["Reduced output from humid air.","Ozone smell around equipment.","Generator cell degradation."]}),
  ato:P({titleAr:"تعويض التبخر ATO",titleEn:"ATO",howAr:"يعوض الماء المتبخر تلقائياً للحفاظ على ثبات مستوى الماء والملوحة.",howEn:"Automatically replaces evaporated freshwater to stabilize level and salinity.",lifespanAr:"وحدة التحكم 4–8 سنوات؛ المضخة الصغيرة 2–5 سنوات والحساس يعتمد على التنظيف.",lifespanEn:"Controller 4–8 years; small pump 2–5 years; sensor life depends heavily on cleanliness.",tipsAr:["استخدم حماية من التشغيل الطويل.","نظف الحساس من الملح والطحالب.","لا تجعل خزان التعويض كبيراً بشكل يسبب كارثة عند التعليق."],tipsEn:["Use maximum-run protection.","Keep sensor clean.","Avoid an oversized reservoir that could flood the system if a sensor sticks."],issuesAr:["حساس عالق يؤدي لزيادة الماء.","فشل المضخة.","انسداد خرطوم التعويض."],issuesEn:["Stuck sensor causing overfill.","Pump failure.","Blocked top-off line."]}),
  refugiumLight:P({titleAr:"إضاءة الرفيوجيوم",titleEn:"Refugium Light",howAr:"توفر ضوءاً للطحالب الكبيرة للمساعدة على استهلاك المغذيات.",howEn:"Provides light for macroalgae to support nutrient uptake.",lifespanAr:"تقريباً 4–8 سنوات للوحدة LED.",lifespanEn:"About 4–8 years for an LED fixture.",tipsAr:["راقب نمو الماكرو ألجي وليس شدة الإضاءة فقط.","نظف العدسة من الرذاذ الملحي.","استخدم جدولاً عكسياً عند الحاجة للمساعدة على ثبات pH."],tipsEn:["Judge by macroalgae growth, not light intensity alone.","Clean salt spray from lens.","Use reverse photoperiod where useful for pH stability."],issuesAr:["احتراق أو تراجع LED.","تراكم ملحي.","نمو ضعيف بسبب طيف أو شدة غير مناسبة."],issuesEn:["LED degradation.","Salt buildup.","Poor macroalgae growth from unsuitable spectrum/intensity."]}),
  turfScrubber:P({titleAr:"Algae Turf Scrubber",titleEn:"Algae Turf Scrubber",howAr:"ينمي طبقة طحالب مقصودة على سطح مضاء لاستهلاك NO3 وPO4 ثم تزال بالحصاد.",howEn:"Grows algae intentionally on a lit surface to export NO3 and PO4 through harvesting.",lifespanAr:"الهيكل 8–15 سنة؛ المضخة/الإضاءة حسب نوعها عادة 3–8 سنوات.",lifespanEn:"Body 8–15 years; pump/light generally 3–8 years depending on type.",tipsAr:["احصد تدريجياً ولا تنظف السطح كله مرة واحدة.","راقب تدفق الماء وتوزيع الضوء."],tipsEn:["Harvest gradually rather than stripping the screen completely.","Monitor flow distribution and lighting."],issuesAr:["انسداد مسار الماء.","نمو غير متجانس.","إزالة مغذيات أكثر من اللازم."],issuesEn:["Water-path blockage.","Uneven growth.","Over-stripping nutrients."]}),
  probe:P({titleAr:"مجس قياس",titleEn:"Probe / Sensor",howAr:"يقيس قيمة مثل pH أو ORP أو الموصلية ويرسلها للكنترولر أو نظام المراقبة.",howEn:"Measures values such as pH, ORP or conductivity and sends them to a controller or monitor.",lifespanAr:"غالباً 1–3 سنوات للمجسات الكهروكيميائية حسب النوع والتخزين والمعايرة.",lifespanEn:"Often 1–3 years for electrochemical probes depending on type, storage and calibration.",tipsAr:["عاير بمحاليل جديدة وموثوقة.","لا تترك المجس يجف إذا كان النوع لا يسمح بذلك.","قارن دورياً بفحص يدوي مستقل."],tipsEn:["Calibrate with fresh trusted solutions.","Do not let probes dry when not designed for it.","Cross-check periodically with an independent test."],issuesAr:["انحراف القراءة.","تلوث أو جفاف المجس.","كابل أو موصل تالف."],issuesEn:["Reading drift.","Probe contamination or drying.","Damaged cable/connector."]}),
  co2:P({titleAr:"نظام CO₂",titleEn:"CO₂ System",howAr:"يحقن ثاني أكسيد الكربون بشكل مضبوط في الأحواض المزروعة عند استخدام نمط الحقن لدعم نمو النباتات مع أولوية سلامة الأسماك.",howEn:"Injects controlled carbon dioxide in planted aquariums when an injected-CO₂ strategy is used, supporting plant growth while fish safety remains the priority.",lifespanAr:"المنظم والصمامات عادة عدة سنوات؛ الأسطوانة قابلة لإعادة التعبئة والـdiffuser والأنابيب تحتاج فحصاً وتنظيفاً دورياً.",lifespanEn:"Regulators and valves commonly last several years; cylinders are refillable while diffusers and tubing need periodic inspection and cleaning.",tipsAr:["راقب الأسماك والتنفس قبل مطاردة نمو أسرع للنبات.","افحص التسريب والضغط والـsolenoid والـdiffuser دورياً.","لا تعوض عدم استقرار CO₂ بزيادة الإضاءة أو السماد بشكل عشوائي."],tipsEn:["Watch fish respiration and behavior before chasing faster plant growth.","Inspect pressure, leaks, solenoid and diffuser regularly.","Do not compensate for unstable CO₂ by blindly increasing light or fertilizer."],issuesAr:["تسريب أو نفاد الأسطوانة.","عدم ثبات الحقن أو انسداد الـdiffuser.","زيادة CO₂ بما يهدد أكسجة وسلامة الأسماك."],issuesEn:["Leaks or depleted cylinder.","Unstable injection or clogged diffuser.","Excess CO₂ compromising fish oxygenation and safety."]}),
  overflow:P({titleAr:"الأوفر فلو والسباكة",titleEn:"Overflow & Plumbing",howAr:"ينقل الماء بالجاذبية من الحوض إلى السامب ويحدد أمان واستقرار مسار الصرف.",howEn:"Moves water by gravity from display to sump and defines drainage safety and stability.",lifespanAr:"السباكة الصلبة 10–20+ سنة؛ الجلود وO-rings تحتاج فحصاً واستبدالاً حسب حالتها.",lifespanEn:"Rigid plumbing often 10–20+ years; seals and O-rings need inspection and replacement as needed.",tipsAr:["اختبر الانقطاع الكهربائي ومستوى رجوع الماء للسامب.","حافظ على مسار طوارئ أو تصريف احتياطي في الأنظمة الحساسة.","نظف الترسبات والقواقع من مدخل الصرف."],tipsEn:["Test power-off backflow and sump capacity.","Keep an emergency/backup drain where appropriate.","Clean deposits and snails from drain intake."],issuesAr:["انسداد جزئي أو كامل.","صوت سحب هواء.","تسريب من الوصلات أو bulkhead."],issuesEn:["Partial/full blockage.","Air-sucking noise.","Leaks at fittings or bulkheads."]}),
  other:P({titleAr:"تجهيزة أخرى",titleEn:"Other Equipment",howAr:"جهاز مخصص يضاف للنظام؛ يجب الرجوع إلى تعليمات الشركة المصنعة لتحديد طريقة عمله وحدود التشغيل.",howEn:"Custom device added to the system; use the manufacturer's guidance for operation and limits.",lifespanAr:"يعتمد على نوع الجهاز والمصنع.",lifespanEn:"Depends on device type and manufacturer.",tipsAr:["سجل الموديل والقدرة وجدول الصيانة.","احتفظ بدليل الجهاز وقطع الاستهلاك الأساسية."],tipsEn:["Record model, power and maintenance schedule.","Keep the manual and key consumables available."],issuesAr:["تختلف حسب الجهاز؛ راقب الحرارة والصوت والتدفق والأخطاء."],issuesEn:["Varies by device; monitor heat, noise, flow and errors."]})
};

export function equipmentProfile(kind:EquipmentKind){return EQUIPMENT_PROFILES[kind]??EQUIPMENT_PROFILES.other;}

export function deviceEnergy(e:Equipment,pricePerKwh:number){
  const watts=Math.max(0,Number(e.powerWatts||0));
  const hours=Math.max(0,Math.min(24,Number(e.hoursPerDay||0)));
  const dailyKwh=watts*hours/1000;
  const monthlyKwh=dailyKwh*30;
  return {dailyKwh,monthlyKwh,monthlyCost:monthlyKwh*Math.max(0,pricePerKwh)};
}

export function tankEnergy(tank:Tank){
  const price=Math.max(0,Number(tank.energySettings?.pricePerKwh||0));
  const rows=tank.equipment.map(e=>({equipment:e,...deviceEnergy(e,price)}));
  return {
    rows,
    dailyKwh:rows.reduce((s,x)=>s+x.dailyKwh,0),
    monthlyKwh:rows.reduce((s,x)=>s+x.monthlyKwh,0),
    monthlyCost:rows.reduce((s,x)=>s+x.monthlyCost,0),
    configured:rows.filter(x=>(x.equipment.powerWatts||0)>0&&(x.equipment.hoursPerDay||0)>0).length
  };
}
