import type { GuidanceAction,IntelligenceEvent,Tank } from "./types";
const iso=()=>new Date().toISOString();
const eid=(d:string,v:string,s?:string)=>`evt-${d}-${v}-${s||Date.now()}`;
export function deriveIntelligenceEvents(before:Tank,after:Tank):IntelligenceEvent[]{
 const out:IntelligenceEvent[]=[];const push=(e:Omit<IntelligenceEvent,"id">)=>out.push({id:eid(e.domain,e.verb,e.sourceId),...e});
 for(const r of after.chemistry.filter(x=>!before.chemistry.some(b=>b.timestamp===x.timestamp)))for(const [parameter,value] of Object.entries(r.values)){if(typeof value==="number")push({timestamp:r.timestamp,kind:"fact",domain:"chemistry",verb:"measured",parameter,value,confidence:r.confidence==="high"?100:r.confidence==="low"?40:70,sourceId:r.timestamp,sourcePage:"chemistry",textAr:`تم قياس ${parameter}: ${value}`,textEn:`${parameter} measured: ${value}`});}
 for(const d of after.dosing.filter(x=>!before.dosing.some(b=>b.id===x.id||b.timestamp===x.timestamp&&b.parameter===x.parameter&&b.ml===x.ml)))push({timestamp:d.timestamp,kind:"action",domain:"dosing",verb:"dose_given",parameter:d.parameter,value:d.ml,unit:"mL",confidence:100,sourceId:d.id||d.timestamp,sourcePage:"dosing",textAr:`تمت جرعة ${d.parameter}: ${d.ml} mL`,textEn:`${d.parameter} dose given: ${d.ml} mL`,metadata:{material:d.material||d.chamberMaterial||null,inventoryItemId:d.inventoryItemId||null,reason:d.reason||null,sourceReadingTimestamp:d.sourceReadingTimestamp||null,verifyAfter:d.verifyAfter||null}});
 for(const w of after.waterChanges.filter(x=>!before.waterChanges.some(b=>b.id===x.id||b.timestamp===x.timestamp)))push({timestamp:w.timestamp,kind:"action",domain:"waterChange",verb:"water_changed",value:w.percent,unit:"%",confidence:100,sourceId:w.id||w.timestamp,sourcePage:"water-change",textAr:`تم تغيير ${w.percent}% من الماء`,textEn:`${w.percent}% water change completed`});
 for(const f of after.feeding.filter(x=>!before.feeding.some(b=>b.id===x.id||b.timestamp===x.timestamp)))push({timestamp:f.timestamp,kind:"action",domain:"feeding",verb:"fed",value:f.amount,confidence:100,sourceId:f.id||f.timestamp,sourcePage:"feeding",textAr:`تم تسجيل تغذية: ${f.food}`,textEn:`Feeding logged: ${f.food}`});
 for(const r of after.rodi.filter(x=>!before.rodi.some(b=>b.id===x.id||b.timestamp===x.timestamp)))push({timestamp:r.timestamp,kind:"fact",domain:"rodi",verb:"batch_logged",value:r.tdsOut,unit:"TDS",confidence:90,sourceId:r.id||r.timestamp,sourcePage:"rodi",textAr:`تم تسجيل RO/DI، TDS الخارج ${r.tdsOut}`,textEn:`RO/DI logged, output TDS ${r.tdsOut}`});
 const bl=new Map(before.livestock.map(x=>[x.id,x]));for(const x of after.livestock){const old=bl.get(x.id);if(!old)push({timestamp:x.addedAt||iso(),kind:"action",domain:"livestock",verb:"added",entityType:x.category,entityId:x.id,value:x.quantity,confidence:100,sourceId:x.id,sourcePage:"livestock",textAr:`تمت إضافة ${x.name} ×${x.quantity}`,textEn:`${x.nameEn||x.name} ×${x.quantity} added`});else if(old.quantity!==x.quantity||old.health!==x.health)push({timestamp:iso(),kind:"observation",domain:"livestock",verb:"changed",entityType:x.category,entityId:x.id,value:x.health,confidence:90,sourceId:x.id,sourcePage:"livestock",textAr:`تغيرت حالة/كمية ${x.name}`,textEn:`${x.nameEn||x.name} status/quantity changed`});}
 for(const old of before.livestock)if(!after.livestock.some(x=>x.id===old.id))push({timestamp:iso(),kind:"observation",domain:"livestock",verb:"removed",entityType:old.category,entityId:old.id,value:old.quantity,confidence:80,sourceId:old.id,sourcePage:"livestock",textAr:`تمت إزالة ${old.name} من السجل`,textEn:`${old.nameEn||old.name} removed from livestock`});
 for(const x of after.livestockExits??[]){if((before.livestockExits??[]).some(b=>b.id===x.id))continue;push({timestamp:x.timestamp,kind:"observation",domain:"livestock",verb:x.reason==="death"?"death":"exit",entityType:x.category,entityId:x.livestockId,value:x.quantity,confidence:x.reason==="unknown"?60:100,sourceId:x.id,sourcePage:"livestock",textAr:x.reason==="death"?`تم تسجيل وفاة ${x.name} ×${x.quantity}`:`تم تسجيل خروج ${x.name} ×${x.quantity}`,textEn:x.reason==="death"?`${x.nameEn||x.name} ×${x.quantity} death recorded`:`${x.nameEn||x.name} ×${x.quantity} exit recorded`,metadata:{reason:x.reason,bodyRemoved:x.bodyRemoved??null,symptoms:x.symptoms||null,notes:x.notes||null}});}
 const be=new Map(before.equipment.map(x=>[x.id,x]));for(const e of after.equipment){const old=be.get(e.id);if(!old)push({timestamp:e.installedAt||iso(),kind:"action",domain:"equipment",verb:"installed",entityType:e.kind,entityId:e.id,confidence:100,sourceId:e.id,sourcePage:"equipment",textAr:`تم تركيب/إضافة جهاز: ${e.name}`,textEn:`Equipment installed/added: ${e.name}`,metadata:{criticality:e.criticality||null,spareAvailable:e.spareAvailable??null,redundancyGroup:e.redundancyGroup||null}});else {if(old.status!==e.status||old.location!==e.location)push({timestamp:iso(),kind:"observation",domain:"equipment",verb:"changed",entityType:e.kind,entityId:e.id,value:e.status,confidence:100,sourceId:e.id,sourcePage:"equipment",textAr:`تغيرت حالة الجهاز ${e.name}`,textEn:`${e.name} status changed`,metadata:{previousStatus:old.status,criticality:e.criticality||null,spareAvailable:e.spareAvailable??null,redundancyGroup:e.redundancyGroup||null,backupPlan:e.backupPlan||null}});for(const fail of e.failures??[]){const prev=(old.failures??[]).find(x=>x.id===fail.id);if(!prev)push({timestamp:fail.timestamp,kind:"observation",domain:"equipment",verb:"failure",entityType:e.kind,entityId:e.id,confidence:100,sourceId:fail.id,sourcePage:"equipment",textAr:`تم تسجيل عطل على ${e.name}: ${fail.note}`,textEn:`Failure recorded on ${e.name}: ${fail.note}`,metadata:{equipmentName:e.name,note:fail.note,criticality:e.criticality||null,spareAvailable:e.spareAvailable??null,redundancyGroup:e.redundancyGroup||null,backupPlan:e.backupPlan||null}});else if(!prev.resolvedAt&&fail.resolvedAt)push({timestamp:fail.resolvedAt,kind:"outcome",domain:"equipment",verb:"failure_resolved",entityType:e.kind,entityId:e.id,confidence:100,sourceId:fail.id,sourcePage:"equipment",textAr:`تم حل عطل ${e.name}`,textEn:`${e.name} failure resolved`});}}}
 for(const old of before.equipment)if(!after.equipment.some(x=>x.id===old.id))push({timestamp:iso(),kind:"action",domain:"equipment",verb:"removed",entityType:old.kind,entityId:old.id,confidence:100,sourceId:old.id,sourcePage:"equipment",textAr:`تمت إزالة الجهاز ${old.name} من النظام`,textEn:`${old.name} removed from system`,metadata:{criticality:old.criticality||null,spareAvailable:old.spareAvailable??null,redundancyGroup:old.redundancyGroup||null}});
 const bi=new Map(before.inventory.map(x=>[x.id,x]));for(const x of after.inventory){const old=bi.get(x.id);if(!old||old.quantity!==x.quantity)push({timestamp:iso(),kind:old&&x.quantity<old.quantity?"action":"fact",domain:"inventory",verb:!old?"added":x.quantity<old.quantity?"consumed":"adjusted",entityType:"stock",entityId:x.id,value:x.quantity,unit:x.unit,confidence:100,sourceId:x.id,sourcePage:"inventory",textAr:`تغير مخزون ${x.name}: ${x.quantity} ${x.unit}`,textEn:`${x.nameEn||x.name} stock changed: ${x.quantity} ${x.unit}`});}
 const bm=new Map(before.maintenance.map(x=>[x.id,x]));for(const m of after.maintenance){const old=bm.get(m.id);if(!old)push({timestamp:iso(),kind:"fact",domain:"maintenance",verb:"scheduled",entityType:"task",entityId:m.id,confidence:100,sourceId:m.id,sourcePage:"maintenance",textAr:`تمت جدولة صيانة: ${m.title}`,textEn:`Maintenance scheduled: ${m.titleEn||m.title}`,metadata:{dueAt:m.nextDue||null,cadence:m.cadence,sourceEquipmentId:m.sourceEquipmentId||null,autoGenerated:m.autoGenerated??false}});else if(!old.done&&m.done)push({timestamp:m.lastDone?new Date(`${m.lastDone}T12:00:00`).toISOString():iso(),kind:"action",domain:"maintenance",verb:"completed",entityType:"task",entityId:m.id,confidence:100,sourceId:m.id,sourcePage:"maintenance",textAr:`اكتملت الصيانة: ${m.title}`,textEn:`Maintenance completed: ${m.titleEn||m.title}`,metadata:{sourceEquipmentId:m.sourceEquipmentId||null,checklistCount:m.checklist?.length??0,checklistDone:m.checklistDone?.length??0}});}
 for(const q of after.quarantine){const old=before.quarantine.find(x=>x.id===q.id);if(!old||old.status!==q.status||old.dosesGiven!==q.dosesGiven)push({timestamp:iso(),kind:"action",domain:"quarantine",verb:!old?"started":q.status==="closed"?"closed":"updated",entityType:"case",entityId:q.id,confidence:100,sourceId:q.id,sourcePage:"quarantine",textAr:`تغيرت حالة الحجر/العلاج: ${q.organism}`,textEn:`Quarantine/treatment changed: ${q.organism}`});}
 for(const e of after.emergencySessions??[]){const old=(before.emergencySessions??[]).find(x=>x.id===e.id);if(!old||old.status!==e.status||old.completedSteps.length!==e.completedSteps.length)push({timestamp:iso(),kind:"action",domain:"emergency",verb:!old?"started":e.status==="completed"?"completed":"progress",entityType:"protocol",entityId:e.id,confidence:100,sourceId:e.id,sourcePage:"emergency",textAr:`تغير بروتوكول الطوارئ: ${e.titleAr}`,textEn:`Emergency protocol changed: ${e.titleEn}`});}
 for(const a of after.acclimationSessions??[]){const old=(before.acclimationSessions??[]).find(x=>x.id===a.id);if(!old||old.status!==a.status)push({timestamp:iso(),kind:"action",domain:"acclimation",verb:!old?"started":a.status==="completed"?"completed":"progress",entityType:"session",entityId:a.id,confidence:100,sourceId:a.id,sourcePage:"acclimation",textAr:"تغيرت حالة جلسة الإقلمة",textEn:"Acclimation session status changed"});}
 return out;
}
export function mergeIntelligenceEvents(existing:IntelligenceEvent[]=[],incoming:IntelligenceEvent[]){const seen=new Set(existing.map(x=>x.id));return [...incoming.filter(x=>!seen.has(x.id)),...existing].slice(0,1000);}
function latestEvent(events:IntelligenceEvent[],domain:string,parameter?:string,verb?:string){return events.find(e=>e.domain===domain&&(!parameter||e.parameter===parameter)&&(!verb||e.verb===verb));}
export function verifyGuidanceActions(actions:GuidanceAction[],events:IntelligenceEvent[]=[]){
 return actions.map(a=>{
  if(a.status!=="done"&&a.status!=="awaiting_verification")return a;
  if(a.verifyAfter&&Date.now()<new Date(a.verifyAfter).getTime())return {...a,status:"awaiting_verification" as const};
  const ev=a.domain==="chemistry"&&a.parameter?latestEvent(events,"chemistry",a.parameter,"measured"):latestEvent(events,a.domain,a.parameter);
  if(!ev||a.executedAt&&new Date(ev.timestamp).getTime()<=new Date(a.executedAt).getTime())return {...a,status:"awaiting_verification" as const};
  return {...a,status:"verified" as const,verifiedAt:iso(),verificationEventId:ev.id,outcome:"unknown" as const,resolvedReasonAr:"تم تسجيل دليل متابعة بعد تنفيذ الإجراء.",resolvedReasonEn:"Follow-up evidence was recorded after the action."};
 });
}
export function reconcileGuidanceActions(existing:GuidanceAction[]=[],generated:GuidanceAction[],events:IntelligenceEvent[]=[]){
 const byKey=new Map(existing.map(x=>[x.dedupeKey,x])),active=new Set(generated.map(x=>x.dedupeKey)),now=iso();
 const next=generated.map(g=>{const old=byKey.get(g.dedupeKey);return old?{...g,id:old.id,createdAt:old.createdAt,updatedAt:now,status:old.status==="in_progress"?"in_progress":g.status,sourceEventIds:[...new Set([...old.sourceEventIds,...g.sourceEventIds])].slice(-20)}:g;});
 for(const old of existing)if(!active.has(old.dedupeKey)&&old.status!=="resolved"&&old.status!=="verified")next.push({...old,status:old.status==="done"||old.status==="awaiting_verification"?"awaiting_verification":"resolved",updatedAt:now});
 return verifyGuidanceActions(next.slice(0,300),events);
}
