import type { GuidanceAction,IntelligenceEvent,Tank } from "./types";
import { chemistryGuidance } from "./chemistryGuidance";
import { unifiedInventory } from "./inventoryIntelligence";
import { rodiIntelligence } from "./rodiIntelligence";
import { equipmentAdequacy } from "./equipmentAdequacy";
import { bioload } from "./health";
const now=()=>new Date().toISOString(),hours=(n:number)=>new Date(Date.now()+n*3600000).toISOString();
const priority=(level:"info"|"warn"|"danger",confidence:number,weight=1)=>Math.round((level==="danger"?90:level==="warn"?60:30)*weight*(.55+.45*confidence/100));
const make=(x:Omit<GuidanceAction,"id"|"createdAt"|"updatedAt"|"priority"> & {weight?:number}):GuidanceAction=>{const {weight,...rest}=x;return {id:`guide-${x.dedupeKey}`,createdAt:now(),updatedAt:now(),priority:priority(x.level,x.confidence,weight),...rest};};
const eventIds=(tank:Tank,domain:string,parameter?:string)=>(tank.intelligenceEvents??[]).filter(e=>e.domain===domain&&(!parameter||e.parameter===parameter)).slice(0,10).map(e=>e.id);
export function deriveGuidanceActions(tank:Tank):GuidanceAction[]{
 const out:GuidanceAction[]=[],stock=unifiedInventory(tank),guide=chemistryGuidance(tank);
 const resource:Record<string,string|undefined>={KH:"khBuffer",Ca:"calcium",Mg:"magnesium",PO4:"phosphateMedia",salinity:"marineSalt"};
 for(const p of guide.problems){
  const preset=resource[p.key],item=preset?tank.inventory.find(i=>i.presetId===preset):undefined,blocked=Boolean(preset&&(!item||item.quantity<=0));
  const conf=p.confidence==="high"?100:p.confidence==="medium"?70:p.confidence==="low"?40:55,level=p.level==="danger"?"danger" as const:"warn" as const;
  out.push(make({dedupeKey:`chemistry:${p.key}`,sourceEventIds:eventIds(tank,"chemistry",p.key),domain:"chemistry",parameter:p.key,level,confidence:conf,status:blocked?"blocked":"ready",page:blocked?"inventory":"chemistry",titleAr:p.reasonAr,titleEn:p.reasonEn,reasonAr:p.reasonAr,reasonEn:p.reasonEn,resourcePresetId:preset,blockedReasonAr:blocked?"مادة التصحيح غير متوفرة بالمخزون.":undefined,blockedReasonEn:blocked?"Corrective material is not available in inventory.":undefined,verifyAfter:hours(level==="danger"?12:24),weight:level==="danger"?1.1:1}));
 }
 for(const x of stock.low){out.push(make({dedupeKey:`inventory:${x.id}`,sourceEventIds:eventIds(tank,"inventory"),domain:"inventory",entityType:"stock",entityId:x.id,level:x.quantity<=0?"danger":"warn",confidence:100,status:"ready",page:"inventory",titleAr:`تأمين مخزون: ${x.name}`,titleEn:`Restock: ${x.nameEn||x.name}`,reasonAr:`المتوفر ${x.quantity} ${x.unit} والحد الأدنى ${x.minimum}.`,reasonEn:`Available ${x.quantity} ${x.unit}; minimum ${x.minimum}.`}));
 }
 const rodi=rodiIntelligence(tank);if(rodi.status==="danger"||rodi.status==="watch")out.push(make({dedupeKey:"rodi:quality",sourceEventIds:eventIds(tank,"rodi"),domain:"rodi",level:rodi.status==="danger"?"danger":"warn",confidence:90,status:"ready",page:"rodi",titleAr:"راجع جودة ومراحل RO/DI",titleEn:"Review RO/DI quality and stages",reasonAr:rodi.notes.join(" "),reasonEn:"RO/DI output or efficiency needs review.",verifyAfter:hours(24)}));
 const eq=equipmentAdequacy(tank);for(const issue of eq.issues.slice(0,8))out.push(make({dedupeKey:`equipment:${issue.id}`,sourceEventIds:eventIds(tank,"equipment"),domain:"equipment",entityType:"equipment",level:issue.level==="danger"?"danger":"warn",confidence:85,status:"ready",page:"equipment",titleAr:issue.ar,titleEn:issue.en,reasonAr:issue.recommendationAr||issue.ar,reasonEn:issue.recommendationEn||issue.en,verifyAfter:hours(24)}));
 for(const l of tank.livestock.filter(x=>x.health!=="good"))out.push(make({dedupeKey:`livestock:${l.id}:health`,sourceEventIds:eventIds(tank,"livestock"),domain:"livestock",entityType:l.category,entityId:l.id,level:l.health==="treatment"?"danger":"warn",confidence:90,status:"ready",page:l.health==="treatment"?"quarantine":"livestock",titleAr:`راقب حالة ${l.name}`,titleEn:`Monitor ${l.nameEn||l.name}`,reasonAr:l.health==="treatment"?"الكائن مسجل تحت العلاج ويحتاج متابعة الاستجابة.":"الكائن مسجل للمراقبة ويحتاج متابعة حالته.",reasonEn:l.health==="treatment"?"The organism is under treatment and needs response monitoring.":"The organism is on watch and needs follow-up.",verifyAfter:hours(12)}));
 const bio=bioload(tank);if(bio.status==="high"||bio.status==="danger")out.push(make({dedupeKey:"livestock:bioload",sourceEventIds:eventIds(tank,"livestock"),domain:"livestock",level:bio.status==="danger"?"danger":"warn",confidence:80,status:"ready",page:"livestock",titleAr:"راجع الحمل الحيوي قبل أي إضافة جديدة",titleEn:"Review bioload before adding livestock",reasonAr:"الحمل الحيوي الحالي مرتفع بالنسبة لحجم النظام ويؤثر على التغذية والكيمياء والفلترة.",reasonEn:"Current bioload is high for system volume and affects feeding, chemistry and filtration."}));
 const latestDoseByParam=new Map<string,IntelligenceEvent>();for(const e of tank.intelligenceEvents??[]){if(e.domain==="dosing"&&e.verb==="dose_given"&&e.parameter&&!latestDoseByParam.has(e.parameter))latestDoseByParam.set(e.parameter,e);}
 for(const [parameter,e] of latestDoseByParam){const verify=typeof e.metadata?.verifyAfter==="string"?e.metadata.verifyAfter:hours(24);const measuredAfter=(tank.intelligenceEvents??[]).find(x=>x.domain==="chemistry"&&x.parameter===parameter&&x.verb==="measured"&&new Date(x.timestamp).getTime()>new Date(e.timestamp).getTime());if(!measuredAfter)out.push(make({dedupeKey:`dosing:${parameter}:verify`,sourceEventIds:[e.id],domain:"dosing",parameter,level:"warn",confidence:100,status:new Date(verify).getTime()>Date.now()?"suggested":"ready",page:"chemistry",titleAr:`إعادة قياس ${parameter} بعد الجرعة`,titleEn:`Retest ${parameter} after dosing`,reasonAr:"تم تسجيل جرعة ولم تُسجل بعدها قراءة تحقق بعد. لا تكرر التصحيح قبل معرفة الاستجابة.",reasonEn:"A dose was logged without a later verification reading. Do not repeat correction before confirming the response.",dueAt:verify,verifyAfter:verify}));}
 const activeEmergency=(tank.emergencySessions??[]).find(x=>x.status==="active");if(activeEmergency)out.push(make({dedupeKey:`emergency:${activeEmergency.id}`,sourceEventIds:eventIds(tank,"emergency"),domain:"emergency",entityType:"protocol",entityId:activeEmergency.id,level:"danger",confidence:100,status:"ready",page:"emergency",titleAr:activeEmergency.titleAr,titleEn:activeEmergency.titleEn,reasonAr:"بروتوكول طوارئ نشط ويأخذ الأولوية على الإجراءات الروتينية.",reasonEn:"An active emergency protocol takes priority over routine actions.",weight:1.1}));
 const activeQ=tank.quarantine.filter(x=>x.status==="active");for(const q of activeQ)if(q.nextDoseAt&&new Date(q.nextDoseAt).getTime()<Date.now())out.push(make({dedupeKey:`quarantine:${q.id}:dose`,sourceEventIds:eventIds(tank,"quarantine"),domain:"quarantine",entityType:"case",entityId:q.id,level:"warn",confidence:100,status:"ready",page:"quarantine",titleAr:`جرعة علاج مستحقة: ${q.organism}`,titleEn:`Treatment dose due: ${q.organism}`,reasonAr:"موعد الجرعة المسجل أصبح مستحقاً؛ راجع العلاج والملصق قبل التنفيذ.",reasonEn:"The recorded dose is due; verify treatment and product label before dosing."}));
 return out.sort((a,b)=>b.priority-a.priority);
}
