import type { GuidanceAction,IntelligenceEvent,Tank } from "./types";
import { chemistryGuidance } from "./chemistryGuidance";
import { unifiedInventory } from "./inventoryIntelligence";
import { rodiIntelligence } from "./rodiIntelligence";
import { equipmentAdequacy } from "./equipmentAdequacy";
import { bioload } from "./health";
const now=()=>new Date().toISOString(),hours=(n:number)=>new Date(Date.now()+n*3600000).toISOString();
const priority=(level:"info"|"warn"|"danger",confidence:number,weight=1)=>Math.round((level==="danger"?90:level==="warn"?60:30)*weight*(.55+.45*confidence/100));
const make=(x:Omit<GuidanceAction,"id"|"createdAt"|"updatedAt"|"priority"> & {weight?:number}):GuidanceAction=>{const {weight,...rest}=x;return {id:`guide-${x.dedupeKey}`,createdAt:now(),updatedAt:now(),priority:priority(x.level,x.confidence,weight),...rest};};
const eventIds=(tank:Tank,domain:string,parameter?:string)=>(tank.intelligenceEvents??[]).filter(e=>e.domain===domain&&(!parameter||e.parameter===parameter)).slice(0,10).map(e=>e.id);
export function deriveGuidanceActions(tank:Tank):GuidanceAction[]{
 const out:GuidanceAction[]=[],stock=unifiedInventory(tank),guide=chemistryGuidance(tank);
 const resource:Record<string,string|undefined>={KH:"khBuffer",Ca:"calcium",Mg:"magnesium",PO4:"phosphateMedia",salinity:"marineSalt"};
 for(const p of guide.problems){
  const preset=resource[p.key],item=preset?tank.inventory.find(i=>i.presetId===preset):undefined,blocked=Boolean(preset&&(!item||item.quantity<=0));
  const conf=p.confidence==="high"?100:p.confidence==="medium"?70:p.confidence==="low"?40:55,level=p.level==="danger"?"danger" as const:"warn" as const;
  out.push(make({dedupeKey:`chemistry:${p.key}`,sourceEventIds:eventIds(tank,"chemistry",p.key),domain:"chemistry",parameter:p.key,level,confidence:conf,status:blocked?"blocked":"ready",page:blocked?"inventory":"chemistry",titleAr:p.reasonAr,titleEn:p.reasonEn,reasonAr:p.reasonAr,reasonEn:p.reasonEn,resourcePresetId:preset,blockedReasonAr:blocked?"مادة التصحيح غير متوفرة بالمخزون.":undefined,blockedReasonEn:blocked?"Corrective material is not available in inventory.":undefined,verifyAfter:hours(level==="danger"?12:24),weight:level==="danger"?1.1:1}));
 }
 for(const x of stock.low){out.push(make({dedupeKey:`inventory:${x.id}`,sourceEventIds:eventIds(tank,"inventory"),domain:"inventory",entityType:"stock",entityId:x.id,level:x.quantity<=0?"danger":"warn",confidence:100,status:"ready",page:"inventory",titleAr:`تأمين مخزون: ${x.name}`,titleEn:`Restock: ${x.nameEn||x.name}`,reasonAr:`المتوفر ${x.quantity} ${x.unit} والحد الأدنى ${x.minimum}.`,reasonEn:`Available ${x.quantity} ${x.unit}; minimum ${x.minimum}.`}));
 }
 const rodi=rodiIntelligence(tank);if(rodi.status==="danger"||rodi.status==="watch")out.push(make({dedupeKey:"rodi:quality",sourceEventIds:eventIds(tank,"rodi"),domain:"rodi",level:rodi.status==="danger"?"danger":"warn",confidence:90,status:"ready",page:"rodi",titleAr:"راجع جودة ومراحل RO/DI",titleEn:"Review RO/DI quality and stages",reasonAr:rodi.notes.join(" "),reasonEn:"RO/DI output or efficiency needs review.",verifyAfter:hours(24)}));
 const eq=equipmentAdequacy(tank);for(const issue of eq.issues.slice(0,8))out.push(make({dedupeKey:`equipment:${issue.id}`,sourceEventIds:eventIds(tank,"equipment"),domain:"equipment",entityType:"equipment",level:issue.level==="danger"?"danger":"warn",confidence:85,status:"ready",page:"equipment",titleAr:issue.ar,titleEn:issue.en,reasonAr:issue.recommendationAr||issue.ar,reasonEn:issue.recommendationEn||issue.en,verifyAfter:hours(24)}));
 const recentEquipmentRemoval=(tank.intelligenceEvents??[]).find(e=>e.domain==="equipment"&&e.verb==="removed"&&Date.now()-new Date(e.timestamp).getTime()<24*3600000);if(recentEquipmentRemoval){const critical=recentEquipmentRemoval.metadata?.criticality==="critical"||["returnPump","heater","overflow","ato"].includes(recentEquipmentRemoval.entityType||"");if(critical)out.push(make({dedupeKey:`equipment:removed:${recentEquipmentRemoval.sourceId}`,sourceEventIds:[recentEquipmentRemoval.id],domain:"equipment",entityType:recentEquipmentRemoval.entityType,entityId:recentEquipmentRemoval.entityId,level:"danger",confidence:100,status:"ready",page:"equipment",titleAr:"تحقق من تغطية وظيفة الجهاز الذي تمت إزالته",titleEn:"Verify coverage after critical equipment removal",reasonAr:"تمت إزالة جهاز مهم من النظام. تأكد أن جهازاً آخر يغطي نفس الوظيفة وأن الحوض بقي ضمن التشغيل الآمن.",reasonEn:"Important equipment was removed. Confirm another device covers the same function and the tank remains safely supported.",verifyAfter:hours(4),weight:1.15}));}
 const recentEquipmentFailures=(tank.intelligenceEvents??[]).filter(e=>e.domain==="equipment"&&e.verb==="failure"&&Date.now()-new Date(e.timestamp).getTime()<7*86400000);for(const failure of recentEquipmentFailures){const device=tank.equipment.find(x=>x.id===failure.entityId);if(!device)continue;const resolved=(tank.intelligenceEvents??[]).some(e=>e.domain==="equipment"&&e.verb==="failure_resolved"&&e.sourceId===failure.sourceId&&new Date(e.timestamp).getTime()>=new Date(failure.timestamp).getTime());if(resolved)continue;const peers=device.redundancyGroup?tank.equipment.filter(x=>x.id!==device.id&&x.redundancyGroup===device.redundancyGroup&&x.status==="on"):[];const protectedByBackup=Boolean(device.spareAvailable||peers.length);const critical=device.criticality==="critical"||["returnPump","heater","overflow","ato"].includes(device.kind);const level=critical&&!protectedByBackup?"danger" as const:"warn" as const;out.push(make({dedupeKey:`equipment:failure:${failure.sourceId}`,sourceEventIds:[failure.id],domain:"equipment",entityType:device.kind,entityId:device.id,level,confidence:100,status:"ready",page:"equipment",titleAr:`عطل يحتاج إجراء: ${device.name}`,titleEn:`Equipment failure needs action: ${device.name}`,reasonAr:protectedByBackup?`يوجد بديل/ازدواجية مسجلة، لكن يجب إصلاح العطل والتحقق من استمرار الوظيفة.`:`لا يوجد بديل عامل مسجل لهذا الجهاز${critical?" الحرج":""}. ${device.backupPlan?"خطة الاحتياط: "+device.backupPlan:"راجع الوظيفة المتأثرة وخطة الاحتياط فوراً."}`,reasonEn:protectedByBackup?"A spare/redundant device is recorded, but the failure still needs repair and functional verification.":`No active backup is recorded for this ${critical?"critical ":""}device. ${device.backupPlan?"Backup plan: "+device.backupPlan:"Review the affected function and backup plan now."}`,verifyAfter:hours(critical?4:24),weight:critical&&!protectedByBackup?1.2:1}));}
 for(const l of tank.livestock.filter(x=>x.health!=="good"))out.push(make({dedupeKey:`livestock:${l.id}:health`,sourceEventIds:eventIds(tank,"livestock"),domain:"livestock",entityType:l.category,entityId:l.id,level:l.health==="treatment"?"danger":"warn",confidence:90,status:"ready",page:l.health==="treatment"?"quarantine":"livestock",titleAr:`راقب حالة ${l.name}`,titleEn:`Monitor ${l.nameEn||l.name}`,reasonAr:l.health==="treatment"?"الكائن مسجل تحت العلاج ويحتاج متابعة الاستجابة.":"الكائن مسجل للمراقبة ويحتاج متابعة حالته.",reasonEn:l.health==="treatment"?"The organism is under treatment and needs response monitoring.":"The organism is on watch and needs follow-up.",verifyAfter:hours(12)}));
 const recentDeath=(tank.intelligenceEvents??[]).find(e=>e.domain==="livestock"&&e.verb==="death"&&Date.now()-new Date(e.timestamp).getTime()<72*3600000);if(recentDeath){const bodyRemoved=recentDeath.metadata?.bodyRemoved===true;out.push(make({dedupeKey:`livestock:death:${recentDeath.sourceId||recentDeath.entityId}`,sourceEventIds:[recentDeath.id],domain:"livestock",entityType:recentDeath.entityType,entityId:recentDeath.entityId,level:bodyRemoved?"warn":"danger",confidence:recentDeath.confidence??90,status:"ready",page:"chemistry",titleAr:bodyRemoved?"راقب الحوض بعد وفاة كائن":"أزل الجسم وافحص الحوض بعد وفاة كائن",titleEn:bodyRemoved?"Monitor tank after livestock death":"Remove body and check tank after livestock death",reasonAr:bodyRemoved?"تمت إزالة الجسم، لكن الوفاة قد تكون إشارة لمشكلة صحية أو بيئية. راقب الكائنات وافحص القيم ذات الصلة.":"الجسم لم يُسجل كمزال من الحوض؛ التحلل قد يرفع الحمل العضوي. أزله إن أمكن وراقب الأمونيا/النتريت وبقية الكائنات.",reasonEn:bodyRemoved?"The body was removed, but the death can signal a health or environmental issue. Observe livestock and check relevant parameters.":"The body was not recorded as removed; decomposition can increase organic load. Remove it if possible and monitor ammonia/nitrite and livestock.",verifyAfter:hours(bodyRemoved?12:4),weight:bodyRemoved?1:1.15}));if(recentDeath.metadata?.symptoms)out.push(make({dedupeKey:`livestock:death:${recentDeath.sourceId}:symptoms`,sourceEventIds:[recentDeath.id],domain:"livestock",entityType:recentDeath.entityType,entityId:recentDeath.entityId,level:"warn",confidence:85,status:"ready",page:"diseases",titleAr:"راجع أعراض الوفاة على بقية الكائنات",titleEn:"Review death symptoms across remaining livestock",reasonAr:`تم تسجيل أعراض قبل الوفاة: ${String(recentDeath.metadata.symptoms)}. راقب ظهورها على كائنات أخرى.`,reasonEn:`Symptoms were recorded before death: ${String(recentDeath.metadata.symptoms)}. Watch for the same signs in other livestock.`,verifyAfter:hours(12)}));}
 const recentFeeds=(tank.intelligenceEvents??[]).filter(e=>e.domain==="feeding"&&e.verb==="fed"&&Date.now()-new Date(e.timestamp).getTime()<7*86400000);const nutrientIssue=chem.problems.find(p=>p.parameter==="NO3"||p.parameter==="PO4");if(nutrientIssue&&recentFeeds.length>=7)out.push(make({dedupeKey:"feeding:nutrients:review",sourceEventIds:[...eventIds(tank,"feeding"),...eventIds(tank,"chemistry")],domain:"feeding",level:"warn",confidence:75,status:"suggested",page:"feeding",titleAr:"راجع روتين التغذية مع ارتفاع المغذيات",titleEn:"Review feeding routine with elevated nutrients",reasonAr:`تم تسجيل ${recentFeeds.length} تغذية خلال 7 أيام مع وجود مشكلة NO3/PO4. هذه علاقة زمنية تستحق المراجعة وليست إثباتاً أن التغذية هي السبب.`,reasonEn:`${recentFeeds.length} feedings were logged in 7 days while NO3/PO4 is problematic. This is a temporal association worth reviewing, not proof that feeding caused it.`,weight:1}));
 const recentWC=(tank.intelligenceEvents??[]).find(e=>e.domain==="waterChange"&&e.verb==="water_changed"&&Date.now()-new Date(e.timestamp).getTime()<48*3600000);if(recentWC){const verifyAt=new Date(new Date(recentWC.timestamp).getTime()+12*3600000).toISOString();const measuredAfter=(tank.intelligenceEvents??[]).some(e=>e.domain==="chemistry"&&e.verb==="measured"&&new Date(e.timestamp).getTime()>new Date(recentWC.timestamp).getTime());if(!measuredAfter&&Number(recentWC.value)>=20)out.push(make({dedupeKey:`waterChange:${recentWC.sourceId}:verify`,sourceEventIds:[recentWC.id],domain:"waterChange",level:"info",confidence:100,status:Date.now()>=new Date(verifyAt).getTime()?"ready":"suggested",page:"chemistry",titleAr:"تحقق من استقرار الحوض بعد تغيير الماء",titleEn:"Verify tank stability after water change",reasonAr:`تم تغيير ${recentWC.value}% من الماء. بعد التغيير الملحوظ، قراءة متابعة تساعد العقل على تقييم النتيجة بدل افتراض التحسن.`,reasonEn:`${recentWC.value}% of the water was changed. A follow-up reading lets the system evaluate the outcome instead of assuming improvement.`,dueAt:verifyAt,verifyAfter:verifyAt}));}
 const bio=bioload(tank);if(bio.status==="high"||bio.status==="danger")out.push(make({dedupeKey:"livestock:bioload",sourceEventIds:eventIds(tank,"livestock"),domain:"livestock",level:bio.status==="danger"?"danger":"warn",confidence:80,status:"ready",page:"livestock",titleAr:"راجع الحمل الحيوي قبل أي إضافة جديدة",titleEn:"Review bioload before adding livestock",reasonAr:"الحمل الحيوي الحالي مرتفع بالنسبة لحجم النظام ويؤثر على التغذية والكيمياء والفلترة.",reasonEn:"Current bioload is high for system volume and affects feeding, chemistry and filtration."}));
 const latestDoseByParam=new Map<string,IntelligenceEvent>();for(const e of tank.intelligenceEvents??[]){if(e.domain==="dosing"&&e.verb==="dose_given"&&e.parameter&&!latestDoseByParam.has(e.parameter))latestDoseByParam.set(e.parameter,e);}
 for(const [parameter,e] of latestDoseByParam){const verify=typeof e.metadata?.verifyAfter==="string"?e.metadata.verifyAfter:new Date(new Date(e.timestamp).getTime()+24*3600000).toISOString();const measuredAfter=(tank.intelligenceEvents??[]).find(x=>x.domain==="chemistry"&&x.parameter===parameter&&x.verb==="measured"&&new Date(x.timestamp).getTime()>new Date(e.timestamp).getTime());if(!measuredAfter)out.push(make({dedupeKey:`dosing:${parameter}:verify`,sourceEventIds:[e.id],domain:"dosing",parameter,level:"warn",confidence:100,status:new Date(verify).getTime()>Date.now()?"suggested":"ready",page:"chemistry",titleAr:`إعادة قياس ${parameter} بعد الجرعة`,titleEn:`Retest ${parameter} after dosing`,reasonAr:"تم تسجيل جرعة ولم تُسجل بعدها قراءة تحقق بعد. لا تكرر التصحيح قبل معرفة الاستجابة.",reasonEn:"A dose was logged without a later verification reading. Do not repeat correction before confirming the response.",dueAt:verify,verifyAfter:verify}));}
 const todayKey=new Date().toISOString().slice(0,10);for(const m of tank.maintenance){if(m.done||!m.nextDue||m.nextDue>=todayKey)continue;const daysLate=Math.max(1,Math.floor((Date.now()-new Date(`${m.nextDue}T23:59:59`).getTime())/86400000));const linkedEquipment=m.sourceEquipmentId?tank.equipment.find(e=>e.id===m.sourceEquipmentId):undefined;const critical=linkedEquipment?.criticality==="critical"||Boolean(linkedEquipment&&["returnPump","heater","overflow","ato"].includes(linkedEquipment.kind));const level=critical||daysLate>=7?"danger" as const:"warn" as const;out.push(make({dedupeKey:`maintenance:overdue:${m.id}`,sourceEventIds:eventIds(tank,"maintenance"),domain:"maintenance",entityType:"task",entityId:m.id,level,confidence:100,status:"ready",page:"maintenance",titleAr:`صيانة متأخرة: ${m.title}`,titleEn:`Overdue maintenance: ${m.titleEn||m.title}`,reasonAr:`المهمة متأخرة ${daysLate} يوم${linkedEquipment?` ومرتبطة بالجهاز ${linkedEquipment.name}`:""}. عدم التنفيذ أصبح معلومة مؤثرة بحد ذاته.`,reasonEn:`This task is ${daysLate} day(s) overdue${linkedEquipment?` and is linked to ${linkedEquipment.name}`:""}. The missed action is now meaningful system context.`,dueAt:m.nextDue,weight:critical?1.15:daysLate>=7?1.1:1}));}
 const activeEmergency=(tank.emergencySessions??[]).find(x=>x.status==="active");if(activeEmergency)out.push(make({dedupeKey:`emergency:${activeEmergency.id}`,sourceEventIds:eventIds(tank,"emergency"),domain:"emergency",entityType:"protocol",entityId:activeEmergency.id,level:"danger",confidence:100,status:"ready",page:"emergency",titleAr:activeEmergency.titleAr,titleEn:activeEmergency.titleEn,reasonAr:"بروتوكول طوارئ نشط ويأخذ الأولوية على الإجراءات الروتينية.",reasonEn:"An active emergency protocol takes priority over routine actions.",weight:1.1}));
 const activeQ=tank.quarantine.filter(x=>x.status==="active");for(const q of activeQ)if(q.nextDoseAt&&new Date(q.nextDoseAt).getTime()<Date.now())out.push(make({dedupeKey:`quarantine:${q.id}:dose`,sourceEventIds:eventIds(tank,"quarantine"),domain:"quarantine",entityType:"case",entityId:q.id,level:"warn",confidence:100,status:"ready",page:"quarantine",titleAr:`جرعة علاج مستحقة: ${q.organism}`,titleEn:`Treatment dose due: ${q.organism}`,reasonAr:"موعد الجرعة المسجل أصبح مستحقاً؛ راجع العلاج والملصق قبل التنفيذ.",reasonEn:"The recorded dose is due; verify treatment and product label before dosing."}));
 return out.sort((a,b)=>b.priority-a.priority);
}
