export type Language = "ar" | "en";
export type TankType = "marine" | "freshwater";
export type TankStatus = "new" | "cycling" | "established";

export type EquipmentKind =
  | "lighting" | "waveMaker" | "skimmer" | "returnPump" | "filterSock"
  | "rollerFilter" | "reactor" | "heater" | "doser" | "uv" | "ozone"
  | "ato" | "refugiumLight" | "turfScrubber" | "probe" | "overflow" | "co2" | "other";

export interface DimensionsCm { length: number; width: number; height: number; }

export interface DisplayEquipmentPosition {
  xPct: number;
  yPct: number;
  zPct: number;
  rotationY?: number;
  flowStrength?: number;
  scale?: number;
}

export interface EquipmentFailureEvent {
  id:string;
  timestamp:string;
  note:string;
  resolvedAt?:string;
}

export interface EquipmentConsumable {
  id:string;
  name:string;
  nameEn?:string;
  installedAt?:string;
  lifeDays?:number;
  quantityOnHand?:number;
  minimumOnHand?:number;
  unit?: "pc" | "g" | "mL" | "L" | "m";
}

export interface Equipment {
  id: string;
  name: string;
  kind: EquipmentKind;
  legacyKind?: string;
  brand?: string;
  model?: string;
  location: "display" | "external" | `sump:${string}`;
  installedAt?: string;
  lastServiceAt?: string;
  serviceIntervalDays?: number;
  futurePlan?: string;
  status: "on" | "off" | "service" | "warning";
  displayPosition?: DisplayEquipmentPosition;
  overflowPlumbingMode?: "combined" | "separate";
  overflowReturnPosition?: DisplayEquipmentPosition;
  powerWatts?: number;
  hoursPerDay?: number;
  /** Manufacturer-rated aquarium/system volume, when applicable (e.g. skimmer/filter). */
  ratedVolumeLiters?: number;
  /** Nominal water flow in liters/hour for pumps, wavemakers, filters, etc. */
  flowLph?: number;
  /** Measured/estimated PAR at the livestock target depth for aquarium lighting. */
  parAtTargetDepth?: number;
  /** Manufacturer or measured lighting coverage dimensions. */
  coverageLengthCm?: number;
  coverageWidthCm?: number;
  /** Expected service life override; defaults are inferred by equipment kind. */
  expectedLifeMinDays?: number;
  expectedLifeMaxDays?: number;
  criticality?: "critical" | "important" | "normal";
  redundancyGroup?: string;
  spareAvailable?: boolean;
  backupPlan?: string;
  failures?: EquipmentFailureEvent[];
  consumables?: EquipmentConsumable[];
  postActionCheckAt?: string;
  co2Mode?: "lowTech" | "injected";
  co2CylinderRemainingPercent?: number;
  co2DropChecker?: "blue" | "green" | "yellow" | "unknown";
}

export interface EnergySettings {
  pricePerKwh: number;
  currency: string;
}

export interface SumpChamber {
  id: string;
  name: string;
  nameEn?: string;
  x: number;
  y: number;
  length: number;
  width: number;
  height: number;
  waterHeight: number;
  media: ("biological" | "chemical" | "refugium" | "turf")[];
  items?: string[];
  contents?: string;
  notes?: string;
}

export interface Sump {
  enabled: boolean;
  dimensions: DimensionsCm;
  operatingFillPercent: number;
  /** Measured water that drains back to the sump during a real power-off test. */
  measuredDrainbackLiters?: number;
  chambers: SumpChamber[];
}

export interface ChemistryReading {
  timestamp: string;
  values: Record<string, number | null>;
  notes?: string;
  usingDefaults?: boolean;
  source?: "manual"|"import"|"device";
  testKit?: string;
  confidence?: "high"|"medium"|"low";
}

export interface MaintenanceTask {
  id: string;
  title: string;
  titleEn?: string;
  cadence: "daily" | "weekly" | "monthly" | "quarterly" | "semiannual" | "annual" | "once";
  done: boolean;
  nextDue?: string;
  lastDone?: string;
  manual?: boolean;
  /** Equipment-generated maintenance task metadata. */
  sourceEquipmentId?: string;
  sourceEquipmentName?: string;
  autoGenerated?: boolean;
  intervalDays?: number;
  checklist?: string[];
  checklistDone?: number[];
  sourceDomain?: IntelligenceEventDomain;
  sourceId?: string;
}

export type AcclimationCategory = "fish" | "coral" | "invert" | "plant" | "macroalgae" | "other";

export interface LivestockItem {
  id: string;
  libraryId?: string;
  name: string;
  nameEn?: string;
  category: "fish" | "coral" | "invert" | "plant" | "other";
  /** Keeps meaningful sub-types such as marine macroalgae after transfer from acclimation. */
  subtype?: string;
  quantity: number;
  health: "good" | "watch" | "treatment";
  load?: number;
  addedAt?: string;
  notes?: string;
  sizeCm?: number;
  lastObservedAt?: string;
  plantGrowth?: "good" | "slow" | "stalled" | "melting";
  plantColor?: "normal" | "pale" | "yellow" | "redWeak" | "spots";
  algaePresent?: boolean;
  lastTrimmedAt?: string;
}

export interface LivestockExitEvent {
  id:string;
  timestamp:string;
  livestockId:string;
  name:string;
  nameEn?:string;
  category:LivestockItem["category"];
  quantity:number;
  reason:"death"|"sold"|"transferred"|"returned"|"removed"|"unknown";
  bodyRemoved?:boolean;
  symptoms?:string;
  notes?:string;
}

export type InventoryCategory =
  | "feeding"
  | "fertilizer"
  | "co2"
  | "dosing"
  | "supplement"
  | "filter_media"
  | "coral_treatment"
  | "medication"
  | "water_prep"
  | "equipment"
  | "testing"
  | "rodi"
  | "other";

export type InventoryConsumer =
  | "feeding"
  | "fertilizer"
  | "co2"
  | "dosing"
  | "acclimation"
  | "quarantine"
  | "waterChange"
  | "sump"
  | "equipment"
  | "testing"
  | "rodi";

export interface InventoryUsage {
  inventoryItemId: string;
  quantity: number;
  unit: string;
  role?: string;
  name?: string;
}

export interface InventoryItem {
  id: string;
  presetId?: string;
  name: string;
  nameEn?: string;
  /** Legacy display category retained for backward compatibility. */
  category?: string;
  categoryEn?: string;
  /** Canonical stock classification used by modules to show only relevant materials. */
  inventoryCategory?: InventoryCategory;
  inventorySubcategory?: string;
  tankCompatibility?: "marine" | "freshwater" | "both";
  consumedBy?: InventoryConsumer[];
  stockBehavior?: "consumable" | "asset";
  /** Optional exact mapping used by the corrective dosing calculator. */
  dosingParameter?: "KH" | "Ca" | "Mg";
  dosingCompoundId?: string;
  quantity: number;
  unit: string;
  minimum: number;
}

export type IntelligenceEventKind = "fact"|"observation"|"action"|"omission"|"outcome";
export type IntelligenceEventDomain = "chemistry"|"dosing"|"maintenance"|"equipment"|"livestock"|"inventory"|"feeding"|"waterChange"|"rodi"|"quarantine"|"emergency"|"acclimation"|"sump"|"journal"|"expense"|"system";
export interface IntelligenceEvent {
  id:string;
  timestamp:string;
  kind:IntelligenceEventKind;
  domain:IntelligenceEventDomain;
  verb:string;
  entityType?:string;
  entityId?:string;
  parameter?:string;
  value?:number|string|boolean|null;
  unit?:string;
  confidence?:number;
  sourceId?:string;
  sourcePage?:string;
  textAr:string;
  textEn:string;
  metadata?:Record<string,string|number|boolean|null>;
}

export type GuidanceActionStatus = "suggested"|"ready"|"blocked"|"in_progress"|"done"|"awaiting_verification"|"verified"|"resolved";
export interface GuidanceAction {
  id:string;
  dedupeKey:string;
  createdAt:string;
  updatedAt:string;
  sourceEventIds:string[];
  domain:IntelligenceEventDomain;
  entityType?:string;
  entityId?:string;
  parameter?:string;
  level:"info"|"warn"|"danger";
  priority:number;
  confidence:number;
  status:GuidanceActionStatus;
  page:string;
  titleAr:string;
  titleEn:string;
  reasonAr:string;
  reasonEn:string;
  resourcePresetId?:string;
  blockedReasonAr?:string;
  blockedReasonEn?:string;
  dueAt?:string;
  executedAt?:string;
  verifyAfter?:string;
  verifiedAt?:string;
  outcome?:"improved"|"stable"|"worse"|"unknown";
  verificationEventId?:string;
  resolvedReasonAr?:string;
  resolvedReasonEn?:string;
}

export interface TimelineEvent {
  id: string;
  timestamp: string;
  type: string;
  textAr: string;
  textEn: string;
}

export interface HealthSnapshot {
  id: string;
  timestamp: string;
  score: number;
  chemistry: number | null;
  maintenance: number;
  state: "excellent" | "stable" | "watch" | "stressed" | "critical";
  reasonAr: string;
  reasonEn: string;
  relatedEventId?: string;
}

export interface JournalPhoto {
  id: string;
  timestamp: string;
  caption: string;
  dataUrl: string;
  livestockId?: string;
  estimatedSizeCm?: number;
  colorIndex?: number;
  brightnessIndex?: number;
  captureScore?: number;
  contrastIndex?: number;
  sharpnessIndex?: number;
  clarityIndex?: number;
  glarePercent?: number;
  shadowPercent?: number;
  palePixelPercent?: number;
  greenDominancePercent?: number;
  brightSpotPercent?: number;
  redDominancePercent?: number;
  blueDominancePercent?: number;
  edgeDensity?: number;
}

export interface VisionAssessmentRecord {
  id: string;
  timestamp: string;
  photoId: string;
  livestockId?: string;
  symptoms: string[];
  notes?: string;
  metrics: {
    colorIndex: number;
    brightnessIndex: number;
    captureScore: number;
    contrastIndex?: number;
    sharpnessIndex?: number;
    clarityIndex?: number;
    glarePercent?: number;
    shadowPercent?: number;
    palePixelPercent?: number;
    greenDominancePercent?: number;
    brightSpotPercent?: number;
    redDominancePercent?: number;
    blueDominancePercent?: number;
    edgeDensity?: number;
  };
  triage: {
    level: "monitor" | "attention" | "urgent";
    confidence: "low" | "medium";
    confidenceScore: number;
    summaryAr: string;
    summaryEn: string;
    observationsAr: string[];
    observationsEn: string[];
    possibilitiesAr: string[];
    possibilitiesEn: string[];
    nextAr: string[];
    nextEn: string[];
    contextAr: string[];
    contextEn: string[];
    comparisonAr?: string;
    comparisonEn?: string;
    engine: string;
  };
  modelStatus: "local-best";
  engine: string;
  external?: {
    status: "not_requested" | "unavailable" | "completed" | "error";
    provider?: string;
    model?: string;
    text?: string;
    error?: string;
    analyzedAt?: string;
  };
  diseaseCandidateIds?: string[];
  followUpTaskId?: string;
  quarantineCaseId?: string;
}

export interface FeedingLog {
  id: string;
  timestamp: string;
  food: string;
  amount: string;
  notes?: string;
  inventoryItemId?: string;
  inventoryQuantityUsed?: number;
  inventoryUnit?: string;
}

export interface DosingLog {
  id: string;
  timestamp: string;
  parameter: string;
  current?: number;
  target?: number;
  ml: number;
  amount?: number;
  unit?: string;
  chamberMaterial?: string;
  material?: string;
  inventoryItemId?: string;
  reason?: string;
  sourceReadingTimestamp?: string;
  plannedSteps?: number;
  steps?: number;
  perStep?: number;
  stepIndex?: number;
  calculatorMode?: "dry" | "stock" | "product" | "routine";
  status?: "planned" | "in_progress" | "logged";
  verifyAfter?: string;
}

export interface DoserChannel {
  id: string;
  name: string;
  material: string;
  capacityMl: number;
  currentMl: number;
  consumption: number;
  period: "daily" | "weekly" | "monthly";
  color: string;
}

export interface FilterMediaItem {
  id: string;
  name: string;
  kind: "gfo" | "activatedCarbon" | "other";
  amountGrams: number;
  installedAt: string;
  referenceLifeDays: number;
  chamberId?: string;
  notes?: string;
  inventoryItemId?: string;
  inventoryQuantityPerReplacement?: number;
  inventoryUnit?: string;
}

export interface QuarantineCase {
  id: string;
  livestockId?: string;
  suspectedDiseaseId?: string;
  symptoms?: string;
  outcome?: "resolved" | "improved" | "stable" | "worse";
  organism: string;
  reason: string;
  plan: string;
  start: string;
  status: "active" | "closed";
  quarantineVolumeLiters?: number;
  treatmentProduct?: string;
  labelDoseMlPer100L?: number;
  intervalHours?: number;
  totalDoses?: number;
  dosesGiven?: number;
  nextDoseAt?: string;
  lastDoseAt?: string;
  notes?: string;
  medicationInventoryItemId?: string;
  medicationUnit?: string;
  medicationQuantityPerDose?: number;
  responseObservedAt?: string;
}

export interface EmergencySession {
  id: string;
  scenarioId: string;
  titleAr: string;
  titleEn: string;
  startedAt: string;
  completedAt?: string;
  completedSteps: number[];
  status: "active" | "completed";
  outcome?: "unknown" | "improved" | "stable" | "worse" | "resolved";
  verifyAfter?: string;
}

export interface ExpenseItem {
  id: string;
  date: string;
  description: string;
  amount: number;
  currency: string;
}

export interface WaterChangeLog {
  id: string;
  timestamp: string;
  liters: number;
  percent: number;
  salinity?: number;
  temperature?: number;
  notes?: string;
  saltInventoryItemId?: string;
  saltQuantityUsed?: number;
  rodiBatchId?: string;
  inventoryUses?: InventoryUsage[];
}

export interface RODILog {
  id: string;
  timestamp: string;
  tdsIn: number;
  tdsOut: number;
  liters: number;
  wasteLiters?: number;
  productionMinutes?: number;
  sourcePressurePsi?: number;
}

export interface RODIServiceEvent {
  id: string;
  timestamp: string;
  component: "sediment" | "carbon" | "di";
  inventoryUse?: InventoryUsage;
  notes?: string;
}

export interface PlantCareLog {
  id: string;
  timestamp: string;
  kind: "fertilizer" | "co2_refill";
  inventoryUse?: InventoryUsage;
  equipmentId?: string;
  notes?: string;
}

export interface AcclimationItem {
  id: string;
  libraryId?: string;
  name: string;
  nameEn?: string;
  category: AcclimationCategory;
  quantity: number;
  dripMinutes: number;
  intervalMinutes: number;
  placement: string;
  notes?: string;
  temperament?: "peaceful" | "semi" | "aggressive";
  sensitivity?: "normal" | "sensitive" | "hardy";
  subtype?: string;
  health: "unknown" | "good" | "fair" | "stressed" | "critical" | "watch";
  status: "waiting" | "acclimating" | "paused" | "ready" | "added" | "deferred" | "emergency";
  startedAt?: string;
  extraMinutes?: number;
  remainingMs?: number;
  endAt?: number | null;
  readyAt?: string;
  addedAt?: string;
  imageDataUrl?: string;
  emergency?: boolean;
}

export interface AcclimationEvent {
  id: string;
  timestamp: string;
  textAr: string;
  textEn: string;
}

export type CoralDipRunStatus = "running" | "ready_to_rinse" | "rinsed" | "cancelled";

export interface CoralDipRun {
  id: string;
  batchId: string;
  itemIds: string[];
  productName: string;
  inventoryItemId: string;
  quantityUsed: number;
  unit: string;
  durationMinutes: number;
  status: CoralDipRunStatus;
  startedAt: string;
  remainingMs?: number;
  endAt?: number | null;
  completedAt?: string;
  rinsedAt?: string;
}

export interface AcclimationSession {
  id: string;
  startedAt: string;
  completedAt?: string;
  status: "setup" | "floating" | "transfer" | "drip" | "release" | "completed";
  wizardStep?: number;
  categories?: AcclimationCategory[];
  tankSalinity?: number;
  bagSalinity?: number;
  temperature?: number;
  existingNotes?: string;
  coralDipEnabled?: boolean;
  coralDipMinutes?: number;
  /** Default inventory-backed Coral Dip preparation used when a coral batch starts. */
  coralDipInventoryItemId?: string;
  /** Quantity consumed from inventory for each freshly prepared dip bath. */
  coralDipQuantityPerPrep?: number;
  /** Each preparation is logged separately so inventory is consumed once per bath, not once per coral. */
  coralDipRuns?: CoralDipRun[];
  /** Explicit safety exception for distressed coral where the user intentionally skips dip. */
  coralDipSkippedItemIds?: string[];
  floatConfirmed: boolean;
  floatStatus?: "waiting" | "running" | "paused" | "ready" | "done";
  floatStartedAt?: string;
  floatRemainingMs?: number;
  floatEndAt?: number | null;
  bucketStatus?: "waiting" | "running" | "paused" | "ready" | "done";
  bucketStartedAt?: string;
  bucketRemainingMs?: number;
  bucketEndAt?: number | null;
  dripStartedAt?: string;
  preflight?: Record<string, boolean>;
  items: AcclimationItem[];
  events: AcclimationEvent[];
}

export interface Tank {
  id: string;
  name: string;
  /** Built-in protected aquarium used only for learning/exploration. */
  isTraining?: boolean;
  /** Start of the current hands-on training run; reset with the training tank. */
  trainingStartedAt?: string;
  type: TankType;
  /** Optional explicit ecosystem profile. When omitted Aqua Nexus infers it from livestock/history/name. */
  ecosystemProfile?: "fishOnly" | "reef" | "planted" | "mixed";
  plantedMode?: "lowTech" | "highTech";
  substrateType?: "inert" | "nutrient" | "soil" | "mixed";
  substrateStartedAt?: string;
  status: TankStatus;
  ageMonths?: number;
  display: DimensionsCm & {
    displacementPercent: number;
    grossLiters: number;
    netLiters: number;
  };
  sump: Sump;
  systemVolumeLiters: number;
  equipment: Equipment[];
  energySettings?: EnergySettings;
  chemistry: ChemistryReading[];
  maintenance: MaintenanceTask[];
  livestock: LivestockItem[];
  livestockExits?: LivestockExitEvent[];
  inventory: InventoryItem[];
  timeline: TimelineEvent[];
  intelligenceEvents?: IntelligenceEvent[];
  guidanceActions?: GuidanceAction[];
  healthSnapshots?: HealthSnapshot[];
  photos: JournalPhoto[];
  visionAssessments?: VisionAssessmentRecord[];
  feeding: FeedingLog[];
  dosing: DosingLog[];
  doserChannels: DoserChannel[];
  filterMedia?: FilterMediaItem[];
  quarantine: QuarantineCase[];
  emergencySessions?: EmergencySession[];
  expenses: ExpenseItem[];
  waterChanges: WaterChangeLog[];
  rodi: RODILog[];
  rodiServiceEvents?: RODIServiceEvent[];
  plantCare?: PlantCareLog[];
  acclimationSessions?: AcclimationSession[];
  createdAt: string;
}

export interface AquaState {
  language: Language;
  selectedTankId: string;
  tanks: Tank[];
}
