"use client";

import { useState } from "react";
import type { Language } from "@/domain/types";
import type { AppPage } from "@/components/navigation/MainNav";
import { Modal } from "@/components/ui/Modal";
import { useAquaStore } from "@/store/useAquaStore";
import { markFeatureLearned } from "@/lib/featureDiscovery";

type PageHelp={
 titleAr:string;titleEn:string;
 summaryAr:string;summaryEn:string;
 capabilitiesAr:string[];capabilitiesEn:string[];
 featuresAr:string[];featuresEn:string[];
};

const HELP:Record<AppPage,PageHelp>={
 dashboard:{titleAr:"لوحة القيادة",titleEn:"Dashboard",summaryAr:"مركز قيادة الحوض: يعرض الحالة والخطر والخطوة التالية، ويربط Tank Brain بين الكيمياء والتجهيزات والكائنات والصيانة والتاريخ، ويعرّفك دورياً على الميزات التي قد لا تكون اكتشفتها.",summaryEn:"The aquarium command center: tank state, risk, next action and Tank Brain links across chemistry, equipment, livestock, maintenance and history, plus rotating feature discovery tips.",capabilitiesAr:["حالة الحوض والخطر والإجراء التالي","Smart Import ظاهر ومباشر من الداشبورد","تخصيص وترتيب صناديق التحليل","بحث شامل وتسجيل سريع من أعلى البرنامج","توقعات وذاكرة وروابط سبب/نتيجة","3D Digital Twin ومشاركة حالة الحوض"],capabilitiesEn:["Tank state, risk and next action","Smart Import exposed directly on Dashboard","Customize and reorder analysis cards","Global search and Quick Log","Forecasts, memory and cause/effect links","3D Digital Twin and tank-status sharing"],featuresAr:["فقاعات ميزات هادئة: 45 ثانية مع وقفة للقراءة و35 ثانية قبل المعلومة التالية","مؤشرات صحة مبنية على أدلة","تنبيهات وإجراءات ذكية مترابطة","آخر بيانات الأجهزة المستوردة","زر ؟ تعليمات الصفحة موجود دائماً بالأعلى"],featuresEn:["Calm feature bubbles: 45-second rise with a reading pause and 35 seconds before the next tip","Evidence-based health indicators","Linked alerts and smart actions","Latest imported device data","Persistent page-help button at the top"]},
 tanks:{titleAr:"الأحواض",titleEn:"Tanks",summaryAr:"إدارة جميع الأحواض والتبديل بينها مع الاحتفاظ بسياق وبيانات مستقلة لكل حوض.",summaryEn:"Manage all aquariums and switch between them while keeping independent context and data for each tank.",capabilitiesAr:["تعدد الأحواض","اختيار الحوض النشط","مراجعة الحجم والنوع والحالة"],capabilitiesEn:["Multiple tanks","Select active tank","Review volume, type and status"],featuresAr:["فصل البيانات لكل حوض","إعداد ذكي لحوض جديد","انتقال سريع بين الأحواض"],featuresEn:["Per-tank data separation","Smart tank setup","Fast tank switching"]},
 equipment:{titleAr:"التجهيزات والاستيراد الذكي",titleEn:"Equipment & Smart Import",summaryAr:"إدارة دورة حياة معدات الحوض مع الاستيراد الذكي من Screenshot أو ملفات Controller وتوزيع البيانات تلقائياً على الوحدات الصحيحة بعد مراجعتك.",summaryEn:"Manage equipment lifecycle plus Smart Import from controller screenshots/exports, routing reviewed data into the correct Aqua Nexus modules.",capabilitiesAr:["Smart Import من صورة أو CSV/JSON/TXT/XML/LOG","مسودة قابلة للتعديل قبل الاعتماد","توزيع Chemistry وDosing وATO وTelemetry وAlerts تلقائياً","إضافة وتعديل المعدات ومكانها باللمس","متابعة الطاقة والتكلفة","العمر والأعطال والازدواجية والاحتياط وقطع الاستهلاك"],capabilitiesEn:["Smart Import from image or CSV/JSON/TXT/XML/LOG","Editable review draft before applying","Automatic Chemistry, Dosing, ATO, Telemetry and Alerts routing","Add/edit equipment and touch placement","Energy and cost monitoring","Lifecycle, failures, redundancy, spares and consumables"],featuresAr:["حفظ مصدر وثقة كل استيراد","منع القيم الكيميائية غير المنطقية","تنبيهات الجهاز تدخل مركز التنبيهات وTank Brain","مجسم حي للحوض والسامب والتجهيزات الخارجية","تقييم كفاية المعدات حسب بروفايل الحوض"],featuresEn:["Import provenance and confidence","Implausible chemistry blocking","Device alerts feed Alerts and Tank Brain","Live system layout for display, sump and external devices","Profile-aware equipment adequacy"]},
 lighting:{titleAr:"الإنارة الذكية",titleEn:"Lighting Intelligence",summaryAr:"بناء برنامج إنارة فعلي وربطه بالمعدات والكائنات وعمق الحوض، مع محاكاة يوم كامل 3D وتحليل التغطية والتموضع.",summaryEn:"Build a real lighting schedule linked to fixtures, livestock and tank depth, with full-day 3D simulation, coverage analysis and placement intelligence.",capabilitiesAr:["برنامج متعدد القنوات ونقاط زمنية","محاكاة يوم كامل بسرعة ×10","تغير لون وسطوع الحوض 3D حسب البرنامج","خرائط Top / Front / 3D وتقدير PAR","خريطة عمق وتموضع للمرجان أو النبات","استيراد برنامج الإنارة من ملف أو Screenshot مع مراجعة"],capabilitiesEn:["Multi-channel time-point schedule","10× full-day simulation","3D tank color/brightness follows the schedule","Top / Front / 3D maps and estimated PAR","Depth placement map for corals/plants","Lighting import from file or screenshot with review"],featuresAr:["Marine وFreshwater logic","Required wattage وFixture coverage","Measured PAR calibration","تنبيه إذا موقع الكائن خارج نطاقه المناسب","تاريخ نسخ البرنامج وتحليل التغييرات","ربط كامل مع Tank Brain وAI"],featuresEn:["Marine and freshwater logic","Required wattage and fixture coverage","Measured PAR calibration","Placement suitability warnings","Program-version history and change analysis","Tank Brain and AI linkage"]},
 sump:{titleAr:"السامب",titleEn:"Sump",summaryAr:"مخطط سامب حقيقي مبني على أبعاد الحجر ومواقعها ومناسيب الماء، وليس رسماً ثابتاً، ويرتبط بالمعدات والمجسم الرقمي للنظام.",summaryEn:"A real sump model driven by chamber dimensions, positions and water levels rather than a fixed diagram, linked to equipment and the system digital twin.",capabilitiesAr:["أبعاد وحجم ومنسوب كل حجرة","ترتيب 2D مرن للحجر أمام/خلف وجنب بعض","Top view ومشهد أمامي تفصيلي","توزيع المعدات والميديا داخل كل حجرة","حساب حجم التشغيل الفعلي"],capabilitiesEn:["Per-chamber dimensions, volume and water level","Flexible 2D chamber layout","Top view and detailed front/elevation view","Equipment/media placement by chamber","Operating-volume calculation"],featuresAr:["المخطط العلوي يظهر على الداشبورد","رموز للمعدات والميديا بدل الصور الحرفية","يتحدث مع تغييرات التجهيزات","جزء من Digital Twin للنظام"],featuresEn:["Top plan is reflected on Dashboard","Symbolic equipment/media icons","Updates with equipment changes","Feeds the system Digital Twin"]},
 livestock:{titleAr:"الكائنات",titleEn:"Livestock",summaryAr:"السجل الحي للأسماك والمرجان والنباتات واللافقاريات مع الصحة والتوافق والموضع والارتباط بالإقلمة والصور والتاريخ.",summaryEn:"The live registry for fish, corals, plants and invertebrates with health, compatibility, placement, acclimation, photos and history.",capabilitiesAr:["إضافة وتصنيف الكائنات والكميات","متابعة الصحة والحالة","فحص التوافق بين الكائنات","ربط الصور والنمو والسجل","تحديد X/Z والعمق للكائنات التي تحتاج تموضع","تقدير الحمل الحيوي"],capabilitiesEn:["Add/classify livestock and quantities","Health/status tracking","Compatibility checks","Photos, growth and history linkage","X/Z/depth placement where relevant","Bioload estimation"],featuresAr:["المرجان والنبات يرتبطان بخريطة الإنارة والعمق","الكائن الناتج عن الإقلمة يضاف للسجل تلقائياً","تنبيهات توافق مستمرة على الداشبورد","تكامل مع الحجر والأمراض والمكتبة"],featuresEn:["Corals/plants link to lighting-depth placement","Completed acclimation feeds livestock automatically","Persistent compatibility alerts on Dashboard","Quarantine, disease and library integration"]},
 acclimation:{titleAr:"الإقلمة",titleEn:"Acclimation",summaryAr:"معالج أمان لإدخال الشحنات الجديدة؛ يدير أنواعاً متعددة بالتوازي مع عدادات مستقلة واستثناءات للحالات المتعبة وربط نهائي بالسجل والمخزون.",summaryEn:"A safety-first intake workflow for new shipments, running multiple category-specific timers in parallel with stressed-arrival exceptions and final registry/inventory linkage.",capabilitiesAr:["عدادات متوازية لأكثر من مجموعة بنفس الوقت","خطوات مختلفة للسمك واللافقاريات والمرجان والنبات","حالة خاصة للكائن المتعب","Coral Dip كجزء من مسار المرجان","تنبيهات لكل عداد وخطوة","تسجيل الاسم والنوع والعدد والصحة والوقت"],capabilitiesEn:["Parallel timers for multiple groups","Separate fish/invert/coral/plant workflows","Stressed-arrival exception path","Coral Dip in coral workflow","Per-timer and per-step alerts","Name/type/count/health/time logging"],featuresAr:["بعد الإقلمة الناجحة يضاف الكائن للحوض تلقائياً","استخدام الـDip يؤثر على المخزون","عدم نقل ماء الكيس إلى الحوض ضمن المسار المناسب","سجل نهائي قابل للمراجعة","نصائح تموضع للمرجان والنبات"],featuresEn:["Successful acclimation adds livestock automatically","Dip use updates inventory","Bag-water exclusion where appropriate","Reviewable final log","Coral/plant placement guidance"]},
 library:{titleAr:"المكتبة",titleEn:"Library",summaryAr:"مرجع داخلي للأنواع والمعلومات المساعدة المرتبطة بالكائنات وإدارتها.",summaryEn:"An internal reference for species and care information linked to aquarium management.",capabilitiesAr:["بحث مرجعي","معلومات الأنواع","استخدام البيانات عند إضافة الكائنات"],capabilitiesEn:["Reference search","Species information","Use data when adding livestock"],featuresAr:["وصول سريع للمعلومة","ربط مع الكائنات","مرجع داخل نفس البرنامج"],featuresEn:["Fast reference access","Livestock linkage","In-app knowledge source"]},
 chemistry:{titleAr:"الكيمياء",titleEn:"Chemistry",summaryAr:"تسجيل واستيراد وتحليل كيمياء الحوض مع فصل صحة القيم عن جودة البيانات، وفحص الحدود والتكرار والحداثة قبل أن تدخل القراءات للذكاء.",summaryEn:"Log, import and analyze chemistry while separating parameter health from data quality, validating bounds, duplicates and freshness before readings feed intelligence.",capabilitiesAr:["تسجيل القيم المقاسة فقط بدون نسخ آخر قراءة","استيراد تاريخ CSV أو TXT","فحص القيم غير المنطقية والتكرار","Ideal وSafe bands والرسوم الزمنية","Chemistry Health وData Confidence منفصلان","تغطية فحص الأسبوع وإكمال المهمة تلقائياً"],capabilitiesEn:["Log only actually measured values","Import historical CSV/TXT","Implausible-value and duplicate checks","Ideal/Safe bands and trends","Separate Chemistry Health and Data Confidence","Weekly panel coverage with task completion"],featuresAr:["قراءات الأجهزة المستوردة تصل للكيمياء مع حفظ المصدر والثقة","إرشاد شو تعمل الآن حسب المشاكل","كشف القراءات القديمة أو الناقصة","ربط الجرعات وتغييرات الماء والتاريخ مع التحليل"],featuresEn:["Imported device chemistry arrives with provenance/confidence","Problem-driven next-action guidance","Stale/missing reading detection","Dosing, water-change and history linkage"]},
 maintenance:{titleAr:"الصيانة",titleEn:"Maintenance",summaryAr:"تنظيم مهام الصيانة الدورية والمستحقة ومتابعة تنفيذها.",summaryEn:"Organize recurring and due maintenance tasks and track completion.",capabilitiesAr:["مهام دورية","مواعيد استحقاق","متابعة الإنجاز","مؤشر صحة الصيانة"],capabilitiesEn:["Recurring tasks","Due dates","Completion tracking","Maintenance health score"],featuresAr:["قائمة المستحق","متابعة الروتين","ربط بالأحداث والتنبيهات"],featuresEn:["Due-task list","Routine tracking","Event and alert linkage"]},
 inventory:{titleAr:"المخزون",titleEn:"Inventory",summaryAr:"متابعة مواد الحوض وقطع الاستهلاك والأدوية والـDip والمنتجات بحيث تتأثر الكميات بالاستخدام الحقيقي من الوحدات المرتبطة.",summaryEn:"Track aquarium supplies, consumables, treatments, dips and products with quantities updated by real use from linked workflows.",capabilitiesAr:["إضافة وتصنيف المواد والكميات","متابعة النقص وإعادة التزويد","ربط مواد الجرعات والصيانة","خصم المستهلك عند استخدامه بمسار مرتبط مثل Coral Dip"],capabilitiesEn:["Add/classify items and quantities","Low-stock and restock tracking","Dosing/maintenance material linkage","Consumption updates from linked workflows such as Coral Dip"],featuresAr:["سجل مخزون عملي بدل قائمة ثابتة","تكامل مع المعدات وقطع الاستهلاك","تنبيهات نقص المواد المهمة"],featuresEn:["Operational inventory rather than a static list","Equipment consumables integration","Low-stock alerts for important supplies"]},
 diseases:{titleAr:"الأمراض",titleEn:"Diseases",summaryAr:"مرجع وإدارة أولية للحالات المرضية والأعراض بدون ادعاء تشخيص قطعي.",summaryEn:"Reference and first-line management for disease signs without claiming definitive diagnosis.",capabilitiesAr:["مراجعة الأعراض","مرجع للحالات المحتملة","ربط مع الحجر والمتابعة"],capabilitiesEn:["Symptom review","Possible-condition reference","Quarantine/follow-up linkage"],featuresAr:["تنظيم الملاحظات","دعم القرار الآمن","ربط مع Visual Tank Insight"],featuresEn:["Structured observations","Safer decision support","Visual Tank Insight linkage"]},
 timeline:{titleAr:"الخط الزمني",titleEn:"Timeline",summaryAr:"سجل موحد لكل ما حدث بالحوض حتى يمكن فهم التسلسل وربط السبب بالنتيجة.",summaryEn:"A unified history of what happened in the tank to support sequence and cause/effect review.",capabilitiesAr:["تسجيل الأحداث","عرض تاريخي مرتب","ربط مع القراءات والخطط"],capabilitiesEn:["Event logging","Chronological history","Links to readings and plans"],featuresAr:["ذاكرة تشغيلية للحوض","دعم التحليل المحلي","مرجع لأي تغيير سابق"],featuresEn:["Operational tank memory","Local analysis support","Reference for prior changes"]},
 journal:{titleAr:"الصور والسجل",titleEn:"Journal",summaryAr:"ذاكرة بصرية للحوض والكائنات: صور، نمو، ملاحظات وVisual Tank Insight ضمن سياق الحوض وتاريخه.",summaryEn:"The tank's visual memory: photos, growth, observations and Visual Tank Insight interpreted in the current tank and history context.",capabilitiesAr:["صور الحوض والكائنات","Growth Tracker ومقارنات زمنية","تحليل بصري للملاحظات الظاهرة","ربط الصورة بالكائن والأحداث","حفظ النتيجة ضمن سجل الحوض"],capabilitiesEn:["Tank and livestock photos","Growth Tracker and time comparison","Visual observation analysis","Photo-to-livestock/event linkage","Save findings into tank history"],featuresAr:["What I Notice","Possible Meaning","Next Best Check","Confidence Level","استخدام الصورة كدليل إضافي لا كتشخيص قطعي"],featuresEn:["What I Notice","Possible Meaning","Next Best Check","Confidence Level","Images as supporting evidence, not definitive diagnosis"]},
 waterchange:{titleAr:"تغيير الماء",titleEn:"Water Change",summaryAr:"تسجيل تغييرات الماء وربطها بتاريخ الحوض والقراءات اللاحقة.",summaryEn:"Log water changes and connect them to tank history and later readings.",capabilitiesAr:["تسجيل الحجم والنسبة","حفظ التاريخ","ربط مع الأحداث"],capabilitiesEn:["Volume/percentage logging","Date history","Event linkage"],featuresAr:["مرجع للتأثير على الكيمياء","متابعة انتظام التغيير","دعم التحليل الزمني"],featuresEn:["Chemistry-effect reference","Routine tracking","Time-series analysis support"]},
 feeding:{titleAr:"التغذية",titleEn:"Feeding",summaryAr:"سجل التغذية لمتابعة الكمية والتكرار وربطها بالمغذيات والحمل الحيوي.",summaryEn:"Feeding log to track frequency and connect feeding with nutrients and bioload.",capabilitiesAr:["تسجيل الوجبات","متابعة التكرار","ربط مع سياق الحوض"],capabilitiesEn:["Feeding logs","Frequency tracking","Tank-context linkage"],featuresAr:["مفيد لتحليل NO3/PO4","مرجع للحمل الحيوي","ذاكرة غذائية"],featuresEn:["Useful for NO3/PO4 analysis","Bioload reference","Feeding history"]},
 dosing:{titleAr:"الجرعات",titleEn:"Dosing",summaryAr:"تسجيل الجرعات وتتبع تأثيرها مع دعم حسابات ذكية ضمن حدود السلامة.",summaryEn:"Log doses and track their effects with intelligent calculations within safety limits.",capabilitiesAr:["سجل الجرعات","قنوات Doser","متابعة الاستهلاك","خطط متابعة"],capabilitiesEn:["Dose logging","Doser channels","Consumption tracking","Follow-up plans"],featuresAr:["ربط الجرعة بالقراءة اللاحقة","Smart Dosing","تنبؤ الاستهلاك"],featuresEn:["Dose-to-next-reading linkage","Smart Dosing","Consumption prediction"]},
 quarantine:{titleAr:"الحجر",titleEn:"Quarantine",summaryAr:"إدارة حجر الكائنات الجديدة أو المريضة مع سجل الحالة والمتابعة.",summaryEn:"Manage quarantine for new or sick organisms with status and follow-up history.",capabilitiesAr:["حالات حجر نشطة","متابعة الكائن","تسجيل الملاحظات","ربط بالأمراض"],capabilitiesEn:["Active quarantine cases","Organism tracking","Observation logging","Disease linkage"],featuresAr:["فصل المتابعة عن الحوض الرئيسي","سجل زمني","دعم قرارات أكثر أماناً"],featuresEn:["Separate follow-up from display tank","Timeline","Safer decision support"]},
 emergency:{titleAr:"الطوارئ",titleEn:"Emergency",summaryAr:"بروتوكولات منظمة للتعامل مع الحالات الحرجة خطوة بخطوة.",summaryEn:"Structured protocols for handling critical aquarium situations step by step.",capabilitiesAr:["سيناريوهات طوارئ","خطوات مرتبة","متابعة الحالة"],capabilitiesEn:["Emergency scenarios","Ordered steps","Status tracking"],featuresAr:["تقليل القرارات العشوائية","أولوية الإجراءات","سجل للطوارئ"],featuresEn:["Reduce random reactions","Action priority","Emergency history"]},
 rodi:{titleAr:"RO/DI",titleEn:"RO/DI",summaryAr:"متابعة مياه التحضير وحالة نظام RO/DI والميديا المرتبطة به.",summaryEn:"Track preparation water and RO/DI system/media condition.",capabilitiesAr:["سجل ماء RO/DI","متابعة الميديا","ربط مع الصيانة"],capabilitiesEn:["RO/DI water log","Media tracking","Maintenance linkage"],featuresAr:["مؤشر لعمر الميديا","مرجع لجودة ماء المصدر","تنبيهات استبدال"],featuresEn:["Media-life indicator","Source-water reference","Replacement alerts"]},
 expenses:{titleAr:"المصاريف",titleEn:"Expenses",summaryAr:"تسجيل مصاريف الحوض ومعرفة الإنفاق الشهري والتراكمي.",summaryEn:"Track aquarium spending and review monthly and cumulative costs.",capabilitiesAr:["تسجيل المصروف","تصنيف التكاليف","ملخص شهري"],capabilitiesEn:["Expense logging","Cost categories","Monthly summary"],featuresAr:["ميزانية تشغيلية","مرجع للشراء","عرض إجمالي الإنفاق"],featuresEn:["Operating budget","Purchase reference","Total-spend view"]},
 alerts:{titleAr:"التنبيهات",titleEn:"Alerts",summaryAr:"مركز تنبيه موحد يستقبل إشارات الكيمياء والصيانة والمعدات والتوافق وبيانات الأجهزة المستوردة ويعطيها أولوية ومسار متابعة.",summaryEn:"A unified alert center for chemistry, maintenance, equipment, compatibility and imported-device signals with priority and follow-up routing.",capabilitiesAr:["تجميع التنبيهات من كل الوحدات","تمييز Info / Warning / Danger","تنبيهات Controller المستوردة تدخل هنا تلقائياً","الانتقال للصفحة المسؤولة عن السبب","ربط التنبيه بحالة Tank Brain"],capabilitiesEn:["Cross-module alert aggregation","Info / Warning / Danger severity","Imported controller alerts feed this center automatically","Jump to the responsible module","Tank Brain state linkage"],featuresAr:["التنبيه الحرج المستورد قد يرفع الحالة العامة إلى Critical","إقرار مراجعة تنبيهات الأجهزة","منع دفن المشاكل داخل صفحة واحدة"],featuresEn:["Critical imported alerts can raise shared state to Critical","Acknowledge imported device alerts","Prevents problems being buried in one module"]},
 reports:{titleAr:"التقارير",titleEn:"Reports",summaryAr:"تجميع بيانات الحوض وذاكرته ومؤشرات الصحة والتشغيل في مخرجات قابلة للمراجعة والمشاركة.",summaryEn:"Compile tank data, history, health and operations into reviewable and shareable outputs.",capabilitiesAr:["ملخص صحة الحوض","تجميع الكيمياء والصيانة والكائنات والأحداث","مراجعة الاتجاه والتقدم","مخرجات للمشاركة والتوثيق"],capabilitiesEn:["Tank health summary","Chemistry, maintenance, livestock and event consolidation","Trend/progress review","Shareable documentation"],featuresAr:["يعتمد على البيانات الفعلية المسجلة","مرجع لمراجعة الأداء مع الزمن","تكامل مع Tank Journey وTimeline"],featuresEn:["Built from recorded tank evidence","Longitudinal performance review","Tank Journey and Timeline integration"]},
 academy:{titleAr:"Aqua Nexus Academy",titleEn:"Aqua Nexus Academy",summaryAr:"مسار تعليم داخل البرنامج يشرح أساسيات تربية الأحواض، المصطلحات، وعلاقة كل مفهوم بالصفحات الفعلية وبطريقة عمل Tank Brain والذكاء الصناعي.",summaryEn:"An in-product learning path covering aquarium fundamentals, terminology, how each concept maps to real pages, and how Tank Brain and AI use tank evidence.",capabilitiesAr:["12 درس قصير من أساس النظام الحي حتى Tank Brain","قاموس مصطلحات سريع قابل للبحث","تقدم محفوظ على هذا الجهاز","روابط مباشرة من الدرس إلى الصفحة العملية","Advanced للمستخدم الخبير بدون تعقيد الدرس الأساسي"],capabilitiesEn:["12 short lessons from living-system basics through Tank Brain","Searchable quick glossary","Progress saved on this device","Direct lesson-to-feature links","Advanced depth without crowding the core lesson"],featuresAr:["التعليم لا يغير بيانات الحوض أو قراراته","اختصارات Academy تظهر سياقياً بالصفحات","الـWizard يعطي شرحاً سريعاً من نفس المنهج","آخر درس يشرح Input → Validation → Context → Confidence → Risk → Next Action → AI Explanation"],featuresEn:["Learning never changes tank data or decisions","Contextual Academy shortcuts appear on relevant pages","Wizard uses quick lessons from the same curriculum","Final lesson explains Input → Validation → Context → Confidence → Risk → Next Action → AI Explanation"]},
 settings:{titleAr:"الإعدادات",titleEn:"Settings",summaryAr:"إعدادات الحوض والتطبيق والخيارات العامة التي تتحكم بسلوك Aqua Nexus وتجربة الاستخدام.",summaryEn:"Tank and application settings that control Aqua Nexus behavior and the user experience.",capabilitiesAr:["إعدادات الحوض والبروفايل","خيارات العرض واللغة","إدارة فقاعات تعليم الميزات","إخفاء الفقاعات أو تشغيلها حسب ما تعلمته","استعادة كل تعليمات الميزات من الصفر"],capabilitiesEn:["Tank/profile settings","Display and language options","Feature discovery bubble controls","Hide bubbles or show only unlearned features","Restore all feature tips from the beginning"],featuresAr:["Aqua Nexus يتذكر الميزات التي فتحتها على هذا الجهاز","استعادة التعليمات لا تغيّر أي بيانات بالحوض","التخصيص بدون كسر بيانات الحوض"],featuresEn:["Aqua Nexus remembers features opened on this device","Restoring tips does not change tank data","Customization without breaking tank data"]}
};

type HelpSensitivity="info"|"important"|"safety";
const PAGE_HELP_SENSITIVITY:Record<AppPage,HelpSensitivity>={
 dashboard:"info",tanks:"info",equipment:"important",lighting:"important",sump:"important",livestock:"important",
 acclimation:"safety",library:"info",chemistry:"safety",maintenance:"important",inventory:"important",diseases:"safety",
 timeline:"info",journal:"info",waterchange:"important",feeding:"important",dosing:"safety",quarantine:"safety",
 emergency:"safety",rodi:"important",expenses:"info",alerts:"safety",reports:"info",settings:"info",academy:"info"
};

const order=(Object.keys(HELP) as AppPage[]);

function PageHelpBody({page,lang}:{page:AppPage;lang:Language}){
 const h=HELP[page];
 const capabilities=lang==="ar"?h.capabilitiesAr:h.capabilitiesEn;
 const features=lang==="ar"?h.featuresAr:h.featuresEn;
 return <div className="help-page-body">
  <div className="help-hero"><small>{lang==="ar"?"شرح الصفحة":"PAGE GUIDE"}</small><h2>{lang==="ar"?h.titleAr:h.titleEn}</h2><p>{lang==="ar"?h.summaryAr:h.summaryEn}</p></div>
  <div className="help-columns">
   <section><h4>{lang==="ar"?"شو بتقدر تعمل هون؟":"What can you do here?"}</h4>{capabilities.map((x,i)=><div className="help-point" key={i}><i>✓</i><span>{x}</span></div>)}</section>
   <section><h4>{lang==="ar"?"أهم الميزات":"Key features"}</h4>{features.map((x,i)=><div className="help-point" key={i}><i>◆</i><span>{x}</span></div>)}</section>
  </div>
 </div>;
}

export function GlobalHelpButton({lang}:{lang:Language}){
 const [open,setOpen]=useState(false);
 return <>
  <button type="button" className="btn help-global-button" onClick={()=>setOpen(true)} aria-label={lang==="ar"?"تعليمات البرنامج":"Program help"}>? {lang==="ar"?"تعليمات":"Help"}</button>
  <Modal open={open} title={lang==="ar"?"دليل Aqua Nexus":"Aqua Nexus Guide"} onClose={()=>setOpen(false)}>
   <div className="help-overview">
    <div className="help-hero"><small>AQUA NEXUS</small><h2>{lang==="ar"?"كيف تستخدم البرنامج؟":"How to use the platform"}</h2><p>{lang==="ar"?"Aqua Nexus مو مجرد سجل. Tank Brain بيربط الكيمياء والمعدات والكائنات والصيانة والصور والاستيراد الذكي والتاريخ، حتى يعطيك حالة الحوض والخطر والخطوة التالية. كل صفحة إلها زر «؟ تعليمات الصفحة»، والداشبورد بيعرفك دورياً على الميزات الجديدة.":"Aqua Nexus is more than a log. Tank Brain connects chemistry, equipment, livestock, maintenance, photos, Smart Import and history into tank state, risk and next action. Every page has a page-help button, while Dashboard rotates feature discovery tips."}</p></div>
    <div className="help-overview-grid">
     <div><b>{lang==="ar"?"1. أنشئ الحوض":"1. Create the tank"}</b><span>{lang==="ar"?"ابدأ بمعالج الإعداد وحدد الحجم والنوع والمعدات والكيمياء الأساسية.":"Use Smart Setup for dimensions, type, equipment and starting chemistry."}</span></div>
     <div><b>{lang==="ar"?"2. أدخل البيانات بالطريقة الأسهل":"2. Use the easiest data path"}</b><span>{lang==="ar"?"سجّل يدوياً أو استخدم Smart Import للصورة/الملف؛ بعد المراجعة تتوزع البيانات على صفحاتها وتدخل Tank Brain.":"Log manually or use Smart Import for screenshots/exports; reviewed data is routed to its modules and Tank Brain."}</span></div>
     <div><b>{lang==="ar"?"3. راقب الفهم الذكي":"3. Read the intelligence"}</b><span>{lang==="ar"?"تابع Tank State وMood والتوقعات والروابط بين الأحداث والنتائج.":"Follow Tank State, Mood, forecasts and event-to-outcome links."}</span></div>
     <div><b>{lang==="ar"?"4. استكشف الميزات بدون ما تضيع":"4. Discover features without hunting"}</b><span>{lang==="ar"?"فقاعات الداشبورد تتحرك ببطء لمدة 45 ثانية، وتتوقف قليلاً بمنتصف الشاشة لتلحق تقرأها، وبعدها في 35 ثانية هدوء قبل الفقاعة التالية.":"Dashboard bubbles rise slowly for 45 seconds, linger around mid-screen for reading, then leave a 35-second quiet gap before the next tip."}</span></div>
    </div>
    <h4 className="help-modules-title">{lang==="ar"?"وحدات البرنامج":"Program modules"}</h4>
    <div className="help-module-grid">{order.map(key=>{const h=HELP[key];return <div className="help-module-card" key={key}><b>{lang==="ar"?h.titleAr:h.titleEn}</b><span>{lang==="ar"?h.summaryAr:h.summaryEn}</span></div>})}</div>
   </div>
  </Modal>
 </>;
}

export function PageHelpButton({page}:{page:AppPage}){
 const lang=useAquaStore(s=>s.language);
 const [open,setOpen]=useState(false);
 const h=HELP[page];
 return <>
  <button type="button" className={`page-help-button help-${PAGE_HELP_SENSITIVITY[page]}`} data-help-sensitivity={PAGE_HELP_SENSITIVITY[page]} onClick={()=>{if(page==="dashboard")markFeatureLearned("tank-brain");setOpen(true)}} aria-label={lang==="ar"?`تعليمات ${h.titleAr}`:`${h.titleEn} help`} title={lang==="ar"?`تعليمات ${h.titleAr}`:`${h.titleEn} help`}>? <span>{lang==="ar"?"تعليمات الصفحة":"Page help"}</span><i aria-hidden="true">{PAGE_HELP_SENSITIVITY[page]==="safety"?"◆":PAGE_HELP_SENSITIVITY[page]==="important"?"•":""}</i></button>
  <Modal open={open} title={lang==="ar"?`تعليمات • ${h.titleAr}`:`Help • ${h.titleEn}`} onClose={()=>setOpen(false)}><PageHelpBody page={page} lang={lang}/></Modal>
 </>;
}
