"use client";
import {useMemo,useState} from "react";
import type {LivestockItem,Tank} from "@/domain/types";
import {useAquaStore} from "@/store/useAquaStore";
import {PageHeader} from "@/components/ui/PageHeader";
import {bi} from "@/i18n";
import {uid,nowISO} from "@/lib/appUtils";

type Kind="fish"|"coral"|"plant"; type Method="breeding"|"frag"|"cutting"|"division"|"runner";
const visual=(kind:Kind,stage:number)=>kind==="fish"?["🐠","🐠  🐠","🥚","🐟 ･ 🐟 ･ 🐟","🐠"][stage-1]:kind==="coral"?["🪸","✂️ 🪸","🪸˙","🪸✨","🪸"][stage-1]:["🌿","✂️ 🌿","🌱","🌱✨","🌿"][stage-1];
export function BreedingPage({tank}:{tank:Tank}){
 const lang=useAquaStore(s=>s.language),patch=useAquaStore(s=>s.patchTank);
 const [kind,setKind]=useState<Kind>("fish"),[step,setStep]=useState(1),[parentId,setParentId]=useState(""),[method,setMethod]=useState<Method>("breeding"),[name,setName]=useState(""),[qty,setQty]=useState(1),[note,setNote]=useState("");
 const eligible=tank.livestock.filter(x=>x.category===kind);
 const parent=tank.livestock.find(x=>x.id===parentId)??eligible[0];
 const allowed:Method[]=kind==="coral"?["frag"]:kind==="plant"?["cutting","division","runner"]:["breeding"];
 const selectedMethod=allowed.includes(method)?method:allowed[0];
 const offspring=useMemo(()=>tank.livestock.filter(x=>x.parentLivestockId),[tank.livestock]);
 const titles=kind==="fish"?[bi(lang,"اختر الأبوين/الأصل","Choose parent stock"),bi(lang,"حدد عملية التكاثر","Choose breeding event"),bi(lang,"سجل الناتج","Record offspring"),bi(lang,"ابدأ المتابعة","Start follow-up"),bi(lang,"تأكيد الاستقرار","Confirm stability")]:kind==="coral"?[bi(lang,"اختر المستعمرة الأم","Choose parent colony"),bi(lang,"حدد عملية الـ Frag","Choose fragging"),bi(lang,"سجل الفراغ الجديد","Record new frag"),bi(lang,"تابع التعافي والنمو","Track recovery & growth"),bi(lang,"تأكيد الاستقرار","Confirm stability")]:[bi(lang,"اختر النبات الأم","Choose parent plant"),bi(lang,"اختر طريقة التكاثر","Choose propagation method"),bi(lang,"سجل النبات الجديد","Record new plant"),bi(lang,"تابع التجذير والنمو","Track rooting & growth"),bi(lang,"تأكيد الاستقرار","Confirm stability")];
 const guidance=kind==="fish"?[bi(lang,"اختر السمكة أو المجموعة التي ظهر منها سلوك التكاثر أو النسل.","Select the fish or group where breeding behavior or offspring appeared."),bi(lang,"سجل العملية فقط بعد ملاحظة دليل فعلي مثل البيض أو الصغار.","Record breeding only after actual evidence such as eggs or fry."),bi(lang,"سجل عدد الصغار التقريبي وملاحظة البداية.","Record approximate offspring count and starting note."),bi(lang,"راقب التغذية والنمو والبقاء وسجل التغييرات في حياة الكائنات.","Monitor feeding, growth and survival; log changes in Life Journey."),bi(lang,"أكد الاستقرار فقط بعد أن يصبح الناتج مستقراً فعلياً.","Confirm stability only after the offspring is genuinely established.")]:kind==="coral"?[bi(lang,"اختر المستعمرة التي أخذت منها القطعة.","Select the colony the frag came from."),bi(lang,"سجل الـFrag بعد القطع الفعلي؛ Aqua Nexus لا يطلب منك تنفيذ القطع.","Log the frag after the actual cut; Aqua Nexus does not instruct you to perform it."),bi(lang,"سجل عدد القطع وملاحظة عن حالة النسيج بعد العملية.","Record frag count and a note about tissue condition."),bi(lang,"راقب التعافي، فتح البوليب والنمو وسجل الصور في حياة الكائنات.","Watch recovery, polyp extension and growth; add photos in Life Journey."),bi(lang,"أكد الاستقرار بعد التعافي والنمو المستقر.","Confirm once recovery and stable growth are evident.")]:[bi(lang,"اختر النبات الأم الذي أخذت منه الناتج.","Select the source plant."),bi(lang,"اختر قصاصة أو تقسيم أو Runner حسب ما حدث فعلياً.","Choose cutting, division or runner based on what actually occurred."),bi(lang,"سجل العدد والحالة الأولية.","Record quantity and initial condition."),bi(lang,"راقب التجذير والنمو الجديد وأي ذوبان أو تراجع.","Monitor rooting, new growth and any melt or decline."),bi(lang,"أكد الاستقرار عند ظهور نمو جديد مستقر.","Confirm after stable new growth appears.")];
 const switchKind=(k:Kind)=>{setKind(k);setStep(1);setParentId("");setMethod(k==="fish"?"breeding":k==="coral"?"frag":"cutting")};
 const markStable=(id:string)=>{const ts=nowISO();patch(tank.id,t=>({...t,livestock:t.livestock.map(x=>x.id===id?{...x,health:"good",lastObservedAt:ts,lifeEvents:[{id:uid("life"),timestamp:ts,type:"health",note:lang==="ar"?"تم تأكيد استقرار ناتج التكاثر.":"Propagation result confirmed stable."},...(x.lifeEvents??[])]}:x),timeline:[{id:uid("ev"),timestamp:ts,type:"propagation-stable",textAr:"التكاثر • تم تأكيد استقرار الناتج.",textEn:"Propagation • Result confirmed stable."},...t.timeline]}))};
 const add=()=>{if(!parent)return;const ts=nowISO(),id=uid("livestock"),childName=name.trim()||`${parent.name} • ${selectedMethod}`;const child:LivestockItem={id,libraryId:parent.libraryId,name:childName,nameEn:parent.nameEn,category:parent.category,subtype:parent.subtype,quantity:Math.max(1,qty),health:"watch",addedAt:ts,notes:note||undefined,location:parent.location??"display",parentLivestockId:parent.id,propagationMethod:selectedMethod,lifeEvents:[{id:uid("life"),timestamp:ts,type:selectedMethod,note:note||undefined}]};patch(tank.id,t=>({...t,livestock:[...t.livestock,child],timeline:[{id:uid("ev"),timestamp:ts,type:"propagation",textAr:`التكاثر • بدأ تتبع ${childName} من ${parent.name} حتى الاستقرار.`,textEn:`Propagation • Tracking ${childName} from ${parent.nameEn||parent.name} through establishment.`},...t.timeline]}));setName("");setNote("");setStep(4)};
 return <section className="page-grid"><PageHeader eyebrow="PROPAGATION & BREEDING" title={bi(lang,"التكاثر","Propagation & Breeding")}/>
 <section className="card panel full-span"><h3>{bi(lang,"سجل عملية تكاثر جديدة","Record a propagation event")}</h3><p className="note">{bi(lang,"اختر النوع واتبع الخطوات البصرية. الصفحة تسجل ما حدث وتتابع الناتج؛ لا تستبدل الإرشادات المتخصصة لتنفيذ القطع أو التكاثر.","Choose a type and follow the visual steps. This page records what happened and follows the result; it does not replace specialized husbandry guidance.")}</p>
 <div className="choice-row">{([["fish","🐠",bi(lang,"تكاثر الأسماك","Fish breeding")],["coral","🪸",bi(lang,"فروع المرجان","Coral fragging")],["plant","🌿",bi(lang,"تكاثر النباتات","Plant propagation")]] as const).map(([k,icon,label])=><button key={k} className={`btn ${kind===k?"primary":""}`} onClick={()=>switchKind(k)}><span style={{fontSize:24}}>{icon}</span> {label}</button>)}</div>
 <div className="propagation-steps">{titles.map((t,i)=><button key={t} className={`card ${step===i+1?"active":""}`} onClick={()=>setStep(i+1)} className="propagation-step-card" style={{border:step===i+1?"1px solid #28d7ff":undefined}}><div style={{fontSize:30,minHeight:42}}>{visual(kind,i+1)}</div><small>{i+1}</small><div><b>{t}</b></div></button>)}</div></section>
 <section className="card panel full-span"><div className="propagation-stage"><div className="propagation-stage-visual">{visual(kind,step)}</div><div><small>{step}/5</small><h3>{titles[step-1]}</h3><p className="note">{guidance[step-1]}</p>
 {step===1&&<label className="field"><span>{bi(lang,"الكائن الأصل","Parent organism")}</span><select value={parent?.id??""} onChange={e=>setParentId(e.target.value)}><option value="">{bi(lang,"اختر","Choose")}</option>{eligible.map(x=><option key={x.id} value={x.id}>{lang==="ar"?x.name:(x.nameEn||x.name)}</option>)}</select>{!eligible.length&&<small>{bi(lang,"لا يوجد كائن مناسب في قائمة الحوض. أضفه أولاً من حياة الكائنات.","No eligible livestock in this tank. Add it first in Livestock.")}</small>}</label>}
 {step===2&&<label className="field"><span>{bi(lang,"الطريقة","Method")}</span><select value={selectedMethod} onChange={e=>setMethod(e.target.value as Method)}>{allowed.map(x=><option key={x} value={x}>{x==="breeding"?bi(lang,"تكاثر / نسل","Breeding / offspring"):x==="frag"?"Frag":x==="cutting"?bi(lang,"قصاصة","Cutting"):x==="division"?bi(lang,"تقسيم","Division"):bi(lang,"مدادة Runner","Runner")}</option>)}</select></label>}
 {step===3&&<div className="form-grid"><label className="field"><span>{bi(lang,"اسم الناتج (اختياري)","Result name (optional)")}</span><input value={name} onChange={e=>setName(e.target.value)}/></label><label className="field"><span>{bi(lang,"العدد","Quantity")}</span><input type="number" min="1" value={qty} onChange={e=>setQty(Math.max(1,Number(e.target.value)||1))}/></label><label className="field full-field"><span>{bi(lang,"ملاحظة البداية","Starting note")}</span><input value={note} onChange={e=>setNote(e.target.value)}/></label><button className="btn primary" disabled={!parent} onClick={add}>{bi(lang,"سجل الناتج وابدأ المتابعة","Record result & start follow-up")}</button></div>}
 {step===4&&<div className="inline-alert info">{bi(lang,"الناتج يظهر الآن في قائمة المتابعة بالأسفل، وكل قياس أو صورة نمو لاحقة تسجل من حياة الكائنات وتبقى مرتبطة بنفس الكائن.","The result now appears below. Future growth measurements and photos are logged in Life Journey and remain linked to the same organism.")}</div>}
 {step===5&&<div className="inline-alert warn">{bi(lang,"استخدم تأكيد الاستقرار من بطاقة الناتج بالأسفل فقط بعد تحقق مؤشرات الاستقرار الفعلية.","Use Confirm stable on the result card below only after real establishment indicators are present.")}</div>}
 <div className="modal-actions">{step>1&&<button className="btn" onClick={()=>setStep(step-1)}>{bi(lang,"السابق","Back")}</button>}{step<5&&<button className="btn primary" disabled={step===1&&!parent} onClick={()=>setStep(step+1)}>{bi(lang,"التالي","Next")}</button>}</div></div></div></section>
 <section className="card panel full-span"><h3>{bi(lang,"تحت المتابعة","Under follow-up")}</h3>{offspring.length?offspring.map(x=><div className="mini-row" key={x.id}><span><b>{lang==="ar"?x.name:(x.nameEn||x.name)}</b> • {x.propagationMethod} • {bi(lang,"من","from")} {tank.livestock.find(p=>p.id===x.parentLivestockId)?.name??"—"}<br/><small>{x.health==="good"?bi(lang,"اكتملت مرحلة الاستقرار","Establishment complete"):bi(lang,"سجل صور وقياسات النمو من حياة الكائنات","Log growth photos and measurements in Life Journey")}</small></span><span><b>{x.health==="good"?bi(lang,"مستقر","Stable"):bi(lang,"تحت المراقبة","Monitoring")}</b>{x.health!=="good"&&<button className="btn" style={{marginInlineStart:8}} onClick={()=>markStable(x.id)}>{bi(lang,"تأكيد الاستقرار","Confirm stable")}</button>}</span></div>):<p className="note">{bi(lang,"لا توجد عمليات قيد المتابعة بعد.","No propagation is being tracked yet.")}</p>}</section><style jsx>{`\n .propagation-steps{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:8px;margin-top:16px;width:100%}\n .propagation-step-card{min-width:0;padding:10px;overflow:hidden}\n .propagation-stage{display:grid;grid-template-columns:minmax(120px,220px) minmax(0,1fr);gap:18px;align-items:center}\n .propagation-stage-visual{font-size:64px;text-align:center;padding:20px;border-radius:16px;background:rgba(20,190,220,.07)}\n @media(max-width:700px){.propagation-steps{grid-template-columns:repeat(5,minmax(76px,1fr));gap:5px;overflow-x:auto;padding-bottom:4px}.propagation-step-card{padding:8px 4px;font-size:12px}.propagation-step-card div:first-child{font-size:24px!important;min-height:34px!important}.propagation-stage{grid-template-columns:1fr;gap:10px}.propagation-stage-visual{font-size:52px;padding:12px}.choice-row{flex-wrap:wrap}.choice-row .btn{flex:1 1 30%;min-width:105px}}\n @media(max-width:430px){.propagation-steps{grid-template-columns:repeat(5,82px)}.propagation-step-card{font-size:11px}}\n `}</style></section>;
}