"use client";
import {useMemo,useState} from "react";
import type {LivestockItem,Tank} from "@/domain/types";
import {useAquaStore} from "@/store/useAquaStore";
import {PageHeader} from "@/components/ui/PageHeader";
import {bi} from "@/i18n";
import {uid,nowISO} from "@/lib/appUtils";

type Kind="fish"|"coral"|"plant"; type Method="breeding"|"frag"|"cutting"|"division"|"runner";
const visual=(kind:Kind,stage:number)=>{
 const common={viewBox:"0 0 240 150",width:"100%",height:"100%","aria-hidden":true};
 const water=<><path d="M10 128h220" stroke="currentColor" opacity=".18"/><path d="M15 116c28-8 48 8 76 0s49 8 78 0 40 4 56 0" fill="none" stroke="currentColor" opacity=".12"/></>;
 const fish=(x:number,y:number,s=1)=><g transform={`translate(${x} ${y}) scale(${s})`}><ellipse cx="0" cy="0" rx="25" ry="14" fill="currentColor" opacity=".2"/><path d="M-24 0-42-15v30Z" fill="currentColor" opacity=".35"/><circle cx="13" cy="-4" r="2.7" fill="currentColor"/><path d="M-7-12c4 7 4 17 0 24M3-13c4 8 4 18 0 26" stroke="currentColor" strokeWidth="3" opacity=".7"/></g>;
 const coral=<g transform="translate(120 92)"><path d="M0 35V-12m0 15-28-28m28 12 28-30M-18-15l-3-24M17-31l7-22M0 8 34-16" fill="none" stroke="currentColor" strokeWidth="9" strokeLinecap="round"/><path d="M-42 35h84" stroke="currentColor" strokeWidth="8" opacity=".25"/></g>;
 const plant=<g transform="translate(120 120)" fill="none" stroke="currentColor" strokeWidth="6" strokeLinecap="round"><path d="M0 10V-76"/><path d="M0-55c-20-18-35-10-38-7 10 20 27 21 38 7ZM0-30c20-18 35-10 38-7-10 20-27 21-38 7ZM0-5c-19-16-32-8-35-5 9 18 25 18 35 5Z" fill="currentColor" opacity=".18"/></g>;
 if(kind==="fish"){if(stage===1)return <svg {...common}>{water}{fish(82,76)}{fish(158,76,-.9)}</svg>;if(stage===2)return <svg {...common}>{water}{fish(80,65)}<path d="M115 90q20-24 40 0" fill="none" stroke="currentColor" strokeDasharray="5 5"/><g fill="currentColor">{[0,1,2,3,4].map(i=><circle key={i} cx={142+i*8} cy={104+(i%2)*5} r="4" opacity=".55"/>)}</g></svg>;if(stage===3)return <svg {...common}>{water}<g fill="currentColor">{Array.from({length:10},(_,i)=><circle key={i} cx={70+(i%5)*24} cy={62+Math.floor(i/5)*25} r="8" opacity=".25"/>)}</g><path d="M65 120c30-20 80-20 110 0" fill="none" stroke="currentColor" opacity=".25"/></svg>;if(stage===4)return <svg {...common}>{water}{fish(62,65,.5)}{fish(120,92,.45)}{fish(178,60,.55)}<g fill="currentColor">{[0,1,2,3].map(i=><circle key={i} cx={100+i*13} cy={35+i%2*8} r="2"/>)}</g></svg>;return <svg {...common}>{water}{fish(120,74,1.35)}<path d="m185 35 9 9 18-22" fill="none" stroke="currentColor" strokeWidth="6"/></svg>}
 if(kind==="coral"){if(stage===1)return <svg {...common}>{water}{coral}</svg>;if(stage===2)return <svg {...common}>{coral}<path d="M148 46 115 78" stroke="#ffbd5c" strokeWidth="4" strokeDasharray="6 4"/><g transform="translate(165 37) rotate(-38)" stroke="currentColor" strokeWidth="5"><path d="M-20 0h40M0-20v40"/><circle r="7" fill="none"/></g></svg>;if(stage===3)return <svg {...common}><path d="M82 124h76l-12-18H94Z" fill="currentColor" opacity=".18"/><g transform="translate(120 91) scale(.7)">{coral}</g><path d="M102 111h36" stroke="currentColor" strokeWidth="7"/></svg>;if(stage===4)return <svg {...common}>{water}{coral}<path d="M188 42c14 18 14 34 0 49-14-15-14-31 0-49Z" fill="currentColor" opacity=".12"/></svg>;return <svg {...common}>{water}{coral}<path d="m184 32 9 9 18-22" fill="none" stroke="currentColor" strokeWidth="6"/></svg>}
 if(stage===1)return <svg {...common}>{water}{plant}</svg>;if(stage===2)return <svg {...common}>{plant}<path d="M82 72h76" stroke="#ffbd5c" strokeWidth="4" strokeDasharray="6 4"/><path d="m162 62 14 10-14 10" fill="none" stroke="currentColor" strokeWidth="5"/></svg>;if(stage===3)return <svg {...common}>{water}<g transform="translate(120 130) scale(.7)">{plant}</g><path d="M88 128h64" stroke="currentColor" strokeWidth="9" opacity=".22"/></svg>;if(stage===4)return <svg {...common}>{water}{plant}<path d="M115 129q-25 12-42 3m52-3q28 14 45 2" fill="none" stroke="currentColor" strokeWidth="3" opacity=".55"/></svg>;return <svg {...common}>{water}{plant}<path d="m184 32 9 9 18-22" fill="none" stroke="currentColor" strokeWidth="6"/></svg>;
};
export function BreedingPage({tank}:{tank:Tank}){
 const lang=useAquaStore(s=>s.language),patch=useAquaStore(s=>s.patchTank); const [showHelp,setShowHelp]=useState(false);
 const [kind,setKind]=useState<Kind>("fish"),[step,setStep]=useState(1),[parentId,setParentId]=useState(""),[method,setMethod]=useState<Method>("breeding"),[name,setName]=useState(""),[qty,setQty]=useState(1),[note,setNote]=useState(""),[resultLocation,setResultLocation]=useState<string>("display");
 const eligible=tank.livestock.filter(x=>x.category===kind);
 const parent=tank.livestock.find(x=>x.id===parentId)??eligible[0];
 const allowed:Method[]=kind==="coral"?["frag"]:kind==="plant"?["cutting","division","runner"]:["breeding"];
 const selectedMethod=allowed.includes(method)?method:allowed[0];
 const offspring=useMemo(()=>tank.livestock.filter(x=>x.parentLivestockId),[tank.livestock]);
 const titles=kind==="fish"?[bi(lang,"اختر مصدر النسل","Choose source stock"),bi(lang,"حدد عملية التكاثر","Choose breeding event"),bi(lang,"سجل الناتج","Record offspring"),bi(lang,"ابدأ المتابعة","Start follow-up"),bi(lang,"تأكيد الاستقرار","Confirm stability")]:kind==="coral"?[bi(lang,"اختر المستعمرة الأم","Choose parent colony"),bi(lang,"حدد عملية الـ Frag","Choose fragging"),bi(lang,"سجل الفراغ الجديد","Record new frag"),bi(lang,"تابع التعافي والنمو","Track recovery & growth"),bi(lang,"تأكيد الاستقرار","Confirm stability")]:[bi(lang,"اختر النبات الأم","Choose parent plant"),bi(lang,"اختر طريقة التكاثر","Choose propagation method"),bi(lang,"سجل النبات الجديد","Record new plant"),bi(lang,"تابع التجذير والنمو","Track rooting & growth"),bi(lang,"تأكيد الاستقرار","Confirm stability")];
 const guidance=kind==="fish"?[bi(lang,"اختر السمكة أو المجموعة التي ظهر منها سلوك التكاثر أو النسل.","Select the fish or group where breeding behavior or offspring appeared."),bi(lang,"سجل العملية فقط بعد ملاحظة دليل فعلي مثل البيض أو الصغار.","Record breeding only after actual evidence such as eggs or fry."),bi(lang,"سجل عدد الصغار التقريبي وملاحظة البداية.","Record approximate offspring count and starting note."),bi(lang,"راقب التغذية والنمو والبقاء وسجل التغييرات في حياة الكائنات.","Monitor feeding, growth and survival; log changes in Life Journey."),bi(lang,"أكد الاستقرار فقط بعد أن يصبح الناتج مستقراً فعلياً.","Confirm stability only after the offspring is genuinely established.")]:kind==="coral"?[bi(lang,"اختر المستعمرة التي أخذت منها القطعة.","Select the colony the frag came from."),bi(lang,"سجل الـFrag بعد القطع الفعلي؛ Aqua Nexus لا يطلب منك تنفيذ القطع.","Log the frag after the actual cut; Aqua Nexus does not instruct you to perform it."),bi(lang,"سجل عدد القطع وملاحظة عن حالة النسيج بعد العملية.","Record frag count and a note about tissue condition."),bi(lang,"راقب التعافي، فتح البوليب والنمو وسجل الصور في حياة الكائنات.","Watch recovery, polyp extension and growth; add photos in Life Journey."),bi(lang,"أكد الاستقرار بعد التعافي والنمو المستقر.","Confirm once recovery and stable growth are evident.")]:[bi(lang,"اختر النبات الأم الذي أخذت منه الناتج.","Select the source plant."),bi(lang,"اختر قصاصة أو تقسيم أو Runner حسب ما حدث فعلياً.","Choose cutting, division or runner based on what actually occurred."),bi(lang,"سجل العدد والحالة الأولية.","Record quantity and initial condition."),bi(lang,"راقب التجذير والنمو الجديد وأي ذوبان أو تراجع.","Monitor rooting, new growth and any melt or decline."),bi(lang,"أكد الاستقرار عند ظهور نمو جديد مستقر.","Confirm after stable new growth appears.")];
 const instructions=kind==="fish"?[
  [bi(lang,"راقب وجود سلوك تكاثر فعلي أو بيض/صغار قبل التسجيل.","Look for actual breeding behavior, eggs or fry before logging."),bi(lang,"لا تغيّر ظروف الحوض بسرعة بهدف إجبار التكاثر.","Do not rapidly change tank conditions to force breeding.")],
  [bi(lang,"اختر Breeding/offspring وسجل ما شاهدته فعلياً.","Choose Breeding/offspring and record only what you actually observed."),bi(lang,"إذا لم تعرف الأبوين بدقة، استخدم المجموعة الأصلية ولا تخمّن.","If exact parents are unknown, use the source group rather than guessing.")],
  [bi(lang,"أدخل عدد الصغار التقريبي، ويمكن تحديثه لاحقاً.","Enter the approximate offspring count; it can be updated later."),bi(lang,"دوّن أول تغذية أو ملاحظة مهمة عن السلوك والحالة.","Note first feeding or any important behavior/condition observation.")],
  [bi(lang,"راقب التغذية، البقاء والنمو. أضف قياسات وصوراً من حياة الكائنات.","Monitor feeding, survival and growth. Add measurements and photos from Life Journey."),bi(lang,"أي تراجع بالصحة يبقي الحالة تحت المراقبة ولا تعتبرها مستقرة.","Any health decline keeps the result under monitoring.")],
  [bi(lang,"أكد الاستقرار بعد تغذية منتظمة ونمو وحالة صحية مستقرة.","Confirm stability after regular feeding, growth and stable health."),bi(lang,"التأكيد ينقل الناتج من المتابعة الأولية إلى كائن مستقر.","Confirmation moves the result from establishment monitoring to stable livestock.")]
 ]:kind==="coral"?[
  [bi(lang,"اختر المستعمرة الأم الصحيحة وتأكد أن حالتها مسجلة قبل العملية.","Select the correct parent colony and make sure its condition is recorded."),bi(lang,"الصفحة توثق الـFrag ولا تعطي تعليمات قطع جراحية.","This page documents fragging; it does not provide cutting procedure instructions.")],
  [bi(lang,"اختر Frag فقط بعد تنفيذ العملية فعلياً.","Choose Frag only after the operation has actually occurred."),bi(lang,"سجل أي ملاحظة عن موضع القطع أو حالة النسيج بدون افتراض التشخيص.","Record cut-location or tissue observations without assuming a diagnosis.")],
  [bi(lang,"سجل عدد القطع الناتجة واسمها الاختياري.","Record the number of resulting frags and an optional name."),bi(lang,"يفضل إضافة صورة بداية من حياة الكائنات لتصبح خط أساس للمقارنة.","Add a starting Life Journey photo when possible to establish a comparison baseline.")],
  [bi(lang,"راقب النسيج، فتح البوليب، اللون والتثبيت والنمو مع الوقت.","Monitor tissue, polyp extension, color, attachment and growth over time."),bi(lang,"سجل الصور والقياسات بدل الاعتماد على الذاكرة البصرية.","Log photos and measurements rather than relying on visual memory.")],
  [bi(lang,"أكد الاستقرار فقط بعد التعافي وغياب التراجع وظهور نمو مستقر.","Confirm only after recovery, no ongoing decline, and stable growth."),bi(lang,"إذا بقيت الحالة غير واضحة اتركها تحت المراقبة.","If condition remains uncertain, keep it under monitoring.")]
 ]:[
  [bi(lang,"اختر النبات الأم الصحيح وسجل حالته الحالية.","Select the correct parent plant and record its current condition."),bi(lang,"استخدم الطريقة التي حدثت فعلياً: قصاصة أو تقسيم أو Runner.","Use the method that actually occurred: cutting, division or runner.")],
  [bi(lang,"اختر طريقة التكاثر المطابقة لما نفذته فعلياً.","Choose the propagation method that matches what you actually did."),bi(lang,"لا تعتبر القصاصة نباتاً مستقراً قبل ظهور مؤشرات نمو جديدة.","Do not treat a cutting as established before new-growth indicators appear.")],
  [bi(lang,"سجل العدد والحالة الأولية وأي ملاحظة عن الجذور أو الأوراق.","Record quantity, initial condition, and root/leaf observations."),bi(lang,"أضف صورة بداية لتسهيل مقارنة التجذير والنمو لاحقاً.","Add a baseline photo to compare rooting and growth later.")],
  [bi(lang,"راقب التجذير، الأوراق الجديدة، الذوبان أو توقف النمو.","Monitor rooting, new leaves, melt, or stalled growth."),bi(lang,"سجل تغيرات النمو في حياة الكائنات لتدخل ذاكرة الحوض.","Log growth changes in Life Journey so they enter tank memory.")],
  [bi(lang,"أكد الاستقرار بعد ظهور نمو جديد مستمر وحالة صحية جيدة.","Confirm after sustained new growth and good health."),bi(lang,"إذا ظهر ذوبان أو توقف نمو، استمر بالمراقبة ولا تؤكد الاستقرار.","If melt or stalled growth appears, continue monitoring instead of confirming stability.")]
 ];
 const practical=kind==="fish"?[
  {tools:bi(lang,"حوض/منطقة تكاثر مناسبة، سطح أو مخبأ وضع البيض حسب النوع، إضاءة هادئة.","Suitable breeding area, species-appropriate spawning surface/hide, gentle lighting."),how:bi(lang,"راقب الزوج أو المجموعة: تنظيف مكان، مغازلة، دفاع عن منطقة، ثم ابحث عن البيض. لا تفصل زوجاً عشوائياً فقط لأنهما ذكر وأنثى.","Observe the pair/group for site cleaning, courtship and territory defense, then verify eggs. Do not pair random male/female fish solely by sex.")},
  {tools:bi(lang,"مصباح صغير للمراقبة وسجل/صورة للبيض أو الصغار.","Small observation light and a photo/log of eggs or fry."),how:bi(lang,"وثّق البيض أو الصغار وتاريخ ظهوره. طريقة الحضانة تختلف حسب النوع: بعض الأبوين يرعيان البيض وبعض الأنواع قد تأكله، لذلك لا يعطي البرنامج قرار فصل عام لكل الأسماك.","Document eggs/fry and date seen. Parental care differs by species, so Aqua Nexus does not apply one universal separation rule.")},
  {tools:bi(lang,"غذاء بحجم مناسب للصغار: روتيفر/غذاء دقيق جداً أو Artemia nauplii عندما يناسب حجم الفم والنوع.","Fry-sized food: rotifers/very fine food or Artemia nauplii when appropriate for species and mouth size."),how:bi(lang,"ابدأ بغذاء يناسب حجم فم الصغار. الأرتيميا ممتازة لكثير من الصغار بعد أن يصبح حجمها مناسباً، لكنها ليست أول غذاء صالح لكل الأنواع. سجل نوع الغذاء وعدد مرات التغذية.","Start with food that fits fry mouth size. Artemia is excellent for many fry once size-appropriate, but is not a universal first food. Log food and feeding frequency.")},
  {tools:bi(lang,"اختبارات ماء، شفط لطيف، تغذية صغيرة متكررة حسب النوع.","Water tests, gentle cleanup, small species-appropriate feedings."),how:bi(lang,"راقب البقاء، امتلاء البطن، السباحة والنمو وجودة الماء. تجنب الإفراط بالطعام لأنه يرفع الحمل العضوي بسرعة في أحواض التربية.","Track survival, belly fullness, swimming, growth and water quality. Avoid overfeeding because nursery systems foul quickly.")},
  {tools:bi(lang,"صور وقياسات متتابعة وسجل تغذية.","Sequential photos, measurements and feeding log."),how:bi(lang,"اعتبر الدفعة مستقرة عندما تتغذى بانتظام، تنمو، وتبقى حالتها مستقرة خلال المتابعة؛ بعدها أكد الاستقرار.","Treat the batch as established when it feeds reliably, grows and remains healthy through follow-up; then confirm stability.")}
 ]:kind==="coral"?[
  {tools:bi(lang,"قفازات ونظارات حماية، وعاء ماء من الحوض، أدوات Frag مناسبة لنوع الهيكل، قواعد Frag وغراء/إيبوكسي مناسب.","Gloves and eye protection, tank-water container, structure-appropriate frag tools, frag plugs and suitable reef glue/epoxy."),how:bi(lang,"اختر مستعمرة سليمة ومستقرة. لا تبدأ بمرجان متراجع أو مصاب، وسجل صورة قبل العملية.","Choose a healthy, stable colony. Do not start with a declining/diseased coral; record a before photo.")},
  {tools:bi(lang,"للـSPS قاطع عظمي مناسب؛ للـLPS الهيكلي أداة قطع مناسبة للهيكل؛ الأدوات تختلف حسب نوع المرجان.","For SPS use an appropriate bone cutter; skeletal LPS requires a structure-appropriate cutting tool; tools vary by coral type."),how:bi(lang,"مكان القص ليس قاعدة واحدة: في المرجان المتفرع يكون عادة على فرع سليم مع ترك نسيج حي جيد للقطعة والأم. في LPS يجب احترام حدود الهيكل واللحم وتجنب تمزيق النسيج. إذا كان النوع غير معروف، لا يعرض Aqua Nexus خط قص افتراضياً.","There is no universal cut line: branching coral is generally cut on a healthy branch while preserving viable tissue on frag and parent. For LPS respect skeleton/tissue boundaries and avoid tearing tissue. If species is unknown, Aqua Nexus does not invent a cut line.")},
  {tools:bi(lang,"قاعدة Frag + غراء سيانوأكريلات جل/مادة تثبيت مناسبة، وعاء شطف بماء الحوض.","Frag plug + reef-safe cyanoacrylate gel/suitable mounting material and tank-water rinse container."),how:bi(lang,"ثبت القطعة من الهيكل أو الجزء المناسب بدون تغطية النسيج الحي بالغراء. سجل صورة مباشرة بعد التثبيت كمرجع.","Mount via suitable skeleton/base without smothering living tissue with glue. Record an immediate post-mount photo as baseline.")},
  {tools:bi(lang,"إضاءة وتيار مناسبين للنوع مع صور متابعة.","Species-appropriate light/flow and follow-up photos."),how:bi(lang,"راقب انحسار النسيج، فتح البوليب، اللون وثبات القطعة. لا ترفع الضوء أو التيار فجأة فقط لتسريع التعافي.","Watch tissue recession, polyp extension, color and attachment. Do not abruptly increase light or flow to force recovery.")},
  {tools:bi(lang,"صور مقارنة وقياس نمو إن أمكن.","Comparison photos and growth measurement when practical."),how:bi(lang,"أكد الاستقرار بعد التئام موضع القطع، ثبات النسيج وظهور نمو/امتداد طبيعي، وليس لمجرد مرور عدد أيام ثابت.","Confirm after the cut area heals, tissue remains stable and normal growth/extension appears—not merely after a fixed number of days.")}
 ]:[
  {tools:bi(lang,"مقص نباتات نظيف أو أداة تقسيم مناسبة حسب النبات.","Clean aquascaping scissors or suitable division tool for the plant."),how:bi(lang,"اختر نباتاً أم سليماً وحدد طريقة تكاثره الطبيعية قبل القص أو التقسيم.","Choose a healthy parent and identify its natural propagation method before cutting/dividing.")},
  {tools:bi(lang,"مقص للنباتات الساقية، أو تقسيم جذمور/كتلة للنباتات التي تقبل ذلك.","Scissors for stem plants, or rhizome/clump division only for plants that support it."),how:bi(lang,"النباتات الساقية تقص عادة من ساق سليمة مع عقد، بينما نباتات الجذمور تقسم من جذمور سليم ولكل جزء أوراق/جذور قابلة للحياة. الـRunner يفصل بعد تكوّن نبتة ابنة مناسبة.","Stem plants are generally cut from healthy stems with nodes; rhizome plants are divided through healthy rhizome with viable leaves/roots per section. Runners are separated after a suitable daughter plant forms.")},
  {tools:bi(lang,"ملقط زراعة وتربة/ركيزة مناسبة.","Planting tweezers and appropriate substrate."),how:bi(lang,"ازرع الناتج بالطريقة المناسبة للنوع؛ لا تدفن جذمور النباتات التي يجب أن يبقى جذمورها مكشوفاً.","Plant according to species; do not bury rhizomes that must remain exposed.")},
  {tools:bi(lang,"صور، قياس نمو، ومراقبة تسميد/CO₂ إن كان مستخدماً.","Photos, growth measurement and fertilizer/CO₂ monitoring when used."),how:bi(lang,"راقب الجذور والأوراق الجديدة والذوبان. لا ترفع السماد أو CO₂ تلقائياً لمجرد بطء أول أيام التأقلم.","Watch roots, new leaves and melt. Do not automatically increase fertilizer or CO₂ just because early establishment is slow.")},
  {tools:bi(lang,"صورة مقارنة وسجل نمو.","Comparison photo and growth log."),how:bi(lang,"أكد الاستقرار بعد نمو جديد مستمر وثبات الحالة، ثم يصبح الناتج جزءاً طبيعياً من Livestock.","Confirm after sustained new growth and stable condition; the result then becomes normal Livestock.")}
 ];
 const switchKind=(k:Kind)=>{setKind(k);setStep(1);setParentId("");setMethod(k==="fish"?"breeding":k==="coral"?"frag":"cutting");setResultLocation("display")};
 const markStable=(id:string)=>{const ts=nowISO();patch(tank.id,t=>({...t,livestock:t.livestock.map(x=>x.id===id?{...x,health:"good",lastObservedAt:ts,lifeEvents:[{id:uid("life"),timestamp:ts,type:"health",note:lang==="ar"?"تم تأكيد استقرار ناتج التكاثر.":"Propagation result confirmed stable."},...(x.lifeEvents??[])]}:x),timeline:[{id:uid("ev"),timestamp:ts,type:"propagation-stable",textAr:"التكاثر • تم تأكيد استقرار الناتج.",textEn:"Propagation • Result confirmed stable."},...t.timeline]}))};
 const add=()=>{if(!parent)return;if(!Number.isFinite(qty)||qty<1){window.alert(bi(lang,"العدد يجب أن يكون 1 أو أكثر.","Quantity must be 1 or greater."));return;}const ts=nowISO(),id=uid("livestock"),childName=name.trim()||`${parent.name} • ${selectedMethod}`;const child:LivestockItem={id,libraryId:parent.libraryId,name:childName,nameEn:parent.nameEn,category:parent.category,subtype:parent.subtype,quantity:Math.round(qty),health:"watch",addedAt:ts,notes:note||undefined,location:resultLocation as LivestockItem["location"],parentLivestockId:parent.id,propagationMethod:selectedMethod,lifeEvents:[{id:uid("life"),timestamp:ts,type:selectedMethod,note:note||undefined}]};patch(tank.id,t=>({...t,livestock:[...t.livestock,child],timeline:[{id:uid("ev"),timestamp:ts,type:"propagation",textAr:`التكاثر • بدأ تتبع ${childName} من ${parent.name} حتى الاستقرار.`,textEn:`Propagation • Tracking ${childName} from ${parent.nameEn||parent.name} through establishment.`},...t.timeline]}));setName("");setNote("");setStep(4)};
 return <section className="page-grid"><PageHeader eyebrow="PROPAGATION & BREEDING" title={bi(lang,"التكاثر","Propagation & Breeding")} actions={<button className="btn" aria-label={bi(lang,"التعليمات","Instructions")} title={bi(lang,"التعليمات","Instructions")} onClick={()=>setShowHelp(v=>!v)}>?</button>}/>{showHelp&&<section className="card panel full-span"><h3>{bi(lang,"كيف تستخدم صفحة التكاثر؟","How to use Propagation & Breeding")}</h3><p className="note">{bi(lang,"اختر أسماك أو مرجان أو نبات، ثم امشِ على المراحل الخمس. كل مرحلة تعرض التطبيق العملي وما تحتاجه. سجّل الناتج فقط بعد حدوثه فعلياً، وبعدها تابع نموه وصحته من حياة الكائنات. تأكيد الاستقرار يعني أن الناتج أصبح مستقراً فعلاً، وليس مجرد مرور مدة زمنية.","Choose fish, coral or plants, then follow the five stages. Each stage shows practical guidance and what you need. Record a result only after it actually occurs, then follow its growth and health in Life Journey. Confirm stability only when the result is genuinely established, not simply after a fixed number of days.")}</p></section>}
 <section className="card panel full-span"><h3>{bi(lang,"سجل عملية تكاثر جديدة","Record a propagation event")}</h3><p className="note">{bi(lang,"اختر النوع واتبع الخطوات البصرية. الصفحة تسجل ما حدث وتتابع الناتج؛ لا تستبدل الإرشادات المتخصصة لتنفيذ القطع أو التكاثر.","Choose a type and follow the visual steps. This page records what happened and follows the result; it does not replace specialized husbandry guidance.")}</p>
 <div className="choice-row">{([["fish","🐠",bi(lang,"تكاثر الأسماك","Fish breeding")],["coral","🪸",bi(lang,"فروع المرجان","Coral fragging")],["plant","🌿",bi(lang,"تكاثر النباتات","Plant propagation")]] as const).map(([k,icon,label])=><button key={k} className={`btn ${kind===k?"primary":""}`} onClick={()=>switchKind(k)}><span style={{fontSize:24}}>{icon}</span> {label}</button>)}</div>
 <div className="propagation-steps">{titles.map((t,i)=><button key={t} className={`card propagation-step-card ${step===i+1?"active":""}`} onClick={()=>setStep(i+1)} style={{border:step===i+1?"1px solid #28d7ff":undefined}}><div className="propagation-step-visual">{visual(kind,i+1)}</div><small>{i+1}</small><div><b>{t}</b></div></button>)}</div></section>
 <section className="card panel full-span"><div className="propagation-stage"><div className="propagation-stage-visual">{visual(kind,step)}</div><div><small>{step}/5</small><h3>{titles[step-1]}</h3><p className="note">{guidance[step-1]}</p><div className="propagation-instructions"><b>{bi(lang,"شو تعمل بهالمرحلة؟","What to do at this stage")}</b>{instructions[step-1].map((x,i)=><div className="propagation-instruction" key={i}><span>{i+1}</span><p>{x}</p></div>)}</div><div className="propagation-practical"><b>{bi(lang,"التطبيق العملي","Practical guide")}</b><div className="practical-row"><strong>{bi(lang,"شو بتحتاج","What you need")}</strong><p>{practical[step-1].tools}</p></div><div className="practical-row"><strong>{bi(lang,"كيف تعملها","How to do it")}</strong><p>{practical[step-1].how}</p></div></div>
 {step===1&&<label className="field"><span>{bi(lang,"المصدر المسجل","Recorded source")}</span><select value={parent?.id??""} onChange={e=>setParentId(e.target.value)}><option value="">{bi(lang,"اختر","Choose")}</option>{eligible.map(x=><option key={x.id} value={x.id}>{lang==="ar"?x.name:(x.nameEn||x.name)}</option>)}</select>{!eligible.length&&<small>{bi(lang,"لا يوجد كائن مناسب في قائمة الحوض. أضفه أولاً من حياة الكائنات.","No eligible livestock in this tank. Add it first in Livestock.")}</small>}</label>}
 {step===2&&<label className="field"><span>{bi(lang,"الطريقة","Method")}</span><select value={selectedMethod} onChange={e=>setMethod(e.target.value as Method)}>{allowed.map(x=><option key={x} value={x}>{x==="breeding"?bi(lang,"تكاثر / نسل","Breeding / offspring"):x==="frag"?"Frag":x==="cutting"?bi(lang,"قصاصة","Cutting"):x==="division"?bi(lang,"تقسيم","Division"):bi(lang,"مدادة Runner","Runner")}</option>)}</select></label>}
 {step===3&&<div className="form-grid"><label className="field"><span>{bi(lang,"اسم الناتج (اختياري)","Result name (optional)")}</span><input value={name} onChange={e=>setName(e.target.value)}/></label><label className="field"><span>{bi(lang,"العدد","Quantity")}</span><input type="number" min="1" value={qty} onChange={e=>setQty(Number(e.target.value))}/></label><label className="field full-field"><span>{bi(lang,"ملاحظة البداية","Starting note")}</span><input value={note} onChange={e=>setNote(e.target.value)}/></label><label className="field"><span>{bi(lang,"مكان الناتج","Result location")}</span><select value={resultLocation} onChange={e=>setResultLocation(e.target.value)}><option value="display">{bi(lang,"الحوض الرئيسي","Display tank")}</option><option value="external">{bi(lang,"خارجي / حضانة منفصلة","External / separate nursery")}</option>{tank.sump.chambers.map(ch=><option key={ch.id} value={`sump:${ch.id}`}>{bi(lang,"سامب","Sump")} • {lang==="ar"?ch.name:(ch.nameEn||ch.name)}</option>)}</select></label><button className="btn primary" disabled={!parent} onClick={add}>{bi(lang,"سجل الناتج وابدأ المتابعة","Record result & start follow-up")}</button></div>}
 {step===4&&<div className="inline-alert info">{bi(lang,"الناتج يظهر الآن في قائمة المتابعة بالأسفل، وكل قياس أو صورة نمو لاحقة تسجل من حياة الكائنات وتبقى مرتبطة بنفس الكائن.","The result now appears below. Future growth measurements and photos are logged in Life Journey and remain linked to the same organism.")}</div>}
 {step===5&&<div className="inline-alert warn">{bi(lang,"استخدم تأكيد الاستقرار من بطاقة الناتج بالأسفل فقط بعد تحقق مؤشرات الاستقرار الفعلية.","Use Confirm stable on the result card below only after real establishment indicators are present.")}</div>}
 <div className="modal-actions">{step>1&&<button className="btn" onClick={()=>setStep(step-1)}>{bi(lang,"السابق","Back")}</button>}{step<5&&<button className="btn primary" disabled={step===1&&!parent} onClick={()=>setStep(step+1)}>{bi(lang,"التالي","Next")}</button>}</div></div></div></section>
 <section className="card panel full-span"><h3>{bi(lang,"تحت المتابعة","Under follow-up")}</h3>{offspring.length?offspring.map(x=><div className="mini-row" key={x.id}><span><b>{lang==="ar"?x.name:(x.nameEn||x.name)}</b> • {x.propagationMethod} • {bi(lang,"من","from")} {tank.livestock.find(p=>p.id===x.parentLivestockId)?.name??"—"}<br/><small>{x.health==="good"?bi(lang,"اكتملت مرحلة الاستقرار","Establishment complete"):bi(lang,"سجل صور وقياسات النمو من حياة الكائنات","Log growth photos and measurements in Life Journey")}</small></span><span><b>{x.health==="good"?bi(lang,"مستقر","Stable"):bi(lang,"تحت المراقبة","Monitoring")}</b>{x.health!=="good"&&<button className="btn" style={{marginInlineStart:8}} onClick={()=>markStable(x.id)}>{bi(lang,"تأكيد الاستقرار","Confirm stable")}</button>}</span></div>):<p className="note">{bi(lang,"لا توجد عمليات قيد المتابعة بعد.","No propagation is being tracked yet.")}</p>}</section><style jsx>{`\n .propagation-steps{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:8px;margin-top:16px;width:100%}\n .propagation-step-card{min-width:0;padding:10px;overflow:hidden}
 .propagation-step-visual{height:64px;color:#67e8ff}.propagation-step-visual svg{display:block}\n .propagation-stage{display:grid;grid-template-columns:minmax(120px,220px) minmax(0,1fr);gap:18px;align-items:center}\n .propagation-stage-visual{height:180px;color:#67e8ff;text-align:center;padding:12px;border-radius:16px;background:rgba(20,190,220,.07)}.propagation-stage-visual svg{display:block}
 .propagation-instructions{margin:12px 0;padding:12px;border:1px solid rgba(40,215,255,.18);border-radius:14px;background:rgba(40,215,255,.045)}
 .propagation-instruction{display:flex;gap:10px;align-items:flex-start;margin-top:9px}.propagation-instruction span{display:grid;place-items:center;flex:0 0 24px;height:24px;border-radius:50%;background:rgba(40,215,255,.16);color:#66e7ff;font-weight:800}.propagation-instruction p{margin:1px 0 0;line-height:1.55}
 .propagation-practical{margin:12px 0;padding:12px;border:1px solid rgba(77,235,171,.2);border-radius:14px;background:rgba(77,235,171,.045)}.practical-row{margin-top:10px}.practical-row strong{display:block;color:#7df0c2;margin-bottom:3px}.practical-row p{margin:0;line-height:1.6}\n @media(max-width:700px){.propagation-steps{grid-template-columns:repeat(5,minmax(76px,1fr));gap:5px;overflow-x:auto;padding-bottom:4px}.propagation-step-card{padding:8px 4px;font-size:12px}.propagation-step-card .propagation-step-visual{height:48px}.propagation-stage{grid-template-columns:1fr;gap:10px}.propagation-stage-visual{height:150px;padding:8px}.choice-row{flex-wrap:wrap}.choice-row .btn{flex:1 1 30%;min-width:105px}}\n @media(max-width:430px){.propagation-steps{grid-template-columns:repeat(5,82px)}.propagation-step-card{font-size:11px}}\n `}</style></section>;
}