"use client";
import { useMemo,useState } from "react";
import { ResponsiveContainer,LineChart,Line,XAxis,YAxis,Tooltip,CartesianGrid,ReferenceArea } from "recharts";
import type { ChemistryReading,MaintenanceTask,Tank } from "@/domain/types";
import { chemistryCatalogForTank,profileLabel,resolvedAquariumProfile } from "@/domain/chemistryProfile";
import { chemistryHealthAssessment,parameterScore } from "@/domain/health";
import { chemistryGuidance } from "@/domain/chemistryGuidance";
import { findNearDuplicateChemistryReading,isExactChemistryDuplicate,latestParameterSamples,validateChemistryValue,weeklyChemistryCoverage } from "@/domain/chemistryDataQuality";
import { completeMaintenanceTask } from "@/domain/maintenanceSchedule";
import { useAquaStore } from "@/store/useAquaStore";
import { tr,bi } from "@/i18n";
import { Modal } from "@/components/ui/Modal";
import { PageHeader } from "@/components/ui/PageHeader";
import { nowISO,uid } from "@/lib/appUtils";
import { buildDelimitedText,downloadDelimitedFile,field,numberField,parseDelimitedText } from "@/lib/tabularImport";

function today(){return new Date().toISOString().slice(0,10);}
function isWeeklyChemistryTask(m:MaintenanceTask){return /قياس النسب الكيميائية|Weekly chemistry/i.test(`${m.title} ${m.titleEn||""}`);}

export function ChemistryPage({tank}:{tank:Tank}) {
 const lang=useAquaStore(s=>s.language),patch=useAquaStore(s=>s.patchTank),cfg:any=chemistryCatalogForTank(tank);
 const profile=resolvedAquariumProfile(tank),keys=Object.keys(cfg),samples=useMemo(()=>latestParameterSamples(tank),[tank]);
 const [selected,setSelected]=useState(keys[0]),[open,setOpen]=useState(false),[values,setValues]=useState<Record<string,string>>(()=>Object.fromEntries(keys.map(k=>[k,""])));
 const [notes,setNotes]=useState(""),[testKit,setTestKit]=useState(""),[confidence,setConfidence]=useState<"high"|"medium"|"low">("high"),[importNote,setImportNote]=useState(""),[formNote,setFormNote]=useState("");
 const guidance=useMemo(()=>chemistryGuidance(tank),[tank]),assessment=useMemo(()=>chemistryHealthAssessment(tank),[tank]),weekly=useMemo(()=>weeklyChemistryCoverage(tank),[tank]);
 const chart=useMemo(()=>tank.chemistry.map(r=>({timestamp:new Date(r.timestamp).getTime(),date:new Date(r.timestamp).toLocaleDateString(),value:r.values[selected]})).filter(x=>typeof x.value==="number"&&Number.isFinite(x.value as number)).sort((a,b)=>a.timestamp-b.timestamp).slice(-30),[tank.chemistry,selected]);
 const topProblems=guidance.problems.slice(0,6),actionItems=topProblems.slice(0,5),selectedMeta:any=cfg[selected];

 function openReading(){setValues(Object.fromEntries(keys.map(k=>[k,""])));setNotes("");setTestKit("");setConfidence("high");setFormNote("");setOpen(true);}
 function maybeCompleteWeekly(t:Tank,extra:ChemistryReading[]){const merged={...t,chemistry:[...extra,...t.chemistry]} as Tank;if(!weeklyChemistryCoverage(merged).complete)return t.maintenance;return t.maintenance.map(m=>isWeeklyChemistryTask(m)?completeMaintenanceTask(m,today()):m);}
 function save(){
  const measured:Record<string,number|null>={},issues:string[]=[];
  for(const key of keys){const raw=(values[key]??"").trim();if(!raw)continue;const n=Number(raw);if(!Number.isFinite(n)){issues.push(`${key}: ${bi(lang,"رقم غير صالح","invalid number")}`);continue;}const issue=validateChemistryValue(tank,key,n);if(issue)issues.push(lang==="ar"?issue.ar:issue.en);else measured[key]=n;}
  if(issues.length){setFormNote(issues.join(" • "));return;}
  if(!Object.keys(measured).length){setFormNote(bi(lang,"أدخل فقط القيم التي قستها فعلياً، ولازم يكون في قراءة واحدة على الأقل.","Enter only values you actually measured; at least one measurement is required."));return;}
  const duplicate=findNearDuplicateChemistryReading(tank,measured,10);
  if(duplicate&&!window.confirm(bi(lang,"نفس مجموعة القيم مسجلة تقريباً خلال آخر 10 دقائق. إذا هاي إعادة قياس فعلية اضغط متابعة؛ إذا كبسة مكررة اختار إلغاء.","The same set of values was already logged within about 10 minutes. Continue only if this is a real retest; cancel if it was an accidental duplicate.")))return;
  const reading:ChemistryReading={timestamp:nowISO(),values:measured,notes:notes||undefined,source:"manual",testKit:testKit.trim()||undefined,confidence};
  patch(tank.id,t=>({...t,chemistry:[reading,...t.chemistry],maintenance:maybeCompleteWeekly(t,[reading]),timeline:[{id:uid("ev"),timestamp:reading.timestamp,type:"chemistry",textAr:`تم تسجيل قياسات فعلية: ${Object.keys(measured).join("، ")}.`,textEn:`Recorded measured chemistry values: ${Object.keys(measured).join(", ")}.`},...t.timeline]}));
  setOpen(false);
 }
 function downloadTemplate(kind:"csv"|"txt"){const headers=["timestamp",...keys,"testKit","confidence","notes"],example:Record<string,unknown>={timestamp:new Date().toISOString(),testKit:"",confidence:"high",notes:""};keys.forEach(k=>example[k]="");const delimiter=kind==="txt"?"\t":",";downloadDelimitedFile(`Aqua_Nexus_${tank.type}_Chemistry_Template.${kind}`,buildDelimitedText(headers,[example],delimiter),kind==="txt"?"text/plain;charset=utf-8":"text/csv;charset=utf-8");}
 async function importReadings(file?:File){
  if(!file)return;
  try{
   const {rows}=parseDelimitedText(await file.text()),readings:ChemistryReading[]=[],rejected:string[]=[];
   rows.forEach((row,rowIndex)=>{const vals:Record<string,number|null>={},rowErrors:string[]=[];let hasValue=false;for(const key of keys){const raw=field(row,key).trim();if(!raw)continue;const n=numberField(row,key);if(n===null){rowErrors.push(`${key}: ${bi(lang,"ليس رقماً","not a number")}`);continue;}const issue=validateChemistryValue(tank,key,n);if(issue)rowErrors.push(lang==="ar"?issue.ar:issue.en);else{vals[key]=n;hasValue=true;}}const rawTimestamp=field(row,"timestamp").trim(),parsed=rawTimestamp?new Date(rawTimestamp):new Date();if(rawTimestamp&&Number.isNaN(parsed.getTime()))rowErrors.push(bi(lang,"timestamp غير صالح","invalid timestamp"));if(rowErrors.length){rejected.push(`#${rowIndex+2}: ${rowErrors.join("; ")}`);return;}if(!hasValue)return;const candidate:ChemistryReading={timestamp:parsed.toISOString(),values:vals,notes:field(row,"notes")||undefined,source:"import",testKit:field(row,"testKit")||undefined,confidence:(["high","medium","low"].includes(field(row,"confidence").toLowerCase())?field(row,"confidence").toLowerCase():"medium") as "high"|"medium"|"low",usingDefaults:false};if(isExactChemistryDuplicate([...tank.chemistry,...readings],candidate)){rejected.push(`#${rowIndex+2}: ${bi(lang,"قراءة مكررة","duplicate reading")}`);return;}readings.push(candidate);});
   if(!readings.length){setImportNote(bi(lang,`لم يتم استيراد أي قراءة صالحة.${rejected.length?` مرفوض: ${rejected.slice(0,3).join(" | ")}`:""}`,`No valid readings were imported.${rejected.length?` Rejected: ${rejected.slice(0,3).join(" | ")}`:""}`));return;}
   readings.sort((a,b)=>new Date(b.timestamp).getTime()-new Date(a.timestamp).getTime());
   patch(tank.id,t=>{const merged=[...readings,...t.chemistry].sort((a,b)=>new Date(b.timestamp).getTime()-new Date(a.timestamp).getTime());const draft={...t,chemistry:merged} as Tank;return {...t,chemistry:merged,maintenance:weeklyChemistryCoverage(draft).complete?t.maintenance.map(m=>isWeeklyChemistryTask(m)?completeMaintenanceTask(m,today()):m):t.maintenance,timeline:[{id:uid("ev"),timestamp:nowISO(),type:"chemistry-import",textAr:`تم استيراد ${readings.length} قراءة فعلية؛ رُفض ${rejected.length} صف.`,textEn:`Imported ${readings.length} measured reading(s); ${rejected.length} row(s) rejected.`},...t.timeline]};});
   setImportNote(bi(lang,`تم استيراد ${readings.length} قراءة. الصفوف المرفوضة: ${rejected.length}.${rejected.length?` أول سبب: ${rejected[0]}`:""}`,`Imported ${readings.length} reading(s). Rejected rows: ${rejected.length}.${rejected.length?` First reason: ${rejected[0]}`:""}`));
  }catch{setImportNote(bi(lang,"تعذر قراءة الملف. استخدم قالب Aqua Nexus بصيغة CSV أو TXT.","Could not read the file. Use the Aqua Nexus CSV or TXT template."));}
 }
 const healthText=assessment.score===null?"—":`${assessment.score}%`,healthBand=assessment.score===null?bi(lang,"غير معروف","Unknown"):assessment.critical?bi(lang,"حرج","Critical"):assessment.score>=80?bi(lang,"جيدة","Good"):assessment.score>=60?bi(lang,"تحتاج انتباه","Needs attention"):bi(lang,"تحتاج تدخل","Needs action"),healthClass=assessment.score===null?"warn":assessment.critical?"danger":assessment.score>=80?"good":assessment.score>=60?"warn":"danger";

 return <section className="page-grid"><PageHeader eyebrow="WATER CHEMISTRY" title={tr(lang,"chemistry")} actions={<div className="actions"><button className="btn" onClick={()=>downloadTemplate("csv")}>↓ Excel / CSV</button><button className="btn" onClick={()=>downloadTemplate("txt")}>↓ TXT</button><label className="btn">↑ {bi(lang,"استيراد ملف","Import file")}<input type="file" accept=".csv,.txt,text/csv,text/plain" hidden onChange={e=>{importReadings(e.target.files?.[0]);e.currentTarget.value="";}}/></label><button className="btn primary" onClick={openReading}>+ {tr(lang,"addReading")}</button></div>}/>
 {importNote&&<div className="inline-alert info full-span">{importNote}</div>}
 {assessment.score===null&&<div className="inline-alert info full-span"><b>🧪 {bi(lang,"ابدأ من هون: سجّل أول قياس حقيقي للحوض.","Start here: log your first real tank test.")}</b><p>{bi(lang,"مو مطلوب تعبي كل القيم. سجّل فقط الاختبارات يلي عملتها فعلياً، واترك الباقي فارغ. بعد الحفظ Aqua Nexus بيشرحلك شو طبيعي وشو يحتاج انتباه.","You do not need to fill every value. Enter only tests you actually performed and leave the rest blank. After saving, Aqua Nexus will explain what is normal and what needs attention.")}</p><button className="btn primary" onClick={openReading}>+ {tr(lang,"addReading")}</button></div>}

 <div className="card panel chemistry-health-summary"><div className="chemistry-health-head"><div><h3>{tr(lang,"chemistryHealth")}</h3><b className="big-number">{healthText}</b></div><span className={`chemistry-health-band ${healthClass}`}>{healthBand}</span></div><p className="note">{lang==="ar"?guidance.headlineAr:guidance.headlineEn}</p><div className="summary-strip"><div className="summary"><small>{bi(lang,"ثقة البيانات","Data confidence")}</small><b>{assessment.dataConfidence}%</b></div><div className="summary"><small>{bi(lang,"تغطية القياسات","Measurement coverage")}</small><b>{assessment.coverage}%</b></div><div className="summary"><small>{bi(lang,"حداثة البيانات","Freshness")}</small><b>{assessment.freshness}%</b></div><div className="summary"><small>{bi(lang,"بروفايل الأهداف","Target profile")}</small><b>{profileLabel(profile,lang)}</b></div></div>{assessment.critical&&<div className="inline-alert danger">⚠ {bi(lang,`يوجد عامل/عوامل خارج المجال الآمن: ${assessment.criticalKeys.join("، ")}. هذه الحالة حرجة بغض النظر عن المتوسط.`,`Parameter(s) outside the safe range: ${assessment.criticalKeys.join(", ")}. This is critical regardless of the average.`)}</div>}<div className={`inline-alert ${weekly.complete?"good":"info"}`}>{weekly.complete?"✓ ":""}{bi(lang,`فحص الأسبوع: ${weekly.measured.length}/${weekly.required.length} من المجموعة المطلوبة. ${weekly.complete?"مكتمل.":`ناقص: ${weekly.missing.join("، ")}`}`,`Weekly panel: ${weekly.measured.length}/${weekly.required.length} required parameters. ${weekly.complete?"Complete.":`Missing: ${weekly.missing.join(", ")}`}`)}</div></div>
 <div className="card panel"><label className="field"><span>{tr(lang,"parameter")}</span><select value={selected} onChange={e=>setSelected(e.target.value)}>{keys.map(k=><option key={k}>{k}</option>)}</select></label><div className="chart-box"><ResponsiveContainer width="100%" height={230}><LineChart data={chart}><CartesianGrid stroke="#15384a"/><XAxis dataKey="date" tick={{fill:"#7da5b4",fontSize:9}}/><YAxis tick={{fill:"#7da5b4",fontSize:9}}/><Tooltip/>{selectedMeta&&<ReferenceArea y1={selectedMeta.safe[0]} y2={selectedMeta.safe[1]} fill="#42d7e7" fillOpacity={0.06}/>} {selectedMeta&&<ReferenceArea y1={selectedMeta.ideal[0]} y2={selectedMeta.ideal[1]} fill="#62d48f" fillOpacity={0.12}/>}<Line type="monotone" dataKey="value" stroke="#42d7e7" strokeWidth={2} dot={false}/></LineChart></ResponsiveContainer></div><p className="note">{bi(lang,"الخلفية الأوسع = Safe، والمنطقة الأوضح = Ideal.","Wider band = Safe; stronger band = Ideal.")}</p></div>
 {guidance.dataIssues.length>0&&<div className="inline-alert danger full-span chemistry-data-alert"><b>⚠️ {bi(lang,"جودة/حداثة البيانات تحتاج مراجعة","Data quality / freshness needs review")}</b>{guidance.dataIssues.slice(0,8).map(x=><p key={x.key}>{lang==="ar"?x.reasonAr:x.reasonEn}<br/><strong>{lang==="ar"?x.actionAr:x.actionEn}</strong></p>)}</div>}
 <section className="card panel full-span chemistry-guidance"><div className="chemistry-guidance-head"><div><small>AQUA NEXUS CHEMISTRY INTELLIGENCE</small><h2>{bi(lang,"شو وضع الكيمياء فعلياً؟","What is actually happening with chemistry?")}</h2><p className="note">{bi(lang,"الـHealth يصف القيم المقاسة، بينما Data Confidence يصف مدى اكتمال وحداثة وموثوقية القياسات. ما عاد نخلط الاثنين.","Health describes measured values; Data Confidence describes completeness, freshness and trustworthiness. They are intentionally separated.")}</p></div><span>{topProblems.length} {bi(lang,"عامل يحتاج انتباه","need attention")}</span></div>{topProblems.length?<div className="chemistry-issue-grid">{topProblems.map(x=><button type="button" className={`chemistry-issue ${x.level}`} key={x.key} onClick={()=>setSelected(x.key)}><span className="chemistry-issue-score">{x.score===null?"—":x.score+"%"}</span><div><b>{x.titleAr}</b><p>{lang==="ar"?x.reasonAr:x.reasonEn}</p></div><span className="chemistry-issue-arrow">›</span></button>)}</div>:assessment.score===null?<div className="inline-alert info">{bi(lang,"لا توجد قياسات فعلية كافية للحكم على حالة الكيمياء.","There are not enough actual measurements to judge chemistry condition.")}</div>:<div className="inline-alert good">✓ {bi(lang,"القيم المقاسة الحالية لا تحتوي مشكلة كيميائية رئيسية.","The measured values do not currently show a major chemistry problem.")}</div>}</section>
 <section className="card panel full-span chemistry-actions"><div className="chemistry-guidance-head"><div><small>NEXT ACTIONS</small><h2>{bi(lang,"شو تعمل هلق؟","What should you do now?")}</h2></div></div><div className="chemistry-action-list">{actionItems.map((x,i)=><div className={`chemistry-action-row ${x.level}`} key={x.key}><span className="chemistry-action-rank">{i+1}</span><div><b>{x.titleAr}</b><p>{lang==="ar"?x.actionAr:x.actionEn}</p></div><button className="btn" onClick={()=>setSelected(x.key)}>{bi(lang,"عرض الرسم","View trend")}</button></div>)}</div>{!actionItems.length&&assessment.score!==null&&<div className="inline-alert good">✓ {bi(lang,"لا يوجد إجراء تصحيحي رئيسي الآن.","No major corrective action is needed now.")}</div>}</section>
 <div className="card panel full-span"><div className="table-wrap"><table><thead><tr><th>{tr(lang,"parameter")}</th><th>{tr(lang,"current")}</th><th>Ideal / Safe</th><th>Score</th><th>{bi(lang,"العمر","Age")}</th><th>{bi(lang,"الثقة","Confidence")}</th></tr></thead><tbody>{keys.map(k=>{const m:any=cfg[k],sample=samples[k],s=parameterScore(sample?.value,m),fresh=guidance.all.find(x=>x.key===k)?.freshnessDays;return <tr key={k}><td>{m.label}</td><td>{sample?.value??"—"}</td><td>{m.ideal[0]}–{m.ideal[1]} / {m.safe[0]}–{m.safe[1]}</td><td>{s===null?"—":`${s}%`}</td><td>{sample?`${sample.ageDays<1?"<1":Math.floor(sample.ageDays)}d / ${fresh}d`:"—"}</td><td>{sample?.confidence??"—"}</td></tr>})}</tbody></table></div></div>
 <Modal open={open} title={tr(lang,"addReading")} onClose={()=>setOpen(false)}><div className="inline-alert info">{bi(lang,"اترك أي حقل لم تقسْه فارغاً. Aqua Nexus لن ينسخ آخر قراءة ولن يحوّلها إلى قياس جديد.","Leave every unmeasured field blank. Aqua Nexus will not copy the previous value into a new measurement.")}</div>{formNote&&<div className="inline-alert danger">{formNote}</div>}<div className="form-grid">{keys.map(k=>{const sample=samples[k];return <label className="field" key={k}><span>{cfg[k].label}</span><input type="number" step="any" value={values[k]??""} placeholder={sample?`${bi(lang,"آخر","Last")}: ${sample.value}`:`Ideal ${cfg[k].ideal[0]}–${cfg[k].ideal[1]}`} onChange={e=>setValues(v=>({...v,[k]:e.target.value}))}/></label>})}<label className="field"><span>Test kit / Device</span><input value={testKit} onChange={e=>setTestKit(e.target.value)}/></label><label className="field"><span>{bi(lang,"ثقة القراءة","Reading confidence")}</span><select value={confidence} onChange={e=>setConfidence(e.target.value as any)}><option value="high">{bi(lang,"مرتفعة","High")}</option><option value="medium">{bi(lang,"متوسطة","Medium")}</option><option value="low">{bi(lang,"منخفضة","Low")}</option></select></label><label className="field full-field"><span>{tr(lang,"notes")}</span><textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label></div><div className="modal-actions"><button className="btn" onClick={()=>setOpen(false)}>{tr(lang,"cancel")}</button><button className="btn primary" onClick={save}>{tr(lang,"save")}</button></div></Modal>
 </section>;
}
