"use client";
import { useEffect,useMemo,useState } from "react";
import type { DoserChannel,Tank } from "@/domain/types";
import { useAquaStore } from "@/store/useAquaStore";
import { tr } from "@/i18n";
import { PageHeader } from "@/components/ui/PageHeader";
import { uid,nowISO } from "@/lib/appUtils";
import { chemistryCatalogForTank } from "@/domain/chemistryProfile";
import { calculateDose,DOSING_PRESETS,type DosingForm,type DosingParameter } from "@/domain/dosingCalculator";
import { chemistryGuidance } from "@/domain/chemistryGuidance";
import { latestParameterSample,validateChemistryValue,validateDosingTarget } from "@/domain/chemistryDataQuality";

const colors=["#27c2dc","#62d48f","#f6c85f","#c877ff","#ff7e79","#4b8bff"];
function idealTarget(tank:Tank,param:DosingParameter){const meta:any=chemistryCatalogForTank(tank)?.[param];return meta?.ideal?(Number(meta.ideal[0])+Number(meta.ideal[1]))/2:param==="KH"?8:param==="Ca"?430:1325;}
function datePlusDays(days:number){return new Date(Date.now()+days*86400000).toISOString().slice(0,10);}

export function DosingPage({tank}:{tank:Tank}) {
 const lang=useAquaStore(s=>s.language),patch=useAquaStore(s=>s.patchTank),availableParams:DosingParameter[]=tank.type==="marine"?["KH","Ca","Mg"]:["KH"];
 const [param,setParam]=useState<DosingParameter>("KH"),[target,setTarget]=useState(()=>idealTarget(tank,"KH")),[form,setForm]=useState<DosingForm>("dry"),[presetId,setPresetId]=useState("nahco3"),[purity,setPurity]=useState(100),[stockGramsPerLiter,setStockGramsPerLiter]=useState(84),[productRaise,setProductRaise]=useState(0);
 useEffect(()=>{setTarget(idealTarget(tank,param));const first=DOSING_PRESETS.find(x=>x.parameter===param);if(first)setPresetId(first.id);},[param,tank.id]);
 const presets=DOSING_PRESETS.filter(x=>x.parameter===param),chosen=presets.find(x=>x.id===presetId)??presets[0],guide=useMemo(()=>chemistryGuidance(tank),[tank]),sample=useMemo(()=>latestParameterSample(tank,param),[tank,param]);
 const current=sample?.value,readingAgeHours=sample?Math.max(0,(Date.now()-new Date(sample.timestamp).getTime())/3600000):99999,currentIssue=current===undefined?undefined:validateChemistryValue(tank,param,current),dataIssue=guide.dataIssues.find(x=>x.key===param),targetCheck=useMemo(()=>validateDosingTarget(tank,param,target),[tank,param,target]);
 const dosingReady=current!==undefined&&readingAgeHours<=48&&sample?.confidence!=="low"&&!currentIssue&&!dataIssue&&!targetCheck.blocked;
 const calc=useMemo(()=>calculateDose({parameter:param,current:current??Number.NaN,target,volumeLiters:tank.systemVolumeLiters,form,presetId:chosen?.id,purityPercent:purity,stockGramsPerLiter,productRaisePerMlPer100L:productRaise}),[param,current,target,tank.systemVolumeLiters,form,chosen?.id,purity,stockGramsPerLiter,productRaise]);
 function setCount(n:number){patch(tank.id,t=>{const channels=[...t.doserChannels];while(channels.length<n)channels.push({id:uid("dc"),name:`Channel ${channels.length+1}`,material:"",capacityMl:1000,currentMl:1000,consumption:0,period:"daily",color:colors[channels.length%colors.length]});return {...t,doserChannels:channels.slice(0,n)};});}
 function updateChannel(id:string,p:Partial<DoserChannel>){patch(tank.id,t=>({...t,doserChannels:t.doserChannels.map(x=>x.id===id?{...x,...p}:x)}))}
 function log(){
  if(!calc.valid||!dosingReady||current===undefined||targetCheck.blocked)return;
  if(targetCheck.level==="warn"&&!window.confirm(lang==="ar"?`${targetCheck.ar} هل تريد المتابعة ضمن المجال الآمن؟`:`${targetCheck.en} Continue within the safe range?`))return;
  const material=form==="product"?(lang==="ar"?"محلول تجاري":"Commercial product"):(lang==="ar"?chosen?.ar:chosen?.en)||chosen?.formula||param,ts=nowISO();
  patch(tank.id,t=>{const channels=calc.steps===1&&calc.unit==="mL"?t.doserChannels.map(ch=>ch.material.trim().toLowerCase()===material.trim().toLowerCase()?{...ch,currentMl:Math.max(0,ch.currentMl-calc.amount)}:ch):t.doserChannels;const dose:any={id:uid("dose"),timestamp:ts,parameter:param,current,target,ml:calc.unit==="mL"?calc.amount:0,amount:calc.amount,unit:calc.unit,material,calculatorMode:form,steps:calc.steps,perStep:calc.perStep,status:calc.steps>1?"planned":"logged",sourceReadingTimestamp:sample?.timestamp};const amountText=`${calc.amount.toFixed(calc.unit==="g"?2:1)} ${calc.unit}`,perStepText=`${calc.perStep.toFixed(calc.unit==="g"?2:1)} ${calc.unit}`;const stepTasks=Array.from({length:calc.steps},(_,i)=>({id:uid("task"),title:`جرعة ${param} ${i+1}/${calc.steps}: ${perStepText}`,titleEn:`${param} dose ${i+1}/${calc.steps}: ${perStepText}`,cadence:"once" as const,done:false,nextDue:datePlusDays(i),manual:true}));const retestTasks=Array.from({length:calc.steps},(_,i)=>({id:uid("task"),title:`إعادة قياس ${param} بعد الجرعة ${i+1}/${calc.steps}`,titleEn:`Retest ${param} after dose ${i+1}/${calc.steps}`,cadence:"once" as const,done:false,nextDue:datePlusDays(i+1),manual:true}));return {...t,doserChannels:channels,dosing:[dose,...t.dosing],timeline:[{id:uid("ev"),timestamp:ts,type:"dosing",textAr:calc.steps>1?`تم إنشاء خطة تصحيح ${param} من القراءة الموثقة ${current} إلى ${target}: ${amountText} من ${material} على ${calc.steps} جرعات.`:`تم تسجيل جرعة ${material}: ${amountText} اعتماداً على القراءة الموثقة ${current} للوصول إلى ${target}.`,textEn:calc.steps>1?`Created ${param} correction plan from verified reading ${current} to ${target}: ${amountText} of ${material} over ${calc.steps} doses.`:`Logged ${material} dose: ${amountText}, based on verified reading ${current} toward ${target}.`},...t.timeline],maintenance:[...t.maintenance,...stepTasks,...retestTasks]};});
 }
 function projectedDays(ch:DoserChannel){const daily=ch.period==="daily"?ch.consumption:ch.period==="weekly"?ch.consumption/7:ch.consumption/30;return daily>0?Math.floor(ch.currentMl/daily):null;}
 const amountLabel=calc.valid?`${calc.amount.toFixed(calc.unit==="g"?2:1)} ${calc.unit}`:"—",stepLabel=calc.valid?`${calc.perStep.toFixed(calc.unit==="g"?2:1)} ${calc.unit}`:"—",safetyLimit=param==="KH"?"1 dKH/day":param==="Mg"?"100 ppm/day":"25 ppm/day";
 return <section className="page-grid"><PageHeader eyebrow="DOSING & CHEMISTRY" title={tr(lang,"dosing")}/>
 <div className="card panel full-span"><div className="module-head"><div><h3>{lang==="ar"?"حاسبة الجرعات الكيميائية":"Chemical Dosing Calculator"}</h3><p className="note">{lang==="ar"?"الجرعة الفعلية مربوطة حصراً بآخر قراءة مسجلة لنفس البارامتر. لتغيير Current لازم تسجل قياساً جديداً في Chemistry؛ ما عاد ممكن تغيير الرقم داخل الحاسبة وتجاوز التحقق.":"Actual dosing is bound to the latest logged measurement of the same parameter. To change Current, log a new Chemistry measurement; the calculator cannot override the verified source value."}</p></div><span className="scene-badge">{tank.systemVolumeLiters.toFixed(1)} L</span></div>
 <div className="form-grid"><label className="field"><span>{lang==="ar"?"البارامتر":"Parameter"}</span><select value={param} onChange={e=>setParam(e.target.value as DosingParameter)}>{availableParams.map(p=><option key={p} value={p}>{p}</option>)}</select></label><label className="field"><span>{lang==="ar"?"القراءة الحالية الموثقة":"Verified current reading"}</span><input type="number" step="any" value={current??""} readOnly placeholder={lang==="ar"?"لا توجد قراءة":"No logged reading"}/>{sample&&<small>{new Date(sample.timestamp).toLocaleString()} • {sample.source} • {sample.confidence}</small>}</label><label className="field"><span>{lang==="ar"?"الهدف":"Target"}</span><input type="number" step="any" value={target} onChange={e=>setTarget(Number(e.target.value))}/></label><label className="field"><span>{lang==="ar"?"شكل الجرعة":"Dose form"}</span><select value={form} onChange={e=>setForm(e.target.value as DosingForm)}><option value="dry">{lang==="ar"?"مادة جافة":"Dry compound"}</option><option value="stock">{lang==="ar"?"محلول محضر بتركيز معروف":"Known stock solution"}</option><option value="product">{lang==="ar"?"منتج تجاري حسب الملصق":"Commercial product label"}</option></select></label></div>
 {form!=="product"&&<div className="form-grid" style={{marginTop:12}}><label className="field"><span>{lang==="ar"?"المركب":"Compound"}</span><select value={chosen?.id||""} onChange={e=>setPresetId(e.target.value)}>{presets.map(x=><option value={x.id} key={x.id}>{lang==="ar"?x.ar:x.en} — {x.formula}</option>)}</select></label><label className="field"><span>{lang==="ar"?"النقاوة %":"Purity %"}</span><input type="number" min="1" max="100" step="1" value={purity} onChange={e=>setPurity(Number(e.target.value))}/></label>{form==="stock"&&<label className="field"><span>{lang==="ar"?"تركيز المحلول غ/لتر":"Stock concentration g/L"}</span><input type="number" min="0" step="any" value={stockGramsPerLiter} onChange={e=>setStockGramsPerLiter(Number(e.target.value))}/></label>}</div>}
 {form==="product"&&<div className="form-grid" style={{marginTop:12}}><label className="field full-field"><span>{lang==="ar"?`حسب ملصق المنتج: 1 mL لكل 100 L يرفع ${param} بمقدار`:`Product label: 1 mL per 100 L raises ${param} by`}</span><input type="number" min="0" step="any" value={productRaise||""} onChange={e=>setProductRaise(Number(e.target.value))} placeholder={lang==="ar"?"أدخل القيمة المكتوبة على العبوة":"Enter label value"}/></label></div>}
 <div className="summary-strip" style={{marginTop:14}}><div className="summary"><small>{lang==="ar"?"الفرق المطلوب":"Required change"}</small><b>{current===undefined?"—":Math.max(0,target-current).toFixed(2)} {param==="KH"?"dKH":"ppm"}</b></div><div className="summary"><small>{lang==="ar"?"الكمية المحسوبة":"Calculated amount"}</small><b>{amountLabel}</b></div><div className="summary"><small>{lang==="ar"?"عدد الأيام/الخطوات":"Days / steps"}</small><b>{calc.valid?calc.steps:"—"}</b></div><div className="summary"><small>{lang==="ar"?"الكمية بكل خطوة":"Per step"}</small><b>{stepLabel}</b></div><div className="summary"><small>{lang==="ar"?"حد الأمان اليومي":"Daily safety limit"}</small><b>{safetyLimit}</b></div></div>
 <div className={`inline-alert ${targetCheck.level==="danger"?"danger":targetCheck.level==="warn"?"warn":"good"}`} style={{marginTop:12}}>{lang==="ar"?targetCheck.ar:targetCheck.en}</div>
 {!dosingReady&&<div className="inline-alert danger" style={{marginTop:12}}><b>{lang==="ar"?"حماية الجرعات: يلزم قياس حديث وموثوق لنفس البارامتر":"Dosing safety gate: a fresh verified reading of the same parameter is required"}</b><p>{!sample?(lang==="ar"?`ما في قراءة مسجلة لـ ${param}. سجل القياس أولاً.`:`No logged ${param} measurement. Record it first.`):sample.confidence==="low"?(lang==="ar"?"ثقة القراءة منخفضة. أعد القياس قبل الجرعة.":"Reading confidence is low. Retest before dosing."):currentIssue?(lang==="ar"?currentIssue.ar:currentIssue.en):dataIssue?(lang==="ar"?dataIssue.reasonAr:dataIssue.reasonEn):readingAgeHours>48?(lang==="ar"?`قراءة ${param} أقدم من 48 ساعة (${Math.floor(readingAgeHours)} ساعة).`:`${param} reading is older than 48 hours (${Math.floor(readingAgeHours)}h).`):targetCheck.blocked?(lang==="ar"?targetCheck.ar:targetCheck.en):""}</p></div>}
 {!calc.valid&&current!==undefined&&<div className="inline-alert warn" style={{marginTop:12}}>{form==="product"?(lang==="ar"?"أدخل قوة المنتج كما هي مكتوبة على العبوة حتى يتم الحساب.":"Enter the product strength from its label to calculate the dose."):(lang==="ar"?"تأكد أن الهدف أعلى من القراءة الحالية وأن بيانات التركيز صحيحة.":"Make sure the target is above the current reading and concentration data is valid.")}</div>}
 {calc.largeCorrection&&<div className="inline-alert warn" style={{marginTop:12}}>{lang==="ar"?`التصحيح كبير؛ قُسّم إلى ${calc.steps} جرعات يومية محافظة مع إعادة قياس بعد كل خطوة. لا تنفذ الخطوة التالية قبل تأكيد الاستجابة بالقياس.`:`Large correction: split into ${calc.steps} conservative daily doses with a retest after every step. Do not continue until the response is confirmed by measurement.`}</div>}
 {form!=="product"&&<div className="note" style={{marginTop:10}}>{lang==="ar"?"الحساب خاص بالشكل الكيميائي المحدد؛ اختر hydrate/anhydrous الصحيح وأدخل النقاوة الفعلية.":"The calculation is specific to the selected chemical form; choose the correct hydrate/anhydrous form and actual purity."}</div>}
 <div style={{marginTop:12}}><button className="btn primary" onClick={log} disabled={!calc.valid||!dosingReady||targetCheck.blocked}>{calc.steps>1?(lang==="ar"?"إنشاء خطة الجرعات الآمنة":"Create safe dosing plan"):(lang==="ar"?"تسجيل الجرعة وإنشاء مهمة إعادة قياس":"Log dose & create retest task")}</button></div></div>
 <div className="card panel full-span"><div className="module-head"><h3>{tr(lang,"doserManager")}</h3><label className="field compact"><span>{tr(lang,"channels")}</span><input type="number" min="0" max="12" value={tank.doserChannels.length} onChange={e=>setCount(Number(e.target.value))}/></label></div><div className="doser-editor-grid">{tank.doserChannels.map((ch,i)=>{const pct=Math.max(0,Math.min(100,ch.currentMl/ch.capacityMl*100)),days=projectedDays(ch);return <article className="doser-editor-card" key={ch.id}><div className="doser-tank"><div className="doser-liquid animated-liquid" style={{height:`${pct}%`,background:ch.color}}/><div className="doser-info"><b>{ch.material||`Channel ${i+1}`}</b><span>{Math.round(ch.currentMl)} / {ch.capacityMl} mL</span><small>{pct.toFixed(0)}%</small></div></div><div className="form-grid one-col"><label className="field"><span>{tr(lang,"liquid")}</span><input value={ch.material} onChange={e=>updateChannel(ch.id,{material:e.target.value})}/></label><label className="field"><span>{tr(lang,"capacity")} mL</span><input type="number" value={ch.capacityMl} onChange={e=>updateChannel(ch.id,{capacityMl:Number(e.target.value)})}/></label><label className="field"><span>{tr(lang,"remaining")} mL</span><input type="number" value={ch.currentMl} onChange={e=>updateChannel(ch.id,{currentMl:Number(e.target.value)})}/></label><label className="field"><span>{tr(lang,"consumption")}</span><input type="number" step="any" value={ch.consumption} onChange={e=>updateChannel(ch.id,{consumption:Number(e.target.value)})}/></label><label className="field"><span>{tr(lang,"period")}</span><select value={ch.period} onChange={e=>updateChannel(ch.id,{period:e.target.value as any})}><option value="daily">{tr(lang,"daily")}</option><option value="weekly">{tr(lang,"weekly")}</option><option value="monthly">{tr(lang,"monthly")}</option></select></label></div><div className="inline-alert info">{days===null?"—":`${days} ${lang==="ar"?"يوم متوقع حتى النفاد":"estimated days remaining"}`}</div></article>})}</div></div>
 <div className="card panel full-span"><h3>{tr(lang,"timeline")}</h3><div className="history-list">{tank.dosing.slice(0,20).map(x=>{const d:any=x,amount=typeof d.amount==="number"?d.amount:x.ml,unit=d.unit||"mL";return <div className="history-row" key={x.id}><b>{x.parameter}: {amount.toFixed(unit==="g"?2:1)} {unit}{d.material?` • ${d.material}`:""}{d.steps>1?` • ${d.steps} steps`:""}</b><span>{new Date(x.timestamp).toLocaleString()}</span></div>})}</div></div>
 </section>;
}
