"use client";
import { useMemo,useState } from "react";
import type { InventoryCategory,InventoryItem,Tank } from "@/domain/types";
import { INVENTORY_PRESETS } from "@/data/legacyCatalogs";
import { useAquaStore } from "@/store/useAquaStore";
import { tr,bi } from "@/i18n";
import { PageHeader } from "@/components/ui/PageHeader";
import { Modal } from "@/components/ui/Modal";
import { uid } from "@/lib/appUtils";
import { inventoryCategoryLabel,inventoryProfile,unifiedInventory } from "@/domain/inventoryIntelligence";

export function InventoryPage({tank}:{tank:Tank}) {
 const lang=useAquaStore(s=>s.language),patch=useAquaStore(s=>s.patchTank),[open,setOpen]=useState(false),[preset,setPreset]=useState(""),[custom,setCustom]=useState(""),[qty,setQty]=useState(0),[unit,setUnit]=useState("g"),[min,setMin]=useState(0),[category,setCategory]=useState<InventoryCategory>("other"),[subcategory,setSubcategory]=useState("");
 const presets:any[]=[...(INVENTORY_PRESETS as any).common,...(((INVENTORY_PRESETS as any)[tank.type])??[])],p=presets.find(x=>x.id===preset);
 const stock=useMemo(()=>unifiedInventory(tank),[tank]);
 const add=()=>{const name=p?.ar||custom.trim(),nameEn=p?.en||custom.trim();if(!name)return;const base:InventoryItem={id:uid("inv"),presetId:preset||undefined,name,nameEn,category:p?.catAr,categoryEn:p?.catEn,quantity:qty,unit:unit||p?.unit||"",minimum:min||p?.min||0};const inferred=inventoryProfile(base);const finalCategory=preset?inferred.category:category;const consumers:any={feeding:["feeding"],fertilizer:["fertilizer"],co2:["co2"],dosing:["dosing"],supplement:["dosing"],filter_media:["sump"],coral_treatment:["acclimation"],water_prep:["waterChange"],equipment:["equipment"],testing:["testing"],rodi:["rodi"],other:[]};patch(tank.id,t=>({...t,inventory:[...t.inventory,{...base,inventoryCategory:finalCategory,inventorySubcategory:preset?inferred.subcategory:(subcategory.trim()||"other"),tankCompatibility:preset?inferred.tankCompatibility:tank.type,consumedBy:preset?inferred.consumedBy:consumers[finalCategory],stockBehavior:finalCategory==="equipment"?"asset":"consumable"}]}));setOpen(false);setPreset("");setCustom("");setSubcategory("");setCategory("other")};
 const updateGeneral=(id:string,v:number)=>patch(tank.id,t=>({...t,inventory:t.inventory.map(x=>x.id===id?{...x,quantity:v}:x)}));
 const updateConsumable=(equipmentId:string,consumableId:string,v:number)=>patch(tank.id,t=>({...t,equipment:t.equipment.map(e=>e.id===equipmentId?{...e,consumables:(e.consumables??[]).map(c=>c.id===consumableId?{...c,quantityOnHand:v}:c)}:e)}));
 const remove=(id:string)=>patch(tank.id,t=>({...t,inventory:t.inventory.filter(x=>x.id!==id)}));
 return <section className="page-grid"><PageHeader eyebrow="UNIFIED INVENTORY" title={tr(lang,"inventory")} actions={<button className="btn primary" onClick={()=>setOpen(true)}>+ {tr(lang,"addStock")}</button>}/>
 {stock.total===0&&<div className="inline-alert info full-span"><div><b>📦 {bi(lang,"المخزون اختياري بالبداية، لكنه بيخلي التنبيهات أذكى.","Inventory is optional at first, but it makes guidance smarter.")}</b><p>{bi(lang,"ضيف المواد يلي بتستخدمها فعلياً مثل الطعام، الملح، مواد الجرعات أو مستهلكات النباتات. البرنامج بيتابع المتوفر وبيحذرك قبل ما تحتاج مادة وما تلاقيها.","Add only supplies you actually use, such as food, salt, dosing materials or plant supplies. Aqua Nexus tracks availability and can warn you before a needed resource runs out.")}</p><button className="btn primary" onClick={()=>setOpen(true)}>+ {tr(lang,"addStock")}</button></div></div>}
 <div className="card panel full-span"><div className="summary-strip"><div className="summary"><small>{bi(lang,"كل المواد","All stock")}</small><b>{stock.total}</b></div><div className="summary"><small>{bi(lang,"مواد المعدات","Equipment consumables")}</small><b>{stock.consumables.length}</b></div><div className="summary"><small>{bi(lang,"مخزون منخفض","Low stock")}</small><b>{stock.low.length}</b></div></div></div>
 <div className="card panel full-span"><div className="table-wrap"><table><thead><tr><th>{tr(lang,"name")}</th><th>{tr(lang,"category")}</th><th>{tr(lang,"available")}</th><th>{tr(lang,"minimum")}</th><th>{tr(lang,"status")}</th><th></th></tr></thead><tbody>{stock.rows.map(x=><tr key={x.id}><td>{lang==="ar"?x.name:(x.nameEn||x.name)}{x.source==="equipment-consumable"&&<small style={{display:"block"}}>⚙ {bi(lang,"مستهلك مرتبط بجهاز","Equipment consumable")}</small>}</td><td>{inventoryCategoryLabel(x.inventoryCategory||"other",lang)}</td><td><input className="table-input" type="number" value={x.quantity} onChange={e=>x.source==="inventory"?updateGeneral(x.id,Number(e.target.value)):updateConsumable(x.equipmentId!,x.consumableId!,Number(e.target.value))}/> {x.unit}</td><td>{x.minimum}</td><td><span className={`status ${x.quantity<=x.minimum?"warn":""}`}>{x.quantity<=x.minimum?tr(lang,"low"):tr(lang,"good")}</span></td><td>{x.source==="inventory"&&<button className="btn danger" onClick={()=>remove(x.id)}>×</button>}</td></tr>)}</tbody></table></div></div>
 <Modal open={open} title={tr(lang,"addStock")} onClose={()=>setOpen(false)}><div className="form-grid"><label className="field"><span>{tr(lang,"name")}</span><select value={preset} onChange={e=>{const id=e.target.value;setPreset(id);const q=presets.find(x=>x.id===id);if(q){setUnit(q.unit||"");setMin(q.min||0);const preview:InventoryItem={id:"preview",presetId:q.id,name:q.ar,nameEn:q.en,category:q.catAr,categoryEn:q.catEn,quantity:0,unit:q.unit||"",minimum:q.min||0};const prof=inventoryProfile(preview);setCategory(prof.category);setSubcategory(prof.subcategory)}}}><option value="">{tr(lang,"other")}</option>{presets.map(x=><option value={x.id} key={x.id}>{lang==="ar"?x.ar:x.en}</option>)}</select></label>{!preset&&<><label className="field"><span>{tr(lang,"name")}</span><input value={custom} onChange={e=>setCustom(e.target.value)}/></label><label className="field"><span>{tr(lang,"category")}</span><select value={category} onChange={e=>setCategory(e.target.value as InventoryCategory)}><option value="feeding">{bi(lang,"تغذية","Feeding")}</option><option value="fertilizer">{bi(lang,"أسمدة","Fertilizer")}</option><option value="co2">CO₂</option><option value="dosing">{bi(lang,"جرعات كيميائية","Dosing")}</option><option value="supplement">{bi(lang,"متممات","Supplements")}</option><option value="filter_media">{bi(lang,"ميديا فلترة","Filter Media")}</option><option value="coral_treatment">{bi(lang,"علاج المرجان","Coral Treatment")}</option><option value="water_prep">{bi(lang,"تحضير الماء","Water Prep")}</option><option value="equipment">{bi(lang,"تجهيزات","Equipment")}</option><option value="testing">{bi(lang,"فحوص","Testing")}</option><option value="rodi">RO/DI</option><option value="other">{bi(lang,"أخرى","Other")}</option></select></label><label className="field"><span>{bi(lang,"النوع الفرعي","Subcategory")}</span><input value={subcategory} onChange={e=>setSubcategory(e.target.value)}/></label></>}<label className="field"><span>{tr(lang,"quantity")}</span><input type="number" step="any" value={qty} onChange={e=>setQty(Number(e.target.value))}/></label><label className="field"><span>{tr(lang,"unit")}</span><input value={unit} onChange={e=>setUnit(e.target.value)}/></label><label className="field"><span>{tr(lang,"stockThreshold")}</span><input type="number" step="any" value={min} onChange={e=>setMin(Number(e.target.value))}/></label></div><div className="modal-actions"><button className="btn" onClick={()=>setOpen(false)}>{tr(lang,"cancel")}</button><button className="btn primary" onClick={add}>{tr(lang,"save")}</button></div></Modal>
 </section>;
}
