"use client";
import {useMemo,useState} from "react";
import type {LivestockItem,Tank} from "@/domain/types";
import {useAquaStore} from "@/store/useAquaStore";
import {PageHeader} from "@/components/ui/PageHeader";
import {bi} from "@/i18n";
import {uid,nowISO} from "@/lib/appUtils";
import {externalizePhoto,resolvePhotoPreview} from "@/lib/photoStorage";
import {useEffect} from "react";

export function LifeJourneyPage({tank}:{tank:Tank}){
 const lang=useAquaStore(s=>s.language),patch=useAquaStore(s=>s.patchTank);
 const [photoSrc,setPhotoSrc]=useState("");
 const [selected,setSelected]=useState(tank.livestock[0]?.id??""),[type,setType]=useState<NonNullable<LivestockItem["lifeEvents"]>[number]["type"]>("observation"),[note,setNote]=useState(""),[size,setSize]=useState("");
 const item=tank.livestock.find(x=>x.id===selected);
 const itemPhotos=useMemo(()=>tank.photos.filter(p=>p.livestockId===selected).sort((a,b)=>b.timestamp.localeCompare(a.timestamp)),[tank.photos,selected]);
 useEffect(()=>{let active=true;const p=itemPhotos[0];if(!p){setPhotoSrc("");return()=>{active=false}};void resolvePhotoPreview(p).then(v=>{if(active)setPhotoSrc(v||p.dataUrl||"")});return()=>{active=false}},[itemPhotos[0]?.id]);
 const addPhoto=async(file?:File)=>{if(!file||!item)return;try{const raw=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=()=>reject(r.error);r.readAsDataURL(file)}),ts=nowISO(),pid=uid("ph");const stored=await externalizePhoto({id:pid,timestamp:ts,caption:`Life Journey • ${item.name}`,dataUrl:raw,livestockId:item.id,estimatedSizeCm:Number(size)>0?Number(size):undefined});patch(tank.id,t=>({...t,photos:[stored,...t.photos],livestock:t.livestock.map(x=>x.id===item.id?{...x,lifeEvents:[{id:uid("life"),timestamp:ts,type:"observation",note:lang==="ar"?"صورة متابعة للنمو والحالة.":"Growth and condition follow-up photo.",photoId:pid,sizeCm:Number(size)>0?Number(size):undefined},...(x.lifeEvents??[])]}:x),timeline:[{id:uid("ev"),timestamp:ts,type:"life-photo",textAr:`حياة الكائنات • تمت إضافة صورة متابعة لـ ${item.name}.`,textEn:`Life Journey • Follow-up photo added for ${item.nameEn||item.name}.`},...t.timeline]}))}catch{}};
 const events=useMemo(()=>[...(item?.lifeEvents??[])].sort((a,b)=>b.timestamp.localeCompare(a.timestamp)),[item]);
 const add=()=>{if(!item)return;const ts=nowISO(),n=Number(size);patch(tank.id,t=>({...t,
   livestock:t.livestock.map(x=>x.id===item.id?{...x,sizeCm:Number.isFinite(n)&&n>0?n:x.sizeCm,lifeEvents:[{id:uid("life"),timestamp:ts,type,note:note.trim()||undefined,sizeCm:Number.isFinite(n)&&n>0?n:undefined},...(x.lifeEvents??[])]}:x),
   timeline:[{id:uid("ev"),timestamp:ts,type:"livestock-life",textAr:`حياة الكائنات • ${item.name}: ${type}${note?` • ${note}`:""}`,textEn:`Life Journey • ${item.nameEn||item.name}: ${type}${note?` • ${note}`:""}`},...t.timeline]
  }));setNote("");setSize("")};
 return <section className="page-grid"><PageHeader eyebrow="LIFE JOURNEY" title={bi(lang,"حياة الكائنات","Life Journey")}/>
 <section className="card panel full-span"><div className="module-head"><div><h3>{bi(lang,"كل كائن له قصة، وليس مجرد صف في قائمة","Every organism has a story, not just a row")}</h3><p className="note">{bi(lang,"الأسماك والمرجان والنبات والقشريات تستخدم نفس Livestock كمصدر وحيد. النمو، الصحة، التكاثر، Frag أو قص/تقسيم النبات تصبح ذاكرة يفهمها عقل الحوض.","Fish, coral, plants and invertebrates use Livestock as the single source of truth. Growth, health, breeding, fragging and plant propagation become Tank Brain memory.")}</p></div></div>
 <div className="form-grid"><label className="field"><span>{bi(lang,"الكائن","Organism")}</span><select value={selected} onChange={e=>setSelected(e.target.value)}>{tank.livestock.map(x=><option key={x.id} value={x.id}>{lang==="ar"?x.name:(x.nameEn||x.name)}</option>)}</select></label>
 <label className="field"><span>{bi(lang,"الحدث","Event")}</span><select value={type} onChange={e=>setType(e.target.value as any)}><option value="observation">{bi(lang,"ملاحظة","Observation")}</option><option value="growth">{bi(lang,"نمو","Growth")}</option><option value="health">{bi(lang,"تغير صحي","Health change")}</option><option value="transfer">{bi(lang,"نقل","Transfer")}</option></select></label>
 <label className="field"><span>{bi(lang,"الحجم الحالي cm (اختياري)","Current size cm (optional)")}</span><input type="number" min="0" step=".1" value={size} onChange={e=>setSize(e.target.value)}/></label>
 <label className="field full-field"><span>{bi(lang,"ملاحظة","Note")}</span><input value={note} onChange={e=>setNote(e.target.value)}/></label></div>
 <button className="btn primary" disabled={!item} onClick={add}>{bi(lang,"حفظ في ذاكرة الحوض","Save to Tank Memory")}</button>
 {item&&(item.category==="coral"||item.category==="plant"||item.category==="fish")&&<div className="inline-alert info" style={{marginTop:12}}>{item.category==="coral"?bi(lang,"إذا صار المرجان مستقراً ونموه مناسباً، يمكن بدء Frag ومتابعة القطعة الجديدة من قسم التكاثر.","When the coral is stable and growing well, a frag can be started and followed in Propagation & Breeding."):item.category==="plant"?bi(lang,"عندما يصبح نمو النبات مناسباً، يمكن أخذ قصاصة/تقسيم/مدادة ومتابعتها من قسم التكاثر.","When plant growth is suitable, a cutting, division or runner can be followed in Propagation & Breeding."):bi(lang,"عند ظهور سلوك تكاثر أو نسل جديد، تبدأ المتابعة من قسم التكاثر.","When breeding behavior or offspring appears, follow it in Propagation & Breeding.")}</div>}</section>
 <section className="card panel full-span"><div className="module-head"><div><h3>{bi(lang,"صور النمو والحالة","Growth & condition photos")}</h3><p className="note">{bi(lang,"كل صورة تبقى مرتبطة بنفس الكائن وتدخل سجل الصور وذاكرة الرحلة.","Every photo stays attached to the same livestock record and joins the photo journal and journey memory.")}</p></div><label className="btn">{bi(lang,"إضافة صورة","Add photo")}<input type="file" accept="image/*" style={{display:"none"}} onChange={e=>{void addPhoto(e.target.files?.[0]);e.currentTarget.value=""}}/></label></div>{photoSrc&&<img src={photoSrc} alt={item?.name||""} style={{width:"100%",maxHeight:320,objectFit:"cover",borderRadius:14}}/>}<small>{itemPhotos.length} {bi(lang,"صورة متابعة","follow-up photos")}</small></section>
 <section className="card panel full-span"><h3>{bi(lang,"رحلة الكائن","Organism journey")}</h3>{!item?<p className="note">{bi(lang,"أضف كائنات أولاً.","Add livestock first.")}</p>:events.length?events.map(e=><div className="mini-row" key={e.id}><span><b>{e.type}</b> • {new Date(e.timestamp).toLocaleDateString(lang==="ar"?"ar-SY":"en-US")} {e.note&&<>• {e.note}</>}</span><b>{e.sizeCm?e.sizeCm+" cm":""}</b></div>):<p className="note">{bi(lang,"لسا ما في أحداث مسجلة لهذا الكائن.","No life events recorded yet.")}</p>}</section></section>
}