"use client";
import {useEffect,useMemo,useState} from "react";
import type {LivestockItem,Tank} from "@/domain/types";
import {useAquaStore} from "@/store/useAquaStore";
import {PageHeader} from "@/components/ui/PageHeader";
import {bi} from "@/i18n";
import {uid,nowISO} from "@/lib/appUtils";
import {externalizePhoto,resolvePhotoPreview} from "@/lib/photoStorage";

export function LifeJourneyPage({tank}:{tank:Tank}){
 const lang=useAquaStore(s=>s.language),patch=useAquaStore(s=>s.patchTank);
 const [photoSrc,setPhotoSrc]=useState("");
 const [selected,setSelected]=useState(tank.livestock[0]?.id??""),[type,setType]=useState<NonNullable<LivestockItem["lifeEvents"]>[number]["type"]>("observation"),[note,setNote]=useState(""),[size,setSize]=useState("");
 const item=tank.livestock.find(x=>x.id===selected);
 const itemPhotos=useMemo(()=>tank.photos.filter(p=>p.livestockId===selected).sort((a,b)=>b.timestamp.localeCompare(a.timestamp)),[tank.photos,selected]);
 useEffect(()=>{let active=true;const p=itemPhotos[0];if(!p){setPhotoSrc("");return()=>{active=false}};void resolvePhotoPreview(p).then(v=>{if(active)setPhotoSrc(v||p.dataUrl||"")});return()=>{active=false}},[itemPhotos[0]?.id]);
 const addPhoto=async(file?:File)=>{if(!file||!item)return;try{const raw=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=()=>reject(r.error);r.readAsDataURL(file)}),ts=nowISO(),pid=uid("ph");const stored=await externalizePhoto({id:pid,timestamp:ts,caption:`Life Journey • ${item.name}`,dataUrl:raw,livestockId:item.id,estimatedSizeCm:Number(size)>0?Number(size):undefined});patch(tank.id,t=>({...t,photos:[stored,...t.photos],livestock:t.livestock.map(x=>x.id===item.id?{...x,lifeEvents:[{id:uid("life"),timestamp:ts,type:"observation",note:lang==="ar"?"صورة متابعة للنمو والحالة.":"Growth and condition follow-up photo.",photoId:pid,sizeCm:Number(size)>0?Number(size):undefined},...(x.lifeEvents??[])]}:x),timeline:[{id:uid("ev"),timestamp:ts,type:"life-photo",textAr:`حياة الكائنات • تمت إضافة صورة متابعة لـ ${item.name}.`,textEn:`Life Journey • Follow-up photo added for ${item.nameEn||item.name}.`},...t.timeline]}))}catch{}};
 const events=useMemo(()=>[...(item?.lifeEvents??[])].sort((a,b)=>b.timestamp.localeCompare(a.timestamp)),[item]);
 const eventLabel=(v:string)=>({observation:bi(lang,"ملاحظة","Observation"),growth:bi(lang,"نمو","Growth"),health:bi(lang,"الصحة","Health"),transfer:bi(lang,"انتقال","Transfer"),breeding:bi(lang,"تكاثر","Breeding"),frag:"Frag",cutting:bi(lang,"قصاصة","Cutting"),division:bi(lang,"تقسيم","Division"),runner:"Runner"} as Record<string,string>)[v]||v;
 const categoryIcon=item?.category==="fish"?"🐠":item?.category==="coral"?"🪸":item?.category==="plant"?"🌿":"🦐";
 const firstDate=item?.addedAt||events[events.length-1]?.timestamp;
 const daysInTank=firstDate?Math.max(0,Math.floor((Date.now()-new Date(firstDate).getTime())/86400000)):0;
 const sizeEvents=events.filter(e=>typeof e.sizeCm==="number"&&e.sizeCm!>0).slice().reverse();
 const firstSize=sizeEvents[0]?.sizeCm,lastSize=sizeEvents[sizeEvents.length-1]?.sizeCm;
 const growthDelta=firstSize&&lastSize&&sizeEvents.length>1?lastSize-firstSize:undefined;
 const lastEvent=events[0];
 const daysSinceLast=lastEvent?Math.floor((Date.now()-new Date(lastEvent.timestamp).getTime())/86400000):null;
 const nextAction=!item?null:daysSinceLast===null||daysSinceLast>=30?bi(lang,"حان وقت صورة متابعة وقياس جديد حتى نقدر نقارن النمو والحالة.","Time for a new follow-up photo and measurement so growth and condition can be compared."):item.health==="watch"?bi(lang,"الكائن تحت المراقبة: سجل ملاحظة صحة وصورة مقارنة عند أي تغير.","This organism is under watch: log a health observation and comparison photo when anything changes."):bi(lang,`آخر متابعة منذ ${daysSinceLast} يوم. استمر بالتوثيق الدوري بدون تسجيلات زائدة بلا فائدة.`,`Last follow-up was ${daysSinceLast} days ago. Continue periodic documentation without unnecessary entries.`);
 const milestones=item?[{label:bi(lang,"دخل الحوض","Added"),done:true},{label:bi(lang,"أول توثيق","First log"),done:events.length>0},{label:bi(lang,"صورة مقارنة","Photo"),done:itemPhotos.length>0},{label:bi(lang,"قياس نمو","Growth"),done:sizeEvents.length>0},{label:bi(lang,"تكاثر/امتداد","Propagation"),done:events.some(e=>["breeding","frag","cutting","division","runner"].includes(e.type))}]:[];
 const add=()=>{if(!item)return;const ts=nowISO(),n=Number(size);patch(tank.id,t=>({...t,
   livestock:t.livestock.map(x=>x.id===item.id?{...x,sizeCm:Number.isFinite(n)&&n>0?n:x.sizeCm,lifeEvents:[{id:uid("life"),timestamp:ts,type,note:note.trim()||undefined,sizeCm:Number.isFinite(n)&&n>0?n:undefined},...(x.lifeEvents??[])]}:x),
   timeline:[{id:uid("ev"),timestamp:ts,type:"livestock-life",textAr:`حياة الكائنات • ${item.name}: ${type}${note?` • ${note}`:""}`,textEn:`Life Journey • ${item.nameEn||item.name}: ${type}${note?` • ${note}`:""}`},...t.timeline]
  }));setNote("");setSize("")};
 return <section className="page-grid"><PageHeader eyebrow="LIFE JOURNEY" title={bi(lang,"حياة الكائنات","Life Journey")}/>
 <section className="card panel full-span life-hero">{item&&<><div className="life-identity"><div className="life-avatar">{photoSrc?<img src={photoSrc} alt={item.name}/>:<span>{categoryIcon}</span>}</div><div><small>{bi(lang,"الملف الحي","LIVING PROFILE")}</small><h2>{lang==="ar"?item.name:(item.nameEn||item.name)}</h2><p className="note">{daysInTank} {bi(lang,"يوم في الحوض","days in tank")} • {bi(lang,"الحالة","Status")}: <b>{item.health}</b></p></div></div><div className="life-stats"><div><small>{bi(lang,"الأحداث","Events")}</small><b>{events.length}</b></div><div><small>{bi(lang,"الصور","Photos")}</small><b>{itemPhotos.length}</b></div><div><small>{bi(lang,"آخر حجم","Latest size")}</small><b>{lastSize??item.sizeCm??"—"}{(lastSize||item.sizeCm)?" cm":""}</b></div><div><small>{bi(lang,"تغير النمو","Growth change")}</small><b>{growthDelta===undefined?"—":`${growthDelta>=0?"+":""}${growthDelta.toFixed(1)} cm`}</b></div></div><div className="life-milestones">{milestones.map((m,i)=><div key={m.label} className={m.done?"done":""}><span>{m.done?"✓":i+1}</span><small>{m.label}</small></div>)}</div>{nextAction&&<div className="life-coach"><b>{bi(lang,"الخطوة المقترحة","Suggested next step")}</b><p>{nextAction}</p></div>}</>}</section>
 <section className="card panel full-span"><div className="module-head"><div><h3>{bi(lang,"كل كائن له قصة، وليس مجرد صف في قائمة","Every organism has a story, not just a row")}</h3><p className="note">{bi(lang,"الأسماك والمرجان والنبات والقشريات تستخدم نفس Livestock كمصدر وحيد. النمو، الصحة، التكاثر، Frag أو قص/تقسيم النبات تصبح ذاكرة يفهمها عقل الحوض.","Fish, coral, plants and invertebrates use Livestock as the single source of truth. Growth, health, breeding, fragging and plant propagation become Tank Brain memory.")}</p></div></div>
 <div className="form-grid"><label className="field"><span>{bi(lang,"الكائن","Organism")}</span><select value={selected} onChange={e=>setSelected(e.target.value)}>{tank.livestock.map(x=><option key={x.id} value={x.id}>{lang==="ar"?x.name:(x.nameEn||x.name)}</option>)}</select></label>
 <label className="field"><span>{bi(lang,"الحدث","Event")}</span><select value={type} onChange={e=>setType(e.target.value as any)}><option value="observation">{bi(lang,"ملاحظة","Observation")}</option><option value="growth">{bi(lang,"نمو","Growth")}</option><option value="health">{bi(lang,"تغير صحي","Health change")}</option><option value="transfer">{bi(lang,"نقل","Transfer")}</option></select></label>
 <label className="field"><span>{bi(lang,"الحجم الحالي cm (اختياري)","Current size cm (optional)")}</span><input type="number" min="0" step=".1" value={size} onChange={e=>setSize(e.target.value)}/></label>
 <label className="field full-field"><span>{bi(lang,"ملاحظة","Note")}</span><input value={note} onChange={e=>setNote(e.target.value)}/></label></div>
 <button className="btn primary" disabled={!item} onClick={add}>{bi(lang,"حفظ في ذاكرة الحوض","Save to Tank Memory")}</button>
 {item&&(item.category==="coral"||item.category==="plant"||item.category==="fish")&&<div className="inline-alert info" style={{marginTop:12}}>{item.category==="coral"?bi(lang,"إذا صار المرجان مستقراً ونموه مناسباً، يمكن بدء Frag ومتابعة القطعة الجديدة من قسم التكاثر.","When the coral is stable and growing well, a frag can be started and followed in Propagation & Breeding."):item.category==="plant"?bi(lang,"عندما يصبح نمو النبات مناسباً، يمكن أخذ قصاصة/تقسيم/مدادة ومتابعتها من قسم التكاثر.","When plant growth is suitable, a cutting, division or runner can be followed in Propagation & Breeding."):bi(lang,"عند ظهور سلوك تكاثر أو نسل جديد، تبدأ المتابعة من قسم التكاثر.","When breeding behavior or offspring appears, follow it in Propagation & Breeding.")}</div>}</section>
 <section className="card panel full-span"><div className="module-head"><div><h3>{bi(lang,"صور النمو والحالة","Growth & condition photos")}</h3><p className="note">{bi(lang,"كل صورة تبقى مرتبطة بنفس الكائن وتدخل سجل الصور وذاكرة الرحلة.","Every photo stays attached to the same livestock record and joins the photo journal and journey memory.")}</p></div><label className="btn">{bi(lang,"إضافة صورة","Add photo")}<input type="file" accept="image/*" style={{display:"none"}} onChange={e=>{void addPhoto(e.target.files?.[0]);e.currentTarget.value=""}}/></label></div>{photoSrc&&<img src={photoSrc} alt={item?.name||""} style={{width:"100%",maxHeight:320,objectFit:"cover",borderRadius:14}}/>}<small>{itemPhotos.length} {bi(lang,"صورة متابعة","follow-up photos")}</small></section>
 <section className="card panel full-span"><h3>{bi(lang,"رحلة الكائن","Organism journey")}</h3>{!item?<p className="note">{bi(lang,"أضف كائنات أولاً.","Add livestock first.")}</p>:events.length?events.map((e,i)=><div className="journey-event" key={e.id}><div className="journey-dot">{i===0?"●":"○"}</div><div><small>{new Date(e.timestamp).toLocaleDateString(lang==="ar"?"ar-SY":"en-US")}</small><h4>{eventLabel(e.type)}</h4>{e.note&&<p>{e.note}</p>}</div><b>{e.sizeCm?e.sizeCm+" cm":""}</b></div>):<p className="note">{bi(lang,"لسا ما في أحداث مسجلة لهذا الكائن.","No life events recorded yet.")}</p>}</section><style jsx>{` .life-hero{overflow:hidden}.life-identity{display:flex;gap:14px;align-items:center}.life-avatar{width:92px;height:92px;border-radius:22px;display:grid;place-items:center;overflow:hidden;background:rgba(40,215,255,.08);border:1px solid rgba(40,215,255,.2);font-size:44px}.life-avatar img{width:100%;height:100%;object-fit:cover}.life-identity h2{margin:3px 0}.life-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:16px}.life-stats>div{padding:10px;border-radius:12px;background:rgba(40,215,255,.045);display:flex;flex-direction:column;gap:4px}.life-stats b{font-size:18px}.life-milestones{display:flex;gap:4px;margin-top:16px;overflow-x:auto}.life-milestones>div{min-width:88px;flex:1;text-align:center;opacity:.45}.life-milestones>div.done{opacity:1}.life-milestones span{margin:auto;display:grid;place-items:center;width:28px;height:28px;border-radius:50%;background:rgba(40,215,255,.12);border:1px solid rgba(40,215,255,.22)}.life-milestones .done span{background:rgba(77,235,171,.14)}.life-milestones small{display:block;margin-top:5px}.life-coach{margin-top:14px;padding:12px;border-radius:14px;border:1px solid rgba(77,235,171,.2);background:rgba(77,235,171,.045)}.life-coach p{margin:5px 0 0}.journey-event{display:grid;grid-template-columns:30px 1fr auto;gap:8px;padding:12px 0;border-bottom:1px solid rgba(255,255,255,.06)}.journey-dot{color:#67e8ff;text-align:center}.journey-event h4,.journey-event p{margin:2px 0}@media(max-width:600px){.life-stats{grid-template-columns:repeat(2,1fr)}.life-avatar{width:76px;height:76px}.life-milestones>div{min-width:74px}.journey-event{grid-template-columns:24px 1fr auto}} `}</style></section>
}