"use client";
import { useMemo,useState } from "react";
import type { RODIServiceEvent,Tank } from "@/domain/types";
import { useAquaStore } from "@/store/useAquaStore";
import { tr,bi } from "@/i18n";
import { PageHeader } from "@/components/ui/PageHeader";
import { uid,nowISO } from "@/lib/appUtils";
import { rodiIntelligence } from "@/domain/rodiIntelligence";
import { inventoryForConsumer,inventoryProfile } from "@/domain/inventoryIntelligence";
import { consumeInventory,inventoryConsumptionMessage } from "@/domain/inventoryConsumption";

export function RODIPage({tank}:{tank:Tank}) {
 const lang=useAquaStore(s=>s.language),patch=useAquaStore(s=>s.patchTank),[tin,setTin]=useState(150),[tout,setTout]=useState(0),[liters,setLiters]=useState(20),[waste,setWaste]=useState(60),[minutes,setMinutes]=useState(60),[psi,setPsi]=useState(0),[serviceComponent,setServiceComponent]=useState<RODIServiceEvent["component"]>("sediment"),[serviceItemId,setServiceItemId]=useState(""),[serviceQty,setServiceQty]=useState("1"),[serviceNotes,setServiceNotes]=useState("");
 const intel=useMemo(()=>rodiIntelligence(tank),[tank]);
 const rodiStock=useMemo(()=>inventoryForConsumer(tank,"rodi"),[tank]);
 const serviceStock=useMemo(()=>rodiStock.filter(item=>{const sub=inventoryProfile(item).subcategory;return serviceComponent==="sediment"?sub==="sediment_filter":serviceComponent==="carbon"?sub==="carbon_filter":sub==="di_resin"}),[rodiStock,serviceComponent]);
 const add=()=>{const ts=nowISO();patch(tank.id,t=>({...t,rodi:[{id:uid("ro"),timestamp:ts,tdsIn:tin,tdsOut:tout,liters,wasteLiters:waste||undefined,productionMinutes:minutes||undefined,sourcePressurePsi:psi||undefined},...t.rodi],timeline:[{id:uid("ev"),timestamp:ts,type:"rodi",textAr:`تم تسجيل دفعة RO/DI: TDS ${tin} → ${tout}, إنتاج ${liters}L.`,textEn:`RO/DI batch logged: TDS ${tin} → ${tout}, ${liters} L produced.`},...t.timeline]}))};
 const logService=()=>{
  const selected=serviceStock.find(x=>x.id===serviceItemId),q=Number(serviceQty);
  if(!selected){window.alert(bi(lang,"اختر المستهلك الصحيح من مخزون RO/DI أولاً.","Select the matching RO/DI consumable from inventory first."));return}
  const use=consumeInventory(tank.inventory,[{inventoryItemId:selected.id,quantity:q,role:`rodi_${serviceComponent}`}]);
  if(!use.ok){window.alert(inventoryConsumptionMessage(use,lang));return}
  const ts=nowISO(),label=serviceComponent==="sediment"?bi(lang,"فلتر الرواسب","Sediment filter"):serviceComponent==="carbon"?bi(lang,"فلتر الكربون","Carbon filter"):bi(lang,"راتنج DI","DI resin");
  const event:RODIServiceEvent={id:uid("ro-service"),timestamp:ts,component:serviceComponent,inventoryUse:use.uses[0],notes:serviceNotes||undefined};
  patch(tank.id,t=>({...t,inventory:use.inventory,rodiServiceEvents:[event,...(t.rodiServiceEvents??[])],timeline:[{id:uid("ev"),timestamp:ts,type:"rodi-service",textAr:`تم استبدال ${label} وخصم ${q} ${selected.unit} من المخزون.`,textEn:`${label} replaced and ${q} ${selected.unit} deducted from inventory.`},...t.timeline]}));
  setServiceItemId("");setServiceNotes("");
 };
 const liveRejection=tin>0?(1-tout/tin)*100:0,eff=(liters+waste)>0?liters/(liters+waste)*100:0,rate=minutes>0?liters/(minutes/60):0;
 return <section className="page-grid"><PageHeader eyebrow="RO/DI INTELLIGENCE" title={tr(lang,"rodi")}/>
 <div className="card panel full-span"><div className="module-head"><div><h3>{bi(lang,"صحة منظومة RO/DI","RO/DI system health")}</h3></div><span className={`status ${intel.status==="danger"?"danger":intel.status==="watch"?"warn":""}`}>{intel.status}</span></div><div className="summary-strip"><div className="summary"><small>{bi(lang,"رفض الممبرين","Membrane rejection")}</small><b>{intel.rejection===null?"—":`${intel.rejection.toFixed(1)}%`}</b></div><div className="summary"><small>{bi(lang,"كفاءة الماء","Water efficiency")}</small><b>{intel.efficiency===null?"—":`${intel.efficiency.toFixed(1)}%`}</b></div><div className="summary"><small>{bi(lang,"اتجاه TDS الخارج","Output TDS trend")}</small><b>{intel.trend}</b></div></div>{intel.notes.map((x,i)=><div className="inline-alert info" key={i}>{x}</div>)}</div>
 <div className="card panel"><div className="form-grid"><label className="field"><span>{tr(lang,"tdsIn")}</span><input type="number" value={tin} onChange={e=>setTin(Number(e.target.value))}/></label><label className="field"><span>{tr(lang,"tdsOut")}</span><input type="number" value={tout} onChange={e=>setTout(Number(e.target.value))}/></label><label className="field"><span>{tr(lang,"producedLiters")}</span><input type="number" value={liters} onChange={e=>setLiters(Number(e.target.value))}/></label><label className="field"><span>{bi(lang,"ماء الرفض L","Waste water L")}</span><input type="number" value={waste} onChange={e=>setWaste(Number(e.target.value))}/></label><label className="field"><span>{bi(lang,"وقت الإنتاج بالدقائق","Production minutes")}</span><input type="number" value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/></label><label className="field"><span>{bi(lang,"ضغط المصدر PSI","Source pressure PSI")}</span><input type="number" value={psi||""} onChange={e=>setPsi(Number(e.target.value))}/></label></div><div className="summary-strip"><div className="summary"><small>{bi(lang,"رفض مباشر","Live rejection")}</small><b>{liveRejection.toFixed(1)}%</b></div><div className="summary"><small>{bi(lang,"كفاءة","Efficiency")}</small><b>{eff.toFixed(1)}%</b></div><div className="summary"><small>{bi(lang,"إنتاجية","Production rate")}</small><b>{rate.toFixed(1)} L/h</b></div></div><button className="btn primary" onClick={add}>{tr(lang,"logBatch")}</button></div>
 <div className="card panel full-span"><div className="module-head"><div><h3>{bi(lang,"صيانة مستهلكات RO/DI","RO/DI consumable service")}</h3><p className="note">{bi(lang,"وقت تبديل فلتر الرواسب أو الكربون أو راتنج DI، سجّل الاستبدال هون ليُخصم المخزون ويتوثق تاريخ الخدمة.","When replacing sediment, carbon, or DI resin, log it here so stock is deducted and service history is retained.")}</p></div></div><div className="form-grid"><label className="field"><span>{bi(lang,"المرحلة","Stage")}</span><select value={serviceComponent} onChange={e=>{setServiceComponent(e.target.value as RODIServiceEvent["component"]);setServiceItemId("")}}><option value="sediment">{bi(lang,"فلتر الرواسب","Sediment filter")}</option><option value="carbon">{bi(lang,"فلتر الكربون","Carbon filter")}</option><option value="di">{bi(lang,"راتنج DI","DI resin")}</option></select></label><label className="field"><span>{bi(lang,"المستهلك من المخزون","Inventory consumable")}</span><select value={serviceItemId} onChange={e=>setServiceItemId(e.target.value)}><option value="">{bi(lang,"اختر المادة","Select item")}</option>{serviceStock.map(x=><option key={x.id} value={x.id}>{lang==="ar"?x.name:(x.nameEn||x.name)} • {x.quantity} {x.unit}</option>)}</select></label><label className="field"><span>{bi(lang,"الكمية المستخدمة","Amount used")}</span><input type="number" min="0" step="any" value={serviceQty} onChange={e=>setServiceQty(e.target.value)}/></label><label className="field"><span>{tr(lang,"notes")}</span><input value={serviceNotes} onChange={e=>setServiceNotes(e.target.value)}/></label></div>{serviceStock.length===0&&<div className="inline-alert info">{bi(lang,"ما في مستهلك مطابق لهذه المرحلة بالمخزون حالياً.","No matching consumable for this stage is currently in inventory.")}</div>}<button className="btn primary" onClick={logService} disabled={!serviceItemId}>{bi(lang,"تسجيل الاستبدال وخصم المخزون","Log replacement & deduct stock")}</button><div className="history-list" style={{marginTop:12}}>{(tank.rodiServiceEvents??[]).slice(0,8).map(x=><div className="history-row" key={x.id}><b>{x.component==="sediment"?bi(lang,"فلتر الرواسب","Sediment filter"):x.component==="carbon"?bi(lang,"فلتر الكربون","Carbon filter"):bi(lang,"راتنج DI","DI resin")}</b><span>{new Date(x.timestamp).toLocaleString()}</span><small>{x.inventoryUse?`${x.inventoryUse.quantity} ${x.inventoryUse.unit} • ${x.inventoryUse.name||""}`:""}</small></div>)}</div></div>
 <div className="card panel"><div className="history-list">{tank.rodi.map(x=><div className="history-row" key={x.id}><b>{x.liters} L • TDS {x.tdsIn} → {x.tdsOut}</b><span>{new Date(x.timestamp).toLocaleString()}</span><small>{x.wasteLiters!==undefined?`Waste ${x.wasteLiters} L`:""} {x.productionMinutes?`• ${x.productionMinutes} min`:""} {x.sourcePressurePsi?`• ${x.sourcePressurePsi} PSI`:""}</small></div>)}</div></div>
 </section>;
}
