"use client";
import {useMemo,useState} from "react";
import type {Tank} from "@/domain/types";
import {useAquaStore} from "@/store/useAquaStore";
import {PageHeader} from "@/components/ui/PageHeader";
import {bi} from "@/i18n";

const DAY=86400000;
const num=(v:unknown)=>Math.max(0,Number(v)||0);
export function TankConsumptionPage({tank}:{tank:Tank}){
 const lang=useAquaStore(s=>s.language),now=Date.now(); const [showHelp,setShowHelp]=useState(false);
 const stats=useMemo(()=>{
  const within=(ts:string,d:number)=>now-new Date(ts).getTime()<=d*DAY;
  const dosing=tank.dosing.filter(x=>within(x.timestamp,30));
  const feeding=tank.feeding.filter(x=>within(x.timestamp,30));
  const plant=(tank.plantCare??[]).filter(x=>within(x.timestamp,30));
  const dose=new Map<string,number>();for(const x of dosing)dose.set(x.parameter,(dose.get(x.parameter)||0)+num(x.ml||x.amount));
  const stock=new Map<string,number>();
  for(const x of feeding)if(x.inventoryQuantityUsed)stock.set(`${x.food}|${x.inventoryUnit||"unit"}`,(stock.get(`${x.food}|${x.inventoryUnit||"unit"}`)||0)+num(x.inventoryQuantityUsed));
  for(const x of plant)if(x.inventoryUse){const k=`${x.inventoryUse.name||x.kind}|${x.inventoryUse.unit}`;stock.set(k,(stock.get(k)||0)+num(x.inventoryUse.quantity));}
  const chem=(key:string)=>tank.chemistry.map(x=>({ts:x.timestamp,v:Number(x.values[key])})).filter(x=>Number.isFinite(x.v)).sort((a,b)=>new Date(b.ts).getTime()-new Date(a.ts).getTime()).slice(0,8);
  const trend=(key:string)=>{const a=chem(key);if(a.length<2)return null;const newest=a[0],oldest=a[a.length-1],days=Math.max(1,(new Date(newest.ts).getTime()-new Date(oldest.ts).getTime())/DAY);return (newest.v-oldest.v)/days};
  const growth30=tank.livestock.flatMap(x=>(x.lifeEvents??[]).filter(e=>e.type==="growth"&&within(e.timestamp,30))).length;
  const remaining=[...stock.entries()].map(([k,used])=>{const [name,unit]=k.split("|"),inv=tank.inventory.find(i=>(i.name===name||i.nameEn===name)&&i.unit===unit);return{name,unit,used,daily:used/30,daysLeft:inv&&used>0?inv.quantity/(used/30):null}});
  return{dose:[...dose.entries()],stock:[...stock.entries()],remaining,feedingCount:feeding.length,growth30,kh:trend("KH"),ca:trend("Ca"),mg:trend("Mg"),no3:trend("NO3"),po4:trend("PO4")};
 },[tank,now]);
 const trendRows=[["KH",stats.kh],["Ca",stats.ca],["Mg",stats.mg],["NO3",stats.no3],["PO4",stats.po4]] as const;
 const evidenceCount=stats.feedingCount+stats.growth30+stats.dose.length+stats.stock.length+trendRows.filter(([,v])=>v!==null).length;
 const confidence=evidenceCount>=12?bi(lang,"بيانات جيدة","Good evidence"):evidenceCount>=5?bi(lang,"بيانات متوسطة","Growing evidence"):bi(lang,"بيانات قليلة","Limited evidence");
 const runway=stats.remaining.filter(x=>x.daysLeft!==null).sort((a,b)=>a.daysLeft!-b.daysLeft!);
 const urgent=runway.filter(x=>x.daysLeft!<=14);
 const maxDose=Math.max(1,...stats.dose.map(([,v])=>v));
 const maxStock=Math.max(1,...stats.stock.map(([,v])=>v));
 const history=useMemo(()=>{const start=now-90*DAY,b=Array.from({length:6},(_,i)=>({start:start+i*15*DAY,end:start+(i+1)*15*DAY,dose:0,feed:0,growth:0}));const hit=(ts:string)=>{const t=new Date(ts).getTime();return b.find(x=>t>=x.start&&t<x.end)};tank.dosing.forEach(x=>{const q=hit(x.timestamp);if(q)q.dose+=num(x.ml||x.amount)});tank.feeding.forEach(x=>{const q=hit(x.timestamp);if(q)q.feed++});tank.livestock.forEach(x=>(x.lifeEvents??[]).forEach(e=>{if(e.type==="growth"){const q=hit(e.timestamp);if(q)q.growth++}}));return b},[tank,now]);
 const spark=(key:"dose"|"feed"|"growth")=>{const vals=history.map(x=>x[key]),mx=Math.max(1,...vals);return vals.map((v,i)=>({v,x:12+i*43.2,y:106-(v/mx)*78}))};
 const sparkPath=(key:"dose"|"feed"|"growth")=>spark(key).map((q,i)=>(i?"L":"M")+" "+q.x+" "+q.y).join(" ");
 const direction=(key:"dose"|"feed"|"growth")=>{const v=history.map(x=>x[key]),a=(v[0]+v[1]+v[2])/3,b=(v[3]+v[4]+v[5])/3;return Math.abs(b-a)<Math.max(.25,a*.12)?bi(lang,"مستقر تقريباً","roughly stable"):b>a?bi(lang,"صاعد","rising"):bi(lang,"هابط","falling")};
 const correlation=tank.type==="marine"
  ?(stats.growth30&&stats.dose.length
    ?bi(lang,"تم تسجيل نمو مع استخدام جرعات خلال آخر 30 يوم. عقل الحوض سيعاملها كعلاقة تستحق المراقبة، وليس كسبب مثبت أو أمراً لرفع الجرعة.","Growth and dosing were both logged in the last 30 days. Tank Brain treats this as a correlation to watch, not proof of causation or an instruction to increase dosing.")
    :bi(lang,"مع تراكم بيانات النمو والتغذية والجرعات سيظهر هنا الربط بين الطلب الحيوي واتجاهات الحوض.","As growth, feeding and dosing evidence accumulates, biological demand correlations will appear here."))
  :(stats.growth30&&(tank.plantCare??[]).length
    ?bi(lang,"تم تسجيل نمو نباتي مع عناية/تسميد. راقب الكيمياء وCO₂ قبل أي تعديل؛ الارتباط لا يعني أن التسميد هو السبب وحده.","Plant growth and care/fertilization were both logged. Review chemistry and CO₂ before changing anything; correlation does not prove causation.")
    :bi(lang,"مع تراكم بيانات النمو والتغذية والجرعات سيظهر هنا الربط بين الطلب الحيوي واتجاهات الحوض.","As growth, feeding and dosing evidence accumulates, biological demand correlations will appear here."));
 return <section className="page-grid"><PageHeader eyebrow="TANK CONSUMPTION" title={bi(lang,"استهلاك الحوض","Tank Consumption")} actions={<button className="btn" aria-label={bi(lang,"التعليمات","Instructions")} title={bi(lang,"التعليمات","Instructions")} onClick={()=>setShowHelp(v=>!v)}>?</button>}/>{showHelp&&<section className="card panel full-span"><h3>{bi(lang,"كيف تقرأ استهلاك الحوض؟","How to read Tank Consumption")}</h3><p className="note">{bi(lang,"الصفحة تحلل سجلات التغذية والجرعات والمخزون والنمو والكيمياء. مسجل يعني بيانات أدخلتها فعلياً، محسوب يعني حساباً مباشراً عليها، وتقديري يعني توقعاً إذا استمر المعدل الحالي. تغير الكيمياء وحده لا يُعتبر استهلاكاً مثبتاً، والتوقعات ليست أوامر جرعات تلقائية.","This page analyzes feeding, dosing, inventory, growth and chemistry logs. Logged means actual recorded data, Calculated means direct arithmetic on it, and Estimated means a projection if the current rate continues. Chemistry drift alone is not proven consumption, and forecasts are not automatic dosing instructions.")}</p></section>
 <section className="card panel full-span metabolism"><div className="metabolism-head"><div><small>AQUARIUM METABOLISM</small><h2>{bi(lang,"بصمة استهلاك الحوض","Tank consumption fingerprint")}</h2><p className="note">{bi(lang,"صورة تشغيلية لما يدخل الحوض وما يستهلكه وما يتغير فيه، مبنية فقط على سجلاتك.","An operational view of what enters the aquarium, what is consumed and what changes, based only on your logs.")}</p></div><div className="evidence-badge"><small>{bi(lang,"قوة الدليل","Evidence")}</small><b>{confidence}</b></div></div><div className="metabolism-flow"><div><span>🍽️</span><b>{stats.feedingCount}</b><small>{bi(lang,"تغذية","feedings")}</small></div><div className="flow-arrow">→</div><div><span>💧</span><b>{stats.dose.length}</b><small>{bi(lang,"جرعات","dosing")}</small></div><div className="flow-arrow">→</div><div><span>↗</span><b>{stats.growth30}</b><small>{bi(lang,"نمو","growth")}</small></div><div className="flow-arrow">→</div><div><span>📈</span><b>{trendRows.filter(([,v])=>v!==null).length}</b><small>{bi(lang,"اتجاهات","trends")}</small></div></div>{urgent.length>0&&<div className="inline-alert warn"><b>{bi(lang,"تنبيه مخزون","Stock attention")}</b><p>{bi(lang,`${urgent.length} مادة قد تنفد خلال 14 يوم إذا استمر معدل الاستخدام الحالي.`,`${urgent.length} item(s) may run out within 14 days if the current usage rate continues.`)}</p></div>}</section>
 <section className="card panel full-span"><h3>{bi(lang,"الاستهلاك المثبت • آخر 30 يوم","Evidence-backed consumption • last 30 days")}</h3><p className="note">{bi(lang,"لا نجمع وحدات مختلفة مع بعضها ولا نسمي تغير الكيمياء استهلاكاً إذا لم يكن لدينا دليل كافٍ.","Different units are never mixed, and chemistry drift is not labeled biological consumption without enough evidence.")}</p>
 <div className="feeding-first-look"><div><small>{bi(lang,"مرات التغذية","Feedings")}</small><b>{stats.feedingCount}</b></div><div><small>{bi(lang,"أحداث نمو","Growth events")}</small><b>{stats.growth30}</b></div><div><small>{bi(lang,"مواد جرعات","Dosing materials")}</small><b>{stats.dose.length}</b></div></div></section>
 <section className="card panel full-span"><h3>{bi(lang,"الجرعات","Dosing")}</h3>{stats.dose.length?stats.dose.map(([p,v])=><div className="consumption-row" key={p}><div><b>{p}</b><small>{v.toFixed(1)} mL / 30d • {(v/30).toFixed(2)} mL/day</small></div><div className="meter"><i style={{width:`${Math.max(4,v/maxDose*100)}%`}}/></div></div>):<p className="note">{bi(lang,"لا توجد جرعات مسجلة.","No dosing history.")}</p>}</section>
 <section className="card panel full-span"><h3>{bi(lang,"التغذية والمواد المستهلكة","Feeding & consumed stock")}</h3>{stats.stock.length?stats.stock.map(([k,v])=>{const [n,u]=k.split("|");return <div className="consumption-row" key={k}><div><b>{n}</b><small>{v.toFixed(2)} {u} / 30d</small></div><div className="meter stock"><i style={{width:`${Math.max(4,v/maxStock*100)}%`}}/></div></div>}):<p className="note">{bi(lang,"لا يوجد استهلاك مخزون مسجل بعد.","No inventory-backed consumption yet.")}</p>}</section>
 <section className="card panel full-span"><h3>{bi(lang,"الاتجاه والتوقع • 90 يوم","Trend & Forecast • 90 days")}</h3><p className="note">{bi(lang,"مقسمة إلى فترات 15 يوم. الخطوط تاريخ مسجل؛ التوقع امتداد للمعدل الحالي وليس قياساً مستقبلياً.","Grouped into 15-day windows. Lines are logged history; forecasts extend the current rate and are not future measurements.")}</p><div className="trend-legend"><span>● {bi(lang,"مسجل","Logged")}</span><span>◐ {bi(lang,"محسوب","Calculated")}</span><span>○ {bi(lang,"تقديري","Estimated")}</span></div><div className="trend-cards">{(["dose","feed","growth"] as const).map(k=><div key={k}><b>{k==="dose"?bi(lang,"الجرعات","Dosing"):k==="feed"?bi(lang,"التغذية","Feeding"):bi(lang,"أحداث النمو","Growth events")}</b><strong>{direction(k)}</strong><svg viewBox="0 0 240 120"><path d="M12 106H228" stroke="currentColor" opacity=".12"/><path d={sparkPath(k)} fill="none" stroke="currentColor" strokeWidth="4"/>{spark(k).map((q,i)=><circle key={i} cx={q.x} cy={q.y} r="3.5" fill="currentColor"/>)}</svg></div>)}</div><div className="forecast-grid"><div><small>{bi(lang,"محسوب","Calculated")}</small><b>{bi(lang,"جرعات 30 يوم إذا استمر المعدل","30d dosing at current rate")}</b><strong>{stats.dose.reduce((s,[,v])=>s+v,0).toFixed(1)} mL</strong></div><div><small>{bi(lang,"تقديري","Estimated")}</small><b>{bi(lang,"أقرب نفاد مخزون","Nearest stock depletion")}</b><strong>{runway[0]?"≈ "+Math.round(runway[0].daysLeft!)+" "+bi(lang,"يوم","days"):"—"}</strong></div></div><div className="inline-alert info"><b>{bi(lang,"كيف نقرأها؟","How to read it")}</b><p>{bi(lang,"مسجل = أدخله المستخدم. محسوب = حساب مباشر على السجل. تقديري = توقع إذا استمر نفس المعدل وقد يتغير.","Logged = user-entered evidence. Calculated = direct arithmetic. Estimated = projection if the current rate continues and may change.")}</p></div></section>
 <section className="card panel full-span"><h3>{bi(lang,"اتجاه القياسات","Measured trends")}</h3>{[["KH",stats.kh],["Ca",stats.ca],["Mg",stats.mg],["NO3",stats.no3],["PO4",stats.po4]].filter(([,v])=>v!==null).map(([k,v])=><div className="mini-row" key={String(k)}><b>{k}</b><span>{Number(v).toFixed(3)} / day • {bi(lang,"اتجاه مرصود، ليس استهلاكاً مثبتاً","observed drift, not proven consumption")}</span></div>)}</section>
 <section className="card panel full-span"><h3>{bi(lang,"توقع نفاد المخزون","Stock runway")}</h3>{stats.remaining.filter(x=>x.daysLeft!==null).map(x=><div className="mini-row" key={x.name+x.unit}><b>{x.name}</b><span>≈ {Math.round(x.daysLeft!)} {bi(lang,"يوم","days")}</span></div>)}</section>
 <section className="card panel full-span"><div className="inline-alert info"><b>{bi(lang,"ربط عقل الحوض","Tank Brain correlation")}</b><p>{correlation}</p></div></section><style jsx>{` .metabolism-head{display:flex;justify-content:space-between;gap:14px;align-items:flex-start}.metabolism h2{margin:3px 0}.evidence-badge{padding:10px 12px;border-radius:14px;background:rgba(77,235,171,.07);border:1px solid rgba(77,235,171,.18);white-space:nowrap}.evidence-badge small,.evidence-badge b{display:block}.metabolism-flow{display:grid;grid-template-columns:1fr auto 1fr auto 1fr auto 1fr;gap:8px;align-items:center;margin:18px 0}.metabolism-flow>div:not(.flow-arrow){text-align:center;padding:12px 6px;border-radius:14px;background:rgba(40,215,255,.045)}.metabolism-flow span,.metabolism-flow b,.metabolism-flow small{display:block}.metabolism-flow span{font-size:25px}.metabolism-flow b{font-size:22px}.flow-arrow{color:#67e8ff}.consumption-row{display:grid;grid-template-columns:minmax(130px,220px) 1fr;gap:12px;align-items:center;padding:10px 0}.consumption-row small{display:block;margin-top:3px}.meter{height:9px;border-radius:99px;background:rgba(255,255,255,.06);overflow:hidden}.meter i{display:block;height:100%;border-radius:99px;background:currentColor;color:#67e8ff}.meter.stock i{color:#7df0c2} .trend-legend{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0}.trend-legend span{padding:5px 8px;border-radius:999px;background:rgba(255,255,255,.04);font-size:12px}.trend-cards{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.trend-cards>div,.forecast-grid>div{padding:12px;border-radius:14px;background:rgba(40,215,255,.035)}.trend-cards b,.trend-cards strong{display:block}.trend-cards svg{width:100%;height:105px;color:#67e8ff}.forecast-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px;margin:12px 0}.forecast-grid small,.forecast-grid b,.forecast-grid strong{display:block}.forecast-grid strong{font-size:20px;margin-top:5px}@media(max-width:600px){.trend-cards,.forecast-grid{grid-template-columns:1fr}.metabolism-head{display:block}.evidence-badge{display:inline-block;margin-top:8px}.metabolism-flow{grid-template-columns:repeat(4,1fr)}.flow-arrow{display:none}.consumption-row{grid-template-columns:1fr}.meter{margin-top:-4px}} `}</style></section>;
}