"use client";
import { useMemo,useState } from "react";
import type { Tank } from "@/domain/types";
import { useAquaStore } from "@/store/useAquaStore";
import { tr,bi } from "@/i18n";
import { PageHeader } from "@/components/ui/PageHeader";
import { uid,nowISO } from "@/lib/appUtils";
import { inventoryForConsumer,inventoryProfile } from "@/domain/inventoryIntelligence";
import { consumeInventory,inventoryConsumptionMessage } from "@/domain/inventoryConsumption";
import { waterChangeIntelligence } from "@/domain/waterChangeIntelligence";

export function WaterChangePage({tank}:{tank:Tank}) {
 const lang=useAquaStore(s=>s.language),patch=useAquaStore(s=>s.patchTank),[liters,setLiters]=useState(Math.round(tank.systemVolumeLiters*.15)),[sal,setSal]=useState(1.025),[temp,setTemp]=useState(25),[notes,setNotes]=useState(""),[saltItemId,setSaltItemId]=useState(""),[saltUsed,setSaltUsed]=useState(""),[conditionerItemId,setConditionerItemId]=useState(""),[conditionerUsed,setConditionerUsed]=useState(""),[freshSaltItemId,setFreshSaltItemId]=useState(""),[freshSaltUsed,setFreshSaltUsed]=useState(""),[rodiBatchId,setRodiBatchId]=useState("");
 const pct=useMemo(()=>tank.systemVolumeLiters?liters/tank.systemVolumeLiters*100:0,[liters,tank.systemVolumeLiters]);
 const intel=useMemo(()=>waterChangeIntelligence(tank,pct,tank.type==="marine"?sal:undefined,temp),[tank,pct,sal,temp]);
 const waterPrepStock=useMemo(()=>inventoryForConsumer(tank,"waterChange"),[tank]);
 const marineSaltStock=useMemo(()=>waterPrepStock.filter(x=>inventoryProfile(x).subcategory==="marine_salt"),[waterPrepStock]);
 const conditionerStock=useMemo(()=>waterPrepStock.filter(x=>inventoryProfile(x).subcategory==="conditioner"),[waterPrepStock]);
 const freshwaterSaltStock=useMemo(()=>waterPrepStock.filter(x=>inventoryProfile(x).subcategory==="freshwater_salt"),[waterPrepStock]);
 const save=()=>{
  if(intel.blocked){window.alert(lang==="ar"?"حجم تغيير الماء غير صالح. راجع كمية اللترات وحجم النظام قبل التسجيل.":"Water-change volume is invalid. Review liters and system volume before logging.");return}
  if(intel.risk==="warn"&&!window.confirm(lang==="ar"?"التغيير أكبر أو أسرع من الروتين المعتاد. راجع السبب ومطابقة ماء التعويض. هل تريد المتابعة؟":"This change is larger or faster than routine. Review the reason and replacement-water match. Continue?"))return;
  if(intel.risk==="danger"){
   if(!window.confirm(lang==="ar"?"⚠️ تغيير ماء عالي الخطورة: الحجم كبير أو في أكثر من عامل اختلاف. لا تكمل إلا إذا عندك سبب واضح وماء التعويض مضبوط. متابعة؟":"⚠️ High-risk water change: the volume is large or multiple mismatch factors are present. Continue only with a clear reason and properly matched replacement water. Continue?"))return;
   if(!window.confirm(lang==="ar"?"تأكيد أخير: Aqua Nexus ينصح بالمراقبة وإعادة القياس بعد التغيير الكبير. هل تم تجهيز الماء فعلياً وتريد تسجيل التنفيذ؟":"Final confirmation: Aqua Nexus recommends close monitoring and retesting after a large change. Is the replacement water actually prepared and do you want to log execution?"))return;
  }
  const selected=[
   tank.type==="marine"&&saltItemId?{inventoryItemId:saltItemId,quantity:Number(saltUsed),role:"marine_salt"}:null,
   tank.type==="freshwater"&&conditionerItemId?{inventoryItemId:conditionerItemId,quantity:Number(conditionerUsed),role:"conditioner"}:null,
   tank.type==="freshwater"&&freshSaltItemId?{inventoryItemId:freshSaltItemId,quantity:Number(freshSaltUsed),role:"freshwater_salt"}:null
  ].filter((x):x is {inventoryItemId:string;quantity:number;role:string}=>Boolean(x));
  const use=consumeInventory(tank.inventory,selected);
  if(!use.ok){window.alert(inventoryConsumptionMessage(use,lang));return}
  const marineSaltUse=use.uses.find(x=>x.role==="marine_salt"),ts=nowISO();
  patch(tank.id,t=>({...t,
   inventory:use.inventory,
   waterChanges:[{id:uid("wc"),timestamp:ts,liters,percent:pct,salinity:t.type==="marine"?sal:undefined,temperature:temp,notes,saltInventoryItemId:marineSaltUse?.inventoryItemId,saltQuantityUsed:marineSaltUse?.quantity,rodiBatchId:rodiBatchId||undefined,inventoryUses:use.uses},...t.waterChanges],
   timeline:[{id:uid("ev"),timestamp:ts,type:"waterchange",textAr:`تم تغيير ${liters} لتر (${pct.toFixed(1)}%)${use.uses.length?` وخصم ${use.uses.length} مادة تحضير من المخزون`:""}.`,textEn:`A ${liters} L water change (${pct.toFixed(1)}%) was logged${use.uses.length?` with ${use.uses.length} preparation item(s) deducted from inventory`:""}.`},...t.timeline]
  }));
 };
 return <section className="page-grid"><PageHeader eyebrow="WATER CHANGE PLANNER" title={tr(lang,"waterChange")}/>
 <div className="card panel full-span"><div className="module-head"><div><h3>{bi(lang,"تخطيط قبل التنفيذ","Plan before changing water")}</h3><p className="note">{bi(lang,`اقتراح أولي حسب القراءات الحالية: حوالي ${intel.suggestedPercent}% عند الحاجة، مع معالجة السبب الأساسي وليس تغيير الماء وحده.`,`Initial suggestion from current readings: about ${intel.suggestedPercent}% when needed, while addressing root cause rather than relying on water changes alone.`)}</p></div><span className={`status ${intel.risk==="danger"?"danger":intel.risk==="warn"?"warn":"good"}`}>{intel.risk==="danger"?bi(lang,"خطر مرتفع","HIGH RISK"):intel.risk==="warn"?bi(lang,"مراجعة","REVIEW"):bi(lang,"طبيعي","NORMAL")}</span></div><div className="summary-strip"><div className="summary"><small>NO3 {bi(lang,"نظري بعد التغيير","theoretical after")}</small><b>{intel.projectedNO3===null?"—":intel.projectedNO3.toFixed(1)}</b></div><div className="summary"><small>PO4 {bi(lang,"نظري بعد التغيير","theoretical after")}</small><b>{intel.projectedPO4===null?"—":intel.projectedPO4.toFixed(3)}</b></div><div className="summary"><small>{bi(lang,"الحجم المقترح","Suggested")}</small><b>{intel.suggestedPercent}%</b></div></div>{intel.warnings.map((w,i)=><div className={`inline-alert ${intel.risk==="danger"?"danger":"warn"}`} key={i}>{w}</div>)}</div>
 <div className="card panel"><div className="inline-alert info"><b>{bi(lang,"قبل ما تسجّل التغيير","Before logging the change")}</b><p>{bi(lang,"حدد كمية الماء يلي رح تغيّرها واضبط حرارة ماء التعويض، وللحوض البحري الملوحة كمان. ربط الملح ودفعة RO/DI بالمخزون اختياري لكنه بيساعد البرنامج يعرف مصدر الماء والمواد المستخدمة.","Choose the water volume and match replacement-water temperature; for marine tanks, match salinity too. Linking salt and an RO/DI batch is optional but gives Aqua Nexus better source and resource context.")}</p></div><div className="form-grid"><label className="field"><span>{tr(lang,"changeLiters")}</span><input type="number" min="0" value={liters} onChange={e=>setLiters(Number(e.target.value))}/></label><label className="field"><span>{tr(lang,"changePercent")}</span><input value={`${pct.toFixed(1)}%`} readOnly/></label>{tank.type==="marine"&&<label className="field"><span>{tr(lang,"replacementSalinity")}</span><input type="number" step=".001" value={sal} onChange={e=>setSal(Number(e.target.value))}/></label>}<label className="field"><span>{tr(lang,"temperature")}</span><input type="number" step=".1" value={temp} onChange={e=>setTemp(Number(e.target.value))}/></label>{tank.type==="marine"&&<><label className="field"><span>{bi(lang,"ملح من المخزون (اختياري)","Salt inventory (optional)")}</span><select value={saltItemId} onChange={e=>setSaltItemId(e.target.value)}><option value="">{bi(lang,"بدون ربط","Not linked")}</option>{marineSaltStock.map(x=><option key={x.id} value={x.id}>{lang==="ar"?x.name:(x.nameEn||x.name)} • {x.quantity} {x.unit}</option>)}</select></label>{saltItemId&&<label className="field"><span>{bi(lang,"كمية الملح المستخدمة","Salt quantity used")}</span><input type="number" min="0" step="any" value={saltUsed} onChange={e=>setSaltUsed(e.target.value)}/></label>}</>}
 {tank.type==="freshwater"&&<><label className="field"><span>{bi(lang,"مزيل كلور / Conditioner","Conditioner")}</span><select value={conditionerItemId} onChange={e=>setConditionerItemId(e.target.value)}><option value="">{bi(lang,"غير مستخدم / غير مربوط","Not used / not linked")}</option>{conditionerStock.map(x=><option key={x.id} value={x.id}>{lang==="ar"?x.name:(x.nameEn||x.name)} • {x.quantity} {x.unit}</option>)}</select></label>{conditionerItemId&&<label className="field"><span>{bi(lang,"الكمية المستخدمة","Amount used")}</span><input type="number" min="0" step="any" value={conditionerUsed} onChange={e=>setConditionerUsed(e.target.value)}/></label>}<label className="field"><span>{bi(lang,"ملح نهري / Aquarium Salt","Freshwater aquarium salt")}</span><select value={freshSaltItemId} onChange={e=>setFreshSaltItemId(e.target.value)}><option value="">{bi(lang,"غير مستخدم / غير مربوط","Not used / not linked")}</option>{freshwaterSaltStock.map(x=><option key={x.id} value={x.id}>{lang==="ar"?x.name:(x.nameEn||x.name)} • {x.quantity} {x.unit}</option>)}</select></label>{freshSaltItemId&&<label className="field"><span>{bi(lang,"الكمية المستخدمة","Amount used")}</span><input type="number" min="0" step="any" value={freshSaltUsed} onChange={e=>setFreshSaltUsed(e.target.value)}/></label>}</>}<label className="field"><span>{bi(lang,"دفعة RO/DI المستخدمة (اختياري)","RO/DI batch used (optional)")}</span><select value={rodiBatchId} onChange={e=>setRodiBatchId(e.target.value)}><option value="">{bi(lang,"غير محدد","Not specified")}</option>{tank.rodi.slice(0,10).map(x=><option key={x.id} value={x.id}>{new Date(x.timestamp).toLocaleDateString()} • {x.liters} L • TDS {x.tdsOut}</option>)}</select></label><label className="field full-field"><span>{tr(lang,"notes")}</span><textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label></div><button className="btn primary" onClick={save} disabled={intel.blocked||!Number.isFinite(liters)||liters<=0}>{tr(lang,"waterChangeLog")}</button></div>
 <div className="card panel"><div className="history-list">{tank.waterChanges.map(x=><div className="history-row" key={x.id}><b>{x.liters} L • {x.percent.toFixed(1)}%</b><span>{new Date(x.timestamp).toLocaleString()}</span></div>)}</div></div>
 </section>;
}
